In [1]:
from pathlib import Path
import re
from pprint import pprint
from sentence_transformers import CrossEncoder
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

In [2]:
# Questions 目录
QUESTIONS_DIR = Path("./Questions")

# ———————————————————— 参数：拆分用 ————————————————————
# 8 个固定 section
SECTION_TITLES = [
    "Problem Interface",
    "Formal Definitions",
    "Required Complexity",
    "Maintained State",
    "Invariants",
    "Per-Operation Update Rules",
    "Output Rule",
    "Edge Cases and Consistency Checks",
]

SECTION_VARS = {
    "Problem Interface": "ProblemInterface",
    "Formal Definitions": "FormalDefinitions",
    "Required Complexity": "RequiredComplexity",
    "Maintained State": "MaintainedState",
    "Invariants": "Invariants",
    "Per-Operation Update Rules": "PerOperationUpdateRules",
    "Output Rule": "OutputRule",
    "Edge Cases and Consistency Checks": "EdgeCasesAndConsistencyChecks",
}

FIRST_SECTION_MARK = "### [1] Problem Interface"

SECTION_PATTERN = re.compile(
    r"^###\s*\[(\d+)\]\s*(.+?)\s*$",
    re.MULTILINE
)

NUMBERED_STEP_RE = re.compile(r"^\s*\d+\.\s+")



# ———————————————————— 参数：CrossEncoder计算用 ————————————————————
model = CrossEncoder("cross-encoder/stsb-roberta-large")

# 块名顺序
KEY_ORDER = [
    "ProblemInterface",                  # 1
    "FormalDefinitions",                 # 2
    "RequiredComplexity",                # 3
    "MaintainedState",                   # 4
    "Invariants",                        # 5
    "PerOperationUpdateRules",           # 6
    "OutputRule",                        # 7
    "EdgeCasesAndConsistencyChecks",     # 8
    "Note",                              # 9
]

# 对应矩阵变量名
MAT_NAMES = [
    "mat1PI",
    "mat2FD",
    "mat3RC",
    "mat4MS",
    "mat5INV",
    "mat6POUR",
    "mat7OR",
    "mat8ECCC",
    "mat9N",
]

# ———————————————————— 参数：数据分析 ————————————————————

TARGET_Q_INDEX = 0   # 指定打印 / 分析第几个题目（从 0 开始）

# k和temp必须严格与QtoE中的一致
k = 20
temperature_list = [0.0, 0.2, 0.5, 0.8]

ROUND_DIGITS = 6    # 保留几位

# 若只想看部分矩阵，可改成例如 ["mat8ECCC", "mat9N"]
SELECTED_MATS = None

DEFAULT_MAT_NAMES = [
    "mat1PI",    # Problem Interface
    "mat2FD",    # Formal Definitions
    "mat3RC",    # Required Complexity
    "mat4MS",    # Maintained State
    "mat5INV",   # Invariants
    "mat6POUR",  # Per-Operation Update Rules
    "mat7OR",    # Output Rule
    "mat8ECCC",  # Edge Cases and Consistency Checks
    "mat9N",
]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/stsb-roberta-large
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
# 拆分用 函数部分
def list_question_dirs(questions_dir: Path):
    return sorted(
        [p for p in questions_dir.iterdir() if p.is_dir() and not p.name.startswith(".")],
        key=lambda x: x.name
    )


def list_explain_txts(explain_dir: Path):
    txts = []

    for p in explain_dir.iterdir():
        if not (p.is_file() and p.suffix.lower() == ".txt"):
            continue

        parts = p.stem.split()

        if len(parts) >= 1 and parts[0].isdigit():
            txts.append((int(parts[0]), p))

    txts_sorted = sorted(txts, key=lambda x: x[0])
    # display(txts_sorted)

    return [p for _, p in txts_sorted]


def remove_blank_lines(text: str) -> str:
    """
    对块内容做空行剔除：删除所有空行，仅保留非空行并按原顺序拼接。
    """
    if not text:
        return ""
    lines = [line for line in text.splitlines() if line.strip() != ""]
    return "\n".join(lines).strip()


def split_into_8_sections(text: str):
    """
    先切出 8 个块。
    舍弃 ### [1] Problem Interface 之前的任何内容。
    返回 dict:
    {
        'ProblemInterface': ...,
        ...
        'EdgeCasesAndConsistencyChecks': ...
    }
    """
    first_idx = text.find(FIRST_SECTION_MARK)
    if first_idx == -1:
        raise ValueError(f"未找到 '{FIRST_SECTION_MARK}'")

    text = text[first_idx:]
    matches = list(SECTION_PATTERN.finditer(text))
    if not matches:
        raise ValueError("未识别到 section 标题")

    parsed = {v: "" for v in SECTION_VARS.values()}

    for i, m in enumerate(matches):
        title = m.group(2).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        content = text[start:end]

        if title in SECTION_VARS:
            parsed[SECTION_VARS[title]] = content

    return parsed


def extract_note_from_section8(detailed_text: str):
    """
    从第八块中剥离第九块 Note。

    规则：
    1. 先对第八块原始内容处理，不提前删空行。
    2. 只考虑“最后一个由空行分隔出的连续非空块”是否应作为 Note。
    3. 若该最后块内部存在某行匹配 '数字. 空格'（如 5. xxx），
       则说明它属于第八块，不剥离。
    4. 若最后块内部没有编号行，且它前面由空行分隔，则将其剥离为 Note。
    5. 因为是按空行分块，若前面有编号步骤但中间已有空行断开，则最后块不再属于该步骤。
    """
    if not detailed_text.strip():
        return "", ""

    lines = detailed_text.splitlines()

    # 去掉末尾空行，便于找最后非空块
    end = len(lines) - 1
    while end >= 0 and lines[end].strip() == "":
        end -= 1

    if end < 0:
        return "", ""

    # 找最后一个连续非空块 [block_start, end]
    block_start = end
    while block_start >= 0 and lines[block_start].strip() != "":
        block_start -= 1
    block_start += 1

    # 如果整个 detailed 都是一个连续非空块，则不剥离 Note
    if block_start == 0:
        main_text = "\n".join(lines[:end + 1])
        return main_text, ""

    last_block_lines = lines[block_start:end + 1]

    # 若最后块内部含有编号步骤起始行，则它属于第八块
    if any(NUMBERED_STEP_RE.match(line) for line in last_block_lines):
        main_text = "\n".join(lines[:end + 1])
        return main_text, ""

    # 否则，最后块剥离为 Note
    note_text = "\n".join(last_block_lines)
    main_text = "\n".join(lines[:block_start - 1])  # block_start-1 是分隔空行

    return main_text, note_text


def parse_one_explain_file(txt_path: Path):
    """
    处理单个 explain 文件：
    1. 先切分出 8 个块
    2. 对第 8 块做第 9 块 Note 的剥离
    3. 对这 9 块内容统一做空行剔除
    返回：
    {
        'ProblemInterface': ...,
        ...
        'EdgeCasesAndConsistencyChecks': ...,
        'Note': ...
    }
    """
    raw = txt_path.read_text(encoding="utf-8")

    parsed8 = split_into_8_sections(raw)

    detailed_main, note_text = extract_note_from_section8(parsed8["EdgeCasesAndConsistencyChecks"])
    parsed8["EdgeCasesAndConsistencyChecks"] = detailed_main

    parsed9 = dict(parsed8)
    parsed9["Note"] = note_text

    # 最后统一对 9 块做空行剔除
    for key in parsed9:
        parsed9[key] = remove_blank_lines(parsed9[key])

    return parsed9


def parse_question_dir(question_dir: Path):
    """
    对单个题目目录处理。
    返回：
    {
        'ProblemSummary': [file1内容, file2内容, ...],
        ...
        'DetailedAlgorithmSteps': [...],
        'Note': [...]
    }
    """
    explain_dir = question_dir / "LLM Explains"
    if not explain_dir.exists() or not explain_dir.is_dir():
        raise FileNotFoundError(f"{question_dir} 下不存在 'LLM Explains' 文件夹")

    txt_files = list_explain_txts(explain_dir)

    result = {v: [] for v in SECTION_VARS.values()}
    result["Note"] = []

    for txt_path in txt_files:
        parsed = parse_one_explain_file(txt_path)
        for key in result:
            result[key].append(parsed[key])

    return result

In [4]:
# 遍历所有题目
dirs = list_question_dirs(QUESTIONS_DIR)
all_results = {}

for d in dirs:
    try:
        all_results[d.name] = parse_question_dir(d)
        print(f"done: {d.name}")
    except Exception as e:
        print(f"error: {d.name} -> {e}")

if all_results:
    first_name = next(iter(all_results))
    print(f"\n示例题目: {first_name}")
    pprint(all_results[first_name])

done: Easy B3666
done: Easy P15288
done: Easy P15457
done: Easy P4306
done: Easy P7714
done: Hard P11658
done: Hard P11823
done: Hard P13901
done: Hard P15082
done: Hard P6845
done: ML Q1
done: ML Q2
done: ML Q3
done: Mid P1407
done: Mid P14989
done: Mid P3007
done: Mid P3167
done: Mid P4092

示例题目: Easy B3666
{'EdgeCasesAndConsistencyChecks': ['- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '

In [4]:
# 单独测试
dirs = list_question_dirs(QUESTIONS_DIR)
all_results = {}

d = dirs[0]
try:
    all_results[d.name] = parse_question_dir(d)
    print(f"done: {d.name}")
except Exception as e:
    print(f"error: {d.name} -> {e}")

if all_results:
    first_name = next(iter(all_results))
    print(f"\n示例题目: {first_name}")
    pprint(all_results[first_name])

[(1, PosixPath('Questions/Easy B3666/LLM Explains/1 0.0.txt')),
 (2, PosixPath('Questions/Easy B3666/LLM Explains/2 0.0.txt')),
 (3, PosixPath('Questions/Easy B3666/LLM Explains/3 0.0.txt')),
 (4, PosixPath('Questions/Easy B3666/LLM Explains/4 0.0.txt')),
 (5, PosixPath('Questions/Easy B3666/LLM Explains/5 0.0.txt')),
 (6, PosixPath('Questions/Easy B3666/LLM Explains/6 0.0.txt')),
 (7, PosixPath('Questions/Easy B3666/LLM Explains/7 0.0.txt')),
 (8, PosixPath('Questions/Easy B3666/LLM Explains/8 0.0.txt')),
 (9, PosixPath('Questions/Easy B3666/LLM Explains/9 0.0.txt')),
 (10, PosixPath('Questions/Easy B3666/LLM Explains/10 0.0.txt')),
 (11, PosixPath('Questions/Easy B3666/LLM Explains/11 0.0.txt')),
 (12, PosixPath('Questions/Easy B3666/LLM Explains/12 0.0.txt')),
 (13, PosixPath('Questions/Easy B3666/LLM Explains/13 0.0.txt')),
 (14, PosixPath('Questions/Easy B3666/LLM Explains/14 0.0.txt')),
 (15, PosixPath('Questions/Easy B3666/LLM Explains/15 0.0.txt')),
 (16, PosixPath('Questions/Easy B3666/LLM Explains/16 0.0.txt')),
 (17, PosixPath('Questions/Easy B3666/LLM Explains/17 0.0.txt')),
 (18, PosixPath('Questions/Easy B3666/LLM Explains/18 0.0.txt')),
 (19, PosixPath('Questions/Easy B3666/LLM Explains/19 0.0.txt')),
 (20, PosixPath('Questions/Easy B3666/LLM Explains/20 0.0.txt')),
 (21, PosixPath('Questions/Easy B3666/LLM Explains/21 0.2.txt')),
 (22, PosixPath('Questions/Easy B3666/LLM Explains/22 0.2.txt')),
 (23, PosixPath('Questions/Easy B3666/LLM Explains/23 0.2.txt')),
 (24, PosixPath('Questions/Easy B3666/LLM Explains/24 0.2.txt')),
 (25, PosixPath('Questions/Easy B3666/LLM Explains/25 0.2.txt')),
 (26, PosixPath('Questions/Easy B3666/LLM Explains/26 0.2.txt')),
 (27, PosixPath('Questions/Easy B3666/LLM Explains/27 0.2.txt')),
 (28, PosixPath('Questions/Easy B3666/LLM Explains/28 0.2.txt')),
 (29, PosixPath('Questions/Easy B3666/LLM Explains/29 0.2.txt')),
 (30, PosixPath('Questions/Easy B3666/LLM Explains/30 0.2.txt')),
 (31, PosixPath('Questions/Easy B3666/LLM Explains/31 0.2.txt')),
 (32, PosixPath('Questions/Easy B3666/LLM Explains/32 0.2.txt')),
 (33, PosixPath('Questions/Easy B3666/LLM Explains/33 0.2.txt')),
 (34, PosixPath('Questions/Easy B3666/LLM Explains/34 0.2.txt')),
 (35, PosixPath('Questions/Easy B3666/LLM Explains/35 0.2.txt')),
 (36, PosixPath('Questions/Easy B3666/LLM Explains/36 0.2.txt')),
 (37, PosixPath('Questions/Easy B3666/LLM Explains/37 0.2.txt')),
 (38, PosixPath('Questions/Easy B3666/LLM Explains/38 0.2.txt')),
 (39, PosixPath('Questions/Easy B3666/LLM Explains/39 0.2.txt')),
 (40, PosixPath('Questions/Easy B3666/LLM Explains/40 0.2.txt')),
 (41, PosixPath('Questions/Easy B3666/LLM Explains/41 0.5.txt')),
 (42, PosixPath('Questions/Easy B3666/LLM Explains/42 0.5.txt')),
 (43, PosixPath('Questions/Easy B3666/LLM Explains/43 0.5.txt')),
 (44, PosixPath('Questions/Easy B3666/LLM Explains/44 0.5.txt')),
 (45, PosixPath('Questions/Easy B3666/LLM Explains/45 0.5.txt')),
 (46, PosixPath('Questions/Easy B3666/LLM Explains/46 0.5.txt')),
 (47, PosixPath('Questions/Easy B3666/LLM Explains/47 0.5.txt')),
 (48, PosixPath('Questions/Easy B3666/LLM Explains/48 0.5.txt')),
 (49, PosixPath('Questions/Easy B3666/LLM Explains/49 0.5.txt')),
 (50, PosixPath('Questions/Easy B3666/LLM Explains/50 0.5.txt')),
 (51, PosixPath('Questions/Easy B3666/LLM Explains/51 0.5.txt')),
 (52, PosixPath('Questions/Easy B3666/LLM Explains/52 0.5.txt')),
 (53, PosixPath('Questions/Easy B3666/LLM Explains/53 0.5.txt')),
 (54, PosixPath('Questions/Easy B3666/LLM Explains/54 0.5.txt')),
 (55, PosixPath('Questions/Easy B3666/LLM Explains/55 0.5.txt')),
 (56, PosixPath('Questions/Easy B3666/LLM Explains/56 0.5.txt')),
 (57, PosixPath('Questions/Easy B3666/LLM Explains/57 0.5.txt')),
 (58, PosixPath('Questions/Easy B3666/LLM Explains/58 0.5.txt')),
 (59, PosixPath('Questions/Easy B3666/LLM Explains/59 0.5.txt')),
 (60, PosixPath('Questions/Easy B3666/LLM Explains/60 0.5.txt')),
 (61, PosixPath('Questions/Easy B3666/LLM Explains/61 0.8.txt')),
 (62, PosixPath('Questions/Easy B3666/LLM Explains/62 0.8.txt')),
 (63, PosixPath('Questions/Easy B3666/LLM Explains/63 0.8.txt')),
 (64, PosixPath('Questions/Easy B3666/LLM Explains/64 0.8.txt')),
 (65, PosixPath('Questions/Easy B3666/LLM Explains/65 0.8.txt')),
 (66, PosixPath('Questions/Easy B3666/LLM Explains/66 0.8.txt')),
 (67, PosixPath('Questions/Easy B3666/LLM Explains/67 0.8.txt')),
 (68, PosixPath('Questions/Easy B3666/LLM Explains/68 0.8.txt')),
 (69, PosixPath('Questions/Easy B3666/LLM Explains/69 0.8.txt')),
 (70, PosixPath('Questions/Easy B3666/LLM Explains/70 0.8.txt')),
 (71, PosixPath('Questions/Easy B3666/LLM Explains/71 0.8.txt')),
 (72, PosixPath('Questions/Easy B3666/LLM Explains/72 0.8.txt')),
 (73, PosixPath('Questions/Easy B3666/LLM Explains/73 0.8.txt')),
 (74, PosixPath('Questions/Easy B3666/LLM Explains/74 0.8.txt')),
 (75, PosixPath('Questions/Easy B3666/LLM Explains/75 0.8.txt')),
 (76, PosixPath('Questions/Easy B3666/LLM Explains/76 0.8.txt')),
 (77, PosixPath('Questions/Easy B3666/LLM Explains/77 0.8.txt')),
 (78, PosixPath('Questions/Easy B3666/LLM Explains/78 0.8.txt')),
 (79, PosixPath('Questions/Easy B3666/LLM Explains/79 0.8.txt')),
 (80, PosixPath('Questions/Easy B3666/LLM Explains/80 0.8.txt'))]

done: Easy B3666

示例题目: Easy B3666
{'EdgeCasesAndConsistencyChecks': ['- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '

In [5]:
display(len(all_results))
display(len(all_results["Easy B3666"]))
display(len(all_results["Easy B3666"]["EdgeCasesAndConsistencyChecks"]))
display(all_results["Easy B3666"]["EdgeCasesAndConsistencyChecks"][0])
display(type(all_results))

18

9

80

'- **Empty stack handling**: When `stack` is empty before step 2 (only at `k=1`), the while loop is skipped, `k=1` is pushed, and `ans = 0 XOR 1 = 1`, matching sample output first line.\n- **Equality case**: The condition `a[stack.top()] ≤ x[k]` uses non-strict inequality (`≤`), so equal values cause the old index to be popped. This is correct because the definition requires `a_i > a_j` for all `j > i`; if `a_i = a_j`, then `i` is not a suffix maximum.\n- **Single element**: For `k=1`, `S_1 = {1}`, so `ans = 1`.\n- **Strictly decreasing input**: If `x[1] > x[2] > ... > x[n]`, then `stack = [1, 2, ..., k]` after `k` operations, and `ans = 1 XOR 2 XOR ... XOR k`.\n- **Strictly increasing input**: If `x[1] < x[2] < ... < x[n]`, then after `k` operations, `stack = [k]`, so `ans = k`.\n- **Parsing-unit consistency**: The input must be parsed as one fixed-length block of `n` integers on the second line; interpreting it as `n` separate scalar reads per line (e.g., one integer per line) would be incorrect.\n- **Indexing convention**: All indices stored in `stack` and used in `ans` are 1-based, matching the problem statement. No conversion to 0-based indexing is performed at any stage.\n- **Wrong interpretations to avoid**:\n  - Using `≥` instead of `>` in the suffix maximum condition would incorrectly include equal values.\n  - Using `a[stack.top()] < x[k]` (strict) in the while condition would fail to pop equal values, violating the `>` requirement.\n  - Storing values instead of indices in the stack would lose position information needed for XOR.\n  - Outputting the XOR of values instead of indices would be incorrect.\n  - Using 0-based indexing internally and converting at output would introduce off-by-one errors.'

dict

In [6]:
def build_similarity_matrix(
    text_list,
    batch_size=64,
    show_pair_progress=False,
    matrix_label="",
    matrix_pos=None,
    matrix_total=None
):
    n = len(text_list)
    mat = np.zeros((n, n), dtype=float)

    # 对角线 = 1
    np.fill_diagonal(mat, 1.0)

    # 上三角 pair
    pairs = []
    index_pairs = []
    for i in range(n):
        for j in range(i + 1, n):
            pairs.append((text_list[i], text_list[j]))
            index_pairs.append((i, j))

    total_pairs = len(pairs)

    if pairs:
        all_scores = []

        pair_pbar = None
        if show_pair_progress:
            desc = matrix_label if matrix_label else "pair progress"
            if matrix_pos is not None and matrix_total is not None:
                desc = f"[matrix {matrix_pos}/{matrix_total}] {desc}"
            pair_pbar = tqdm(total=total_pairs, desc=desc, leave=False)

        for start in range(0, total_pairs, batch_size):
            end = min(start + batch_size, total_pairs)
            batch_pairs = pairs[start:end]
            batch_scores = model.predict(batch_pairs)
            all_scores.extend(batch_scores)

            if pair_pbar is not None:
                pair_pbar.update(end - start)

        if pair_pbar is not None:
            pair_pbar.close()

        for (i, j), score in zip(index_pairs, all_scores):
            mat[i, j] = score
            mat[j, i] = score

    return mat

In [7]:
# ===== 主处理 =====

all_matrices = {}  # 每个题目对应9个矩阵

question_names = list(all_results.keys())
num_questions = len(question_names)
num_matrices = len(MAT_NAMES)
total_matrix_jobs = num_questions * num_matrices

overall_pbar = tqdm(total=total_matrix_jobs, desc="All matrices", position=0)

for q_idx, qname in enumerate(tqdm(question_names, desc="Questions", position=1), start=1):
    qdata = all_results[qname]
    mats = {}

    per_question_pbar = tqdm(
        total=num_matrices,
        desc=f"Question {q_idx}/{num_questions}: {qname}",
        position=2,
        leave=False
    )

    for mat_idx, (key, mat_name) in enumerate(zip(KEY_ORDER, MAT_NAMES), start=1):
        texts = qdata[key]

        per_question_pbar.set_postfix_str(f"{mat_idx}/{num_matrices} -> {mat_name}")
        overall_pbar.set_postfix_str(f"{qname} | {mat_name}")

        mat = build_similarity_matrix(
            texts,
            batch_size=64,
            show_pair_progress=True,
            matrix_label=f"{qname} | {mat_name}",
            matrix_pos=mat_idx,
            matrix_total=num_matrices
        )
        mats[mat_name] = mat

        per_question_pbar.update(1)
        overall_pbar.update(1)

    per_question_pbar.close()
    all_matrices[qname] = mats

overall_pbar.close()

All matrices:   0%|          | 0/162 [00:00<?, ?it/s]

Questions:   0%|          | 0/18 [00:00<?, ?it/s]

Question 1/18: Easy B3666:   0%|          | 0/9 [00:00<?, ?it/s]

[matrix 1/9] Easy B3666 | mat1PI:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 2/9] Easy B3666 | mat2FD:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 3/9] Easy B3666 | mat3RC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 4/9] Easy B3666 | mat4MS:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 5/9] Easy B3666 | mat5INV:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 6/9] Easy B3666 | mat6POUR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 7/9] Easy B3666 | mat7OR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 8/9] Easy B3666 | mat8ECCC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 9/9] Easy B3666 | mat9N:   0%|          | 0/3160 [00:00<?, ?it/s]

Question 2/18: Easy P15288:   0%|          | 0/9 [00:00<?, ?it/s]

[matrix 1/9] Easy P15288 | mat1PI:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 2/9] Easy P15288 | mat2FD:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 3/9] Easy P15288 | mat3RC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 4/9] Easy P15288 | mat4MS:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 5/9] Easy P15288 | mat5INV:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 6/9] Easy P15288 | mat6POUR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 7/9] Easy P15288 | mat7OR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 8/9] Easy P15288 | mat8ECCC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 9/9] Easy P15288 | mat9N:   0%|          | 0/3160 [00:00<?, ?it/s]

Question 3/18: Easy P15457:   0%|          | 0/9 [00:00<?, ?it/s]

[matrix 1/9] Easy P15457 | mat1PI:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 2/9] Easy P15457 | mat2FD:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 7/9] Easy P15457 | mat7OR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 8/9] Easy P15457 | mat8ECCC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 9/9] Easy P15457 | mat9N:   0%|          | 0/3160 [00:00<?, ?it/s]

Question 4/18: Easy P4306:   0%|          | 0/9 [00:00<?, ?it/s]

[matrix 1/9] Easy P4306 | mat1PI:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 2/9] Easy P4306 | mat2FD:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 3/9] Easy P4306 | mat3RC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 4/9] Easy P4306 | mat4MS:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 5/9] Easy P4306 | mat5INV:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 6/9] Easy P4306 | mat6POUR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 7/9] Easy P4306 | mat7OR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 8/9] Easy P4306 | mat8ECCC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 9/9] Easy P4306 | mat9N:   0%|          | 0/3160 [00:00<?, ?it/s]

Question 5/18: Easy P7714:   0%|          | 0/9 [00:00<?, ?it/s]

[matrix 1/9] Easy P7714 | mat1PI:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 2/9] Easy P7714 | mat2FD:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 3/9] Easy P7714 | mat3RC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 4/9] Easy P7714 | mat4MS:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 5/9] Easy P7714 | mat5INV:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 6/9] Easy P7714 | mat6POUR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 7/9] Easy P7714 | mat7OR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 8/9] Easy P7714 | mat8ECCC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 9/9] Easy P7714 | mat9N:   0%|          | 0/3160 [00:00<?, ?it/s]

Question 6/18: Hard P11658:   0%|          | 0/9 [00:00<?, ?it/s]

Question 7/18: Hard P11823:   0%|          | 0/9 [00:00<?, ?it/s]

Question 8/18: Hard P13901:   0%|          | 0/9 [00:00<?, ?it/s]

Question 9/18: Hard P15082:   0%|          | 0/9 [00:00<?, ?it/s]

Question 10/18: Hard P6845:   0%|          | 0/9 [00:00<?, ?it/s]

Question 11/18: ML Q1:   0%|          | 0/9 [00:00<?, ?it/s]

Question 12/18: ML Q2:   0%|          | 0/9 [00:00<?, ?it/s]

Question 13/18: ML Q3:   0%|          | 0/9 [00:00<?, ?it/s]

Question 14/18: Mid P1407:   0%|          | 0/9 [00:00<?, ?it/s]

Question 15/18: Mid P14989:   0%|          | 0/9 [00:00<?, ?it/s]

Question 16/18: Mid P3007:   0%|          | 0/9 [00:00<?, ?it/s]

Question 17/18: Mid P3167:   0%|          | 0/9 [00:00<?, ?it/s]

Question 18/18: Mid P4092:   0%|          | 0/9 [00:00<?, ?it/s]

In [8]:
# all_matrices打印辅助函数
def get_question_names_from_all_matrices(all_matrices):
    return list(all_matrices.keys())

def get_question_name_by_index(all_matrices, q_index):
    qnames = get_question_names_from_all_matrices(all_matrices)
    if not (0 <= q_index < len(qnames)):
        raise IndexError(f"q_index={q_index} 越界，当前题目总数为 {len(qnames)}")
    return qnames[q_index]

def print_question_matrices(all_matrices, q_index, selected_mats=None, round_digits=6):
    qname = get_question_name_by_index(all_matrices, q_index)
    mats = all_matrices[qname]

    mat_names = selected_mats if selected_mats is not None else list(mats.keys())

    print(f"题目 index = {q_index}")
    print(f"题目名称 = {qname}")

    for mat_name in mat_names:
        print(f"\n===== {mat_name} =====")
        mat = mats[mat_name]
        print(f"shape = {mat.shape}")
        display(pd.DataFrame(mat).round(round_digits))

In [10]:
# =============================
# 三种分析方法：辅助函数
# =============================

import numpy as np
import pandas as pd

def check_matrix_and_build_groups(mat, k, temperature_list):
    n = mat.shape[0]
    expected_n = k * len(temperature_list)

    if mat.shape[0] != mat.shape[1]:
        raise ValueError(f"矩阵不是方阵，shape={mat.shape}")

    if n != expected_n:
        raise ValueError(
            f"矩阵大小与参数不匹配：matrix_n={n}, "
            f"但 k * len(temperature_list) = {k} * {len(temperature_list)} = {expected_n}"
        )

    # 顺序约定：
    # [0:k) -> temperature_list[0]
    # [k:2k) -> temperature_list[1]
    # ...
    temp_to_indices = {}
    for ti, temp in enumerate(temperature_list):
        start = ti * k
        end = start + k
        temp_to_indices[temp] = list(range(start, end))

    return temp_to_indices


def get_offdiag_values(mat):
    n = mat.shape[0]
    mask = ~np.eye(n, dtype=bool)
    return mat[mask]


def get_upper_triangle_values(submat):
    n = submat.shape[0]
    vals = []
    for i in range(n):
        for j in range(i + 1, n):
            vals.append(submat[i, j])
    return np.array(vals, dtype=float)


# -----------------------------
# 方法1：整体稳定性
# -----------------------------
def method1_global_stats(mat):
    vals = get_offdiag_values(mat)

    return {
        "offdiag_mean": float(np.mean(vals)),
        "offdiag_std": float(np.std(vals)),
        "offdiag_min": float(np.min(vals)),
        "offdiag_max": float(np.max(vals)),
    }


# -----------------------------
# 方法2：温度内 / 温度间分解
# -----------------------------
def method2_temperature_decomposition(mat, k, temperature_list):
    temp_to_indices = check_matrix_and_build_groups(mat, k, temperature_list)

    # 1) 每个温度内部（within-temp）
    within_rows = []
    within_all_vals = []

    for temp in temperature_list:
        idxs = temp_to_indices[temp]
        submat = mat[np.ix_(idxs, idxs)]
        vals = get_upper_triangle_values(submat)

        within_rows.append({
            "temperature": temp,
            "sample_indices": idxs,
            "within_mean": float(np.mean(vals)) if len(vals) > 0 else np.nan,
            "within_std": float(np.std(vals)) if len(vals) > 0 else np.nan,
            "within_min": float(np.min(vals)) if len(vals) > 0 else np.nan,
            "within_max": float(np.max(vals)) if len(vals) > 0 else np.nan,
        })

        within_all_vals.extend(vals.tolist())

    within_df = pd.DataFrame(within_rows)

    # 2) 不同温度之间（cross-temp）
    cross_mean = pd.DataFrame(index=temperature_list, columns=temperature_list, dtype=float)
    cross_std = pd.DataFrame(index=temperature_list, columns=temperature_list, dtype=float)

    cross_all_vals = []

    for i, temp_i in enumerate(temperature_list):
        idx_i = temp_to_indices[temp_i]

        for j, temp_j in enumerate(temperature_list):
            idx_j = temp_to_indices[temp_j]

            if i == j:
                cross_mean.loc[temp_i, temp_j] = np.nan
                cross_std.loc[temp_i, temp_j] = np.nan
                continue

            vals = []
            for a in idx_i:
                for b in idx_j:
                    vals.append(mat[a, b])

            vals = np.array(vals, dtype=float)
            cross_mean.loc[temp_i, temp_j] = float(np.mean(vals))
            cross_std.loc[temp_i, temp_j] = float(np.std(vals))

            # 只累计上三角温度对，避免重复
            if i < j:
                cross_all_vals.extend(vals.tolist())

    overall_within_mean = float(np.mean(within_all_vals)) if len(within_all_vals) > 0 else np.nan
    overall_cross_mean = float(np.mean(cross_all_vals)) if len(cross_all_vals) > 0 else np.nan

    summary = {
        "overall_within_mean": overall_within_mean,
        "overall_cross_mean": overall_cross_mean,
        "within_minus_cross": (
            overall_within_mean - overall_cross_mean
            if (not np.isnan(overall_within_mean) and not np.isnan(overall_cross_mean))
            else np.nan
        )
    }

    return {
        "within_df": within_df,
        "cross_mean_df": cross_mean,
        "cross_std_df": cross_std,
        "summary": summary,
    }


# -----------------------------
# 方法3：原型 / 离群分析
# -----------------------------
def method3_prototype_outlier(mat, k=None, temperature_list=None):
    n = mat.shape[0]

    row_mean_offdiag = (np.sum(mat, axis=1) - np.diag(mat)) / (n - 1)

    df = pd.DataFrame({
        "sample_index": np.arange(n),
        "row_mean_offdiag": row_mean_offdiag,
    })

    if k is not None and temperature_list is not None:
        expected_n = k * len(temperature_list)
        if expected_n == n:
            df["temperature"] = [temperature_list[i // k] for i in range(n)]
            df["local_index_in_temp"] = [i % k for i in range(n)]

    prototype_idx = int(np.argmax(row_mean_offdiag))
    outlier_idx = int(np.argmin(row_mean_offdiag))

    df = df.sort_values("row_mean_offdiag", ascending=False).reset_index(drop=True)

    return {
        "row_mean_df": df,
        "prototype_idx": prototype_idx,
        "prototype_score": float(row_mean_offdiag[prototype_idx]),
        "outlier_idx": outlier_idx,
        "outlier_score": float(row_mean_offdiag[outlier_idx]),
    }


# -----------------------------
# 汇总：单个矩阵三种分析
# -----------------------------
def analyze_one_matrix(mat, k, temperature_list):
    m1 = method1_global_stats(mat)
    m2 = method2_temperature_decomposition(mat, k, temperature_list)
    m3 = method3_prototype_outlier(mat, k=k, temperature_list=temperature_list)

    overview = {
        **m1,
        **m2["summary"],
        "prototype_idx": m3["prototype_idx"],
        "prototype_score": m3["prototype_score"],
        "outlier_idx": m3["outlier_idx"],
        "outlier_score": m3["outlier_score"],
    }

    return {
        "overview": overview,
        "method1": m1,
        "method2": m2,
        "method3": m3,
    }

In [11]:
# =============================
# 对指定题目的所有矩阵做分析（中文版）
# =============================

def analyze_question_matrices(all_matrices, q_index, k, temperature_list, selected_mats=None, round_digits=6):
    qname = get_question_name_by_index(all_matrices, q_index)
    mats = all_matrices[qname]

    mat_names = selected_mats if selected_mats is not None else list(mats.keys())

    print(f"题目 index = {q_index}")
    print(f"题目名称 = {qname}")
    print(f"k = {k}")
    print(f"temperature_list = {temperature_list}")

    overview_rows = []
    stat_results = {}

    for mat_name in mat_names:
        mat = mats[mat_name]
        result = analyze_one_matrix(mat, k, temperature_list)
        stat_results[mat_name] = result

        overview_row = {"matrix": mat_name}
        overview_row.update(result["overview"])
        overview_rows.append(overview_row)

    overview_df = pd.DataFrame(overview_rows)
    print("\n===== 总览表 =====")
    display(overview_df.round(round_digits))

    for mat_name in mat_names:
        result = stat_results[mat_name]

        print(f"\n\n==============================")
        print(f"矩阵: {mat_name}")
        print(f"==============================")

        print("\n[方法1] 整体稳定性（非对角元素统计）")
        display(pd.DataFrame([result["method1"]]).round(round_digits))

        print("\n[方法2-A] 温度内稳定性")
        display(result["method2"]["within_df"].round(round_digits))

        print("\n[方法2-B] 温度间均值矩阵")
        display(result["method2"]["cross_mean_df"].round(round_digits))

        print("\n[方法2-C] 温度间标准差矩阵")
        display(result["method2"]["cross_std_df"].round(round_digits))

        print("\n[方法2-D] 温度分解汇总")
        display(pd.DataFrame([result["method2"]["summary"]]).round(round_digits))

        print("\n[方法3] 原型 / 离群分析（按 row mean offdiag 排序）")
        display(result["method3"]["row_mean_df"].round(round_digits))

        print(
            f"prototype_idx = {result['method3']['prototype_idx']}, "
            f"prototype_score = {result['method3']['prototype_score']:.{round_digits}f}"
        )
        print(
            f"outlier_idx = {result['method3']['outlier_idx']}, "
            f"outlier_score = {result['method3']['outlier_score']:.{round_digits}f}"
        )

    return overview_df, stat_results

题目 index = 0
题目名称 = Easy B3666
k = 20
temperature_list = [0.2, 0.5, 0.8, 1.0]

===== 总览表 =====

,matrix,offdiag_mean,offdiag_std,offdiag_min,offdiag_max,overall_within_mean,overall_cross_mean,within_minus_cross,prototype_idx,prototype_score,outlier_idx,outlier_score
0,mat1PI,0.757690,0.058490,0.600664,0.932416,0.793663,0.746298,0.047366,0,0.790566,73,0.678953
1,mat2FD,0.737014,0.080047,0.513030,0.937798,0.759622,0.729855,0.029767,0,0.803925,39,0.625806
2,mat3RC,0.635470,0.105595,0.399533,0.962741,0.701351,0.614607,0.086744,1,0.701264,74,0.493384
3,mat4MS,0.708719,0.068221,0.537351,0.909813,0.735524,0.700230,0.035294,0,0.765795,64,0.623357
4,mat5INV,0.692119,0.088029,0.496809,0.955818,0.729639,0.680237,0.049402,0,0.770258,65,0.587802
5,mat6POUR,0.661442,0.068497,0.527780,0.895031,0.714744,0.644563,0.070181,0,0.699297,55,0.602677
6,mat7OR,0.708271,0.083142,0.524267,0.969586,0.766809,0.689734,0.077075,63,0.762219,48,0.631991
7,mat8ECCC,0.575143,0.064746,0.436574,0.800816,0.613537,0.562986,0.050551,51,0.663793,76,0.514582
8,mat9N,0.543311,0.245823,0.009193,0.972853,0.618194,0.519598,0.098595,50,0.648622,63,0.254095

==============================
矩阵: mat1PI
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0       0.75769      0.05849     0.600664     0.932416

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.932416,0.000000,0.932416,0.932416
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.744845,0.041015,0.626614,0.836562
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.765159,0.034365,0.677684,0.861726
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.732234,0.041479,0.626976,0.838072

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.741639  0.753305  0.741997
0.5  0.741639       NaN  0.754462  0.739328
0.8  0.753305  0.754462       NaN  0.747056
1.0  0.741997  0.739328  0.747056       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.036951  0.025817  0.037703
0.5  0.036951       NaN  0.042067  0.043878
0.8  0.025817  0.042067       NaN  0.042467
1.0  0.037703  0.043878  0.042467       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.793663            0.746298            0.047366

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.790566          0.2                    0
1              1          0.790566          0.2                    1
2              2          0.790566          0.2                    2
3              3          0.790566          0.2                    3
4              4          0.790566          0.2                    4
..           ...               ...          ...                  ...
75            34          0.712861          0.5                   14
76            77          0.705279          1.0                   17
77            31          0.698380          0.5                   11
78            35          0.685445          0.5                   15
79            73          0.678953          1.0                   13

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.790566
outlier_idx = 73, outlier_score = 0.678953


==============================
矩阵: mat2FD
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.737014     0.080047      0.51303     0.937798

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.937798,0.000000,0.937798,0.937798
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.721624,0.071207,0.538051,0.908299
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.688590,0.060843,0.556992,0.836194
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.690475,0.066724,0.538755,0.884157

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.769530  0.755675  0.759390
0.5  0.769530       NaN  0.704156  0.697738
0.8  0.755675  0.704156       NaN  0.692640
1.0  0.759390  0.697738  0.692640       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.042255  0.040341  0.038636
0.5  0.042255       NaN  0.063517  0.063977
0.8  0.040341  0.063517       NaN  0.058337
1.0  0.038636  0.063977  0.058337       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.759622            0.729855            0.029767

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.803925          0.2                    0
1              1          0.803925          0.2                    1
2              2          0.803925          0.2                    2
3              3          0.803925          0.2                    3
4              4          0.803925          0.2                    4
..           ...               ...          ...                  ...
75            63          0.673135          1.0                    3
76            73          0.671813          1.0                   13
77            47          0.651580          0.8                    7
78            64          0.640024          1.0                    4
79            39          0.625806          0.5                   19

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.803925
outlier_idx = 39, outlier_score = 0.625806


==============================
矩阵: mat3RC
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0       0.63547     0.105595     0.399533     0.962741

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.940892,0.000000,0.940892,0.940892
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.650253,0.097021,0.457841,0.962741
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.639859,0.065992,0.460453,0.791716
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.574401,0.071719,0.415741,0.793735

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.651661  0.628881  0.595603
0.5  0.651661       NaN  0.628103  0.582080
0.8  0.628881  0.628103       NaN  0.601314
1.0  0.595603  0.582080  0.601314       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.068780  0.054788  0.060422
0.5  0.068780       NaN  0.078941  0.071208
0.8  0.054788  0.078941       NaN  0.065258
1.0  0.060422  0.071208  0.065258       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.701351            0.614607            0.086744

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              1          0.701264          0.2                    1
1              3          0.701264          0.2                    3
2              5          0.701264          0.2                    5
3              4          0.701264          0.2                    4
4              6          0.701264          0.2                    6
..           ...               ...          ...                  ...
75            39          0.552427          0.5                   19
76            52          0.537984          0.8                   12
77            63          0.532758          1.0                    3
78            70          0.526344          1.0                   10
79            74          0.493384          1.0                   14

[80 rows x 4 columns]

prototype_idx = 1, prototype_score = 0.701264
outlier_idx = 74, outlier_score = 0.493384


==============================
矩阵: mat4MS
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.708719     0.068221     0.537351     0.909813

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.909813,0.00000,0.909813,0.909813
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.702951,0.04384,0.583266,0.861091
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.670813,0.03309,0.580387,0.766525
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.658521,0.04100,0.537351,0.795274

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.737537  0.708217  0.714813
0.5  0.737537       NaN  0.685663  0.685125
0.8  0.708217  0.685663       NaN  0.670028
1.0  0.714813  0.685125  0.670028       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.034432  0.037040  0.046372
0.5  0.034432       NaN  0.043226  0.044411
0.8  0.037040  0.043226       NaN  0.037820
1.0  0.046372  0.044411  0.037820       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.735524             0.70023            0.035294

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.765795          0.2                    0
1              1          0.765795          0.2                    1
2              2          0.765795          0.2                    2
3              3          0.765795          0.2                    3
4              4          0.765795          0.2                    4
..           ...               ...          ...                  ...
75            45          0.654052          0.8                    5
76            42          0.652232          0.8                    2
77            36          0.649760          0.5                   16
78            62          0.638707          1.0                    2
79            64          0.623357          1.0                    4

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.765795
outlier_idx = 64, outlier_score = 0.623357


==============================
矩阵: mat5INV
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.692119     0.088029     0.496809     0.955818

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.955818,0.000000,0.955818,0.955818
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.665990,0.045522,0.551696,0.772613
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.657599,0.051860,0.547843,0.826292
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.639149,0.054044,0.516340,0.767496

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.718904  0.697623  0.717965
0.5  0.718904       NaN  0.652944  0.647029
0.8  0.697623  0.652944       NaN  0.646958
1.0  0.717965  0.647029  0.646958       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.048668  0.046459  0.049345
0.5  0.048668       NaN  0.047963  0.052849
0.8  0.046459  0.047963       NaN  0.056896
1.0  0.049345  0.052849  0.056896       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.729639            0.680237            0.049402

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.770258          0.2                    0
1              1          0.770258          0.2                    1
2              2          0.770258          0.2                    2
3              3          0.770258          0.2                    3
4              4          0.770258          0.2                    4
..           ...               ...          ...                  ...
75            47          0.621634          0.8                    7
76            74          0.619295          1.0                   14
77            53          0.619031          0.8                   13
78            44          0.602445          0.8                    4
79            65          0.587802          1.0                    5

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.770258
outlier_idx = 65, outlier_score = 0.587802


==============================
矩阵: mat6POUR
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.661442     0.068497      0.52778     0.895031

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.895031,0.000000,0.895031,0.895031
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.649531,0.036864,0.528347,0.789864
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.671667,0.048588,0.535501,0.777457
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.642749,0.038784,0.548006,0.796783

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.640356  0.634168  0.637420
0.5  0.640356       NaN  0.651115  0.643529
0.8  0.634168  0.651115       NaN  0.660792
1.0  0.637420  0.643529  0.660792       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.023040  0.020714  0.021192
0.5  0.023040       NaN  0.040915  0.036316
0.8  0.020714  0.040915       NaN  0.042280
1.0  0.021192  0.036316  0.042280       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.714744            0.644563            0.070181

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.699297          0.2                    0
1              1          0.699297          0.2                    1
2              2          0.699297          0.2                    2
3              3          0.699297          0.2                    3
4              4          0.699297          0.2                    4
..           ...               ...          ...                  ...
75            36          0.615018          0.5                   16
76            73          0.612629          1.0                   13
77            34          0.612398          0.5                   14
78            52          0.610927          0.8                   12
79            55          0.602677          0.8                   15

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.699297
outlier_idx = 55, outlier_score = 0.602677


==============================
矩阵: mat7OR
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.708271     0.083142     0.524267     0.969586

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.969586,0.000000,0.969586,0.969586
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.706651,0.050354,0.586890,0.845730
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.686086,0.053115,0.524267,0.845879
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.704915,0.043732,0.588706,0.802643

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.687992  0.665827  0.692657
0.5  0.687992       NaN  0.695153  0.705622
0.8  0.665827  0.695153       NaN  0.691152
1.0  0.692657  0.705622  0.691152       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.043245  0.048917  0.051423
0.5  0.043245       NaN  0.054242  0.053124
0.8  0.048917  0.054242       NaN  0.053664
1.0  0.051423  0.053124  0.053664       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.766809            0.689734            0.077075

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             63          0.762219          1.0                    3
1              0          0.751287          0.2                    0
2              2          0.751287          0.2                    2
3              1          0.751287          0.2                    1
4              4          0.751287          0.2                    4
..           ...               ...          ...                  ...
75            37          0.657465          0.5                   17
76            39          0.647168          0.5                   19
77            42          0.633729          0.8                    2
78            53          0.632715          0.8                   13
79            48          0.631991          0.8                    8

[80 rows x 4 columns]

prototype_idx = 63, prototype_score = 0.762219
outlier_idx = 48, outlier_score = 0.631991


==============================
矩阵: mat8ECCC
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.575143     0.064746     0.436574     0.800816

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.750305,0.000000,0.750305,0.750305
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.576466,0.053445,0.479259,0.738287
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.569159,0.064358,0.460441,0.730253
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.558216,0.049330,0.460952,0.680968

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.563275  0.561626  0.552542
0.5  0.563275       NaN  0.570968  0.565509
0.8  0.561626  0.570968       NaN  0.563994
1.0  0.552542  0.565509  0.563994       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.037397  0.029191  0.036368
0.5  0.037397       NaN  0.056308  0.050690
0.8  0.029191  0.056308       NaN  0.059389
1.0  0.036368  0.050690  0.059389       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.613537            0.562986            0.050551

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             51          0.663793          0.8                   11
1             67          0.632366          1.0                    7
2             26          0.629776          0.5                    6
3             44          0.618505          0.8                    4
4             29          0.615729          0.5                    9
..           ...               ...          ...                  ...
75            73          0.535974          1.0                   13
76            77          0.535952          1.0                   17
77            58          0.534450          0.8                   18
78            22          0.525588          0.5                    2
79            76          0.514582          1.0                   16

[80 rows x 4 columns]

prototype_idx = 51, prototype_score = 0.663793
outlier_idx = 76, outlier_score = 0.514582


==============================
矩阵: mat9N
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.543311     0.245823     0.009193     0.972853

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.972504,0.000000,0.972504,0.972504
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.496382,0.165997,0.010790,0.970563
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.545982,0.182868,0.056459,0.960495
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.457906,0.217075,0.009193,0.933275

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.479001  0.614979  0.513941
0.5  0.479001       NaN  0.506944  0.481869
0.8  0.614979  0.506944       NaN  0.520855
1.0  0.513941  0.481869  0.520855       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.258379  0.258042  0.291102
0.5  0.258379       NaN  0.170306  0.177973
0.8  0.258042  0.170306       NaN  0.198798
1.0  0.291102  0.177973  0.198798       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.618194            0.519598            0.098595

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             50          0.648622          0.8                   10
1              0          0.640962          0.2                    0
2              2          0.640962          0.2                    2
3              1          0.640962          0.2                    1
4              4          0.640962          0.2                    4
..           ...               ...          ...                  ...
75            69          0.335772          1.0                    9
76            74          0.311847          1.0                   14
77            31          0.291657          0.5                   11
78            70          0.285909          1.0                   10
79            63          0.254095          1.0                    3

[80 rows x 4 columns]

prototype_idx = 50, prototype_score = 0.648622
outlier_idx = 63, outlier_score = 0.254095

In [12]:
# =============================
# 对指定题目的所有矩阵做分析（英文版）
# =============================

def analyze_question_matrices(all_matrices, q_index, k, temperature_list, selected_mats=None, round_digits=6):
    qname = get_question_name_by_index(all_matrices, q_index)
    mats = all_matrices[qname]

    mat_names = selected_mats if selected_mats is not None else list(mats.keys())

    print(f"Question index = {q_index}")
    print(f"Question Name = {qname}")
    print(f"k = {k}")
    print(f"temperature_list = {temperature_list}")

    overview_rows = []
    stat_results = {}

    for mat_name in mat_names:
        mat = mats[mat_name]
        result = analyze_one_matrix(mat, k, temperature_list)
        stat_results[mat_name] = result

        overview_row = {"matrix": mat_name}
        overview_row.update(result["overview"])
        overview_rows.append(overview_row)

    overview_df = pd.DataFrame(overview_rows)
    print("\n===== Overview Table =====")
    display(overview_df.round(round_digits))

    for mat_name in mat_names:
        result = stat_results[mat_name]

        print(f"\n\n==============================")
        print(f"Matrix: {mat_name}")
        print(f"==============================")

        print("\n[Method 1] Overall Stability (Off-Diagonal Statistics)")
        display(pd.DataFrame([result["method1"]]).round(round_digits))

        print("\n[Method 2-A] Within-Temperature Stability")
        display(result["method2"]["within_df"].round(round_digits))

        print("\n[Method 2-B] Between-Temperature Mean Matrix")
        display(result["method2"]["cross_mean_df"].round(round_digits))

        print("\n[Method 2-C] Between-Temperature Standard Deviation Matrix")
        display(result["method2"]["cross_std_df"].round(round_digits))

        print("\n[Method 2-D] Summary of Temperature Decomposition")
        display(pd.DataFrame([result["method2"]["summary"]]).round(round_digits))

        print("\n[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)")
        display(result["method3"]["row_mean_df"].round(round_digits))

        print(
            f"prototype_idx = {result['method3']['prototype_idx']}, "
            f"prototype_score = {result['method3']['prototype_score']:.{round_digits}f}"
        )
        print(
            f"outlier_idx = {result['method3']['outlier_idx']}, "
            f"outlier_score = {result['method3']['outlier_score']:.{round_digits}f}"
        )

    return overview_df, stat_results

In [13]:
# =========================================================
# 路径辅助
# =========================================================
def get_question_dir_by_name(question_name, questions_dir=QUESTIONS_DIR):
    qdir = Path(questions_dir) / question_name
    qdir.mkdir(parents=True, exist_ok=True)
    return qdir


def save_df_csv(df, path, round_digits=6):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=True, encoding="utf-8-sig", float_format=f"%.{round_digits}f")


def save_dict_as_one_row_csv(d, path, round_digits=6):
    df = pd.DataFrame([d])
    save_df_csv(df, path, round_digits=round_digits)


# =========================================================
# 1) 单题：打印矩阵 + 保存矩阵
# 保存位置：
#   Questions/<题目名>/CrossEncoder_Results/matrices/
# =========================================================
def print_and_save_question_matrices(
    all_matrices,
    q_index,
    questions_dir=QUESTIONS_DIR,
    selected_mats=None,
    round_digits=6,
    save_npy=True,
    save_csv=True,
):
    qname = get_question_name_by_index(all_matrices, q_index)
    mats = all_matrices[qname]
    mat_names = selected_mats if selected_mats is not None else list(mats.keys())

    qdir = get_question_dir_by_name(qname, questions_dir)
    out_dir = qdir / "CrossEncoder_Results" / "matrices"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*80}")
    print(f"题目 index = {q_index}")
    print(f"题目名称 = {qname}")
    print(f"矩阵保存目录 = {out_dir}")
    print(f"{'='*80}")

    for mat_name in mat_names:
        mat = mats[mat_name]
        df = pd.DataFrame(mat)

        print(f"\n===== {mat_name} =====")
        print(f"shape = {mat.shape}")
        display(df.round(round_digits))

        if save_npy:
            np.save(out_dir / f"{mat_name}.npy", mat)

        if save_csv:
            df.to_csv(
                out_dir / f"{mat_name}.csv",
                index=True,
                encoding="utf-8-sig",
                float_format=f"%.{round_digits}f"
            )


# =========================================================
# 2) 单题：分析矩阵 + 打印分析 + 保存分析
# 保存位置：
#   Questions/<题目名>/CrossEncoder_Results/analysis/
# =========================================================
def analyze_and_save_question_matrices(
    all_matrices,
    q_index,
    k,
    temperature_list,
    questions_dir=QUESTIONS_DIR,
    selected_mats=None,
    round_digits=6,
):
    qname = get_question_name_by_index(all_matrices, q_index)
    mats = all_matrices[qname]
    mat_names = selected_mats if selected_mats is not None else list(mats.keys())

    qdir = get_question_dir_by_name(qname, questions_dir)
    out_dir = qdir / "CrossEncoder_Results" / "analysis"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*80}")
    print(f"Question index = {q_index}")
    print(f"Question Name = {qname}")
    print(f"k = {k}")
    print(f"temperature_list = {temperature_list}")
    print(f"analysis save dir = {out_dir}")
    print(f"{'='*80}")

    overview_rows = []
    stat_results = {}

    for mat_name in mat_names:
        mat = mats[mat_name]
        result = analyze_one_matrix(mat, k, temperature_list)
        stat_results[mat_name] = result

        overview_row = {"matrix": mat_name}
        overview_row.update(result["overview"])
        overview_rows.append(overview_row)

    overview_df = pd.DataFrame(overview_rows)

    print("\n===== Overview Table =====")
    display(overview_df.round(round_digits))

    # 保存 overview
    save_df_csv(overview_df, out_dir / "overview.csv", round_digits=round_digits)

    # 每个矩阵单独保存
    for mat_name in mat_names:
        result = stat_results[mat_name]
        mat_dir = out_dir / mat_name
        mat_dir.mkdir(parents=True, exist_ok=True)

        print(f"\n\n==============================")
        print(f"Matrix: {mat_name}")
        print(f"==============================")

        print("\n[Method 1] Overall Stability (Off-Diagonal Statistics)")
        method1_df = pd.DataFrame([result["method1"]])
        display(method1_df.round(round_digits))

        print("\n[Method 2-A] Within-Temperature Stability")
        within_df = result["method2"]["within_df"]
        display(within_df.round(round_digits))

        print("\n[Method 2-B] Between-Temperature Mean Matrix")
        cross_mean_df = result["method2"]["cross_mean_df"]
        display(cross_mean_df.round(round_digits))

        print("\n[Method 2-C] Between-Temperature Standard Deviation Matrix")
        cross_std_df = result["method2"]["cross_std_df"]
        display(cross_std_df.round(round_digits))

        print("\n[Method 2-D] Summary of Temperature Decomposition")
        method2_summary_df = pd.DataFrame([result["method2"]["summary"]])
        display(method2_summary_df.round(round_digits))

        print("\n[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)")
        row_mean_df = result["method3"]["row_mean_df"]
        display(row_mean_df.round(round_digits))

        print(
            f"prototype_idx = {result['method3']['prototype_idx']}, "
            f"prototype_score = {result['method3']['prototype_score']:.{round_digits}f}"
        )
        print(
            f"outlier_idx = {result['method3']['outlier_idx']}, "
            f"outlier_score = {result['method3']['outlier_score']:.{round_digits}f}"
        )

        # 保存各表
        save_df_csv(method1_df, mat_dir / "method1_global_stats.csv", round_digits=round_digits)
        save_df_csv(within_df, mat_dir / "method2_within_temperature.csv", round_digits=round_digits)
        save_df_csv(cross_mean_df, mat_dir / "method2_cross_mean.csv", round_digits=round_digits)
        save_df_csv(cross_std_df, mat_dir / "method2_cross_std.csv", round_digits=round_digits)
        save_df_csv(method2_summary_df, mat_dir / "method2_summary.csv", round_digits=round_digits)
        save_df_csv(row_mean_df, mat_dir / "method3_row_mean_offdiag.csv", round_digits=round_digits)

        # 额外保存一个简短文本摘要
        summary_txt = []
        summary_txt.append(f"Question Name: {qname}")
        summary_txt.append(f"Matrix: {mat_name}")
        summary_txt.append("")
        summary_txt.append("[Method 1] Overall Stability")
        for k1, v1 in result["method1"].items():
            summary_txt.append(f"{k1}: {v1:.{round_digits}f}")
        summary_txt.append("")
        summary_txt.append("[Method 2] Temperature Decomposition Summary")
        for k2, v2 in result["method2"]["summary"].items():
            if isinstance(v2, (int, float, np.floating)):
                summary_txt.append(f"{k2}: {v2:.{round_digits}f}")
            else:
                summary_txt.append(f"{k2}: {v2}")
        summary_txt.append("")
        summary_txt.append("[Method 3] Prototype / Outlier")
        summary_txt.append(
            f"prototype_idx: {result['method3']['prototype_idx']}, "
            f"prototype_score: {result['method3']['prototype_score']:.{round_digits}f}"
        )
        summary_txt.append(
            f"outlier_idx: {result['method3']['outlier_idx']}, "
            f"outlier_score: {result['method3']['outlier_score']:.{round_digits}f}"
        )

        (mat_dir / "summary.txt").write_text("\n".join(summary_txt), encoding="utf-8")

    return overview_df, stat_results


# =========================================================
# 3) 所有题目：批量打印 + 保存
# =========================================================
def run_all_questions_print_and_save(
    all_matrices,
    k,
    temperature_list,
    questions_dir=QUESTIONS_DIR,
    selected_mats=None,
    round_digits=6,
    save_matrices=True,
    save_analysis=True,
):
    all_question_overviews = []

    qnames = get_question_names_from_all_matrices(all_matrices)

    for q_index, qname in enumerate(qnames):
        print(f"\n\n{'#'*100}")
        print(f"Processing question {q_index}/{len(qnames)-1}: {qname}")
        print(f"{'#'*100}")

        if save_matrices:
            print_and_save_question_matrices(
                all_matrices=all_matrices,
                q_index=q_index,
                questions_dir=questions_dir,
                selected_mats=selected_mats,
                round_digits=round_digits,
                save_npy=True,
                save_csv=True,
            )

        if save_analysis:
            overview_df, stat_results = analyze_and_save_question_matrices(
                all_matrices=all_matrices,
                q_index=q_index,
                k=k,
                temperature_list=temperature_list,
                questions_dir=questions_dir,
                selected_mats=selected_mats,
                round_digits=round_digits,
            )

            tmp = overview_df.copy()
            tmp.insert(0, "question_name", qname)
            tmp.insert(0, "question_index", q_index)
            all_question_overviews.append(tmp)

    # 额外保存一个总汇总表（放在 Questions 根目录下）
    if all_question_overviews:
        global_overview_df = pd.concat(all_question_overviews, ignore_index=True)
        global_path = Path(questions_dir) / "CrossEncoder_Results_AllQuestions_Overview.csv"
        global_overview_df.to_csv(
            global_path,
            index=False,
            encoding="utf-8-sig",
            float_format=f"%.{round_digits}f"
        )
        print(f"\nAll-question overview saved to: {global_path}")

        return global_overview_df

    return None

In [14]:
global_overview_df = run_all_questions_print_and_save(
    all_matrices=all_matrices,
    k=k,
    temperature_list=temperature_list,
    questions_dir=QUESTIONS_DIR,
    selected_mats=SELECTED_MATS,
    round_digits=ROUND_DIGITS,
    save_matrices=True,
    save_analysis=True,
)

####################################################################################################
Processing question 0/17: Easy B3666
####################################################################################################

================================================================================
题目 index = 0
题目名称 = Easy B3666
矩阵保存目录 = Questions/Easy B3666/CrossEncoder_Results/matrices
================================================================================

===== mat1PI =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.742610,0.720573,0.727237,0.743048,0.737616,0.782865,0.753669,0.725956,0.772721,0.773219
1,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.742610,0.720573,0.727237,0.743048,0.737616,0.782865,0.753669,0.725956,0.772721,0.773219
2,0.932416,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.742610,0.720573,0.727237,0.743048,0.737616,0.782865,0.753669,0.725956,0.772721,0.773219
3,0.932416,0.932416,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.742610,0.720573,0.727237,0.743048,0.737616,0.782865,0.753669,0.725956,0.772721,0.773219
4,0.932416,0.932416,0.932416,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.742610,0.720573,0.727237,0.743048,0.737616,0.782865,0.753669,0.725956,0.772721,0.773219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.782865,0.782865,0.782865,0.782865,0.782865,0.782865,0.782865,0.782865,0.782865,0.782865,...,0.713352,0.725319,0.732733,0.785111,0.782900,1.000000,0.747704,0.752717,0.812483,0.786229
76,0.753669,0.753669,0.753669,0.753669,0.753669,0.753669,0.753669,0.753669,0.753669,0.753669,...,0.759771,0.740572,0.705982,0.740654,0.828167,0.747704,1.000000,0.832080,0.801342,0.762384
77,0.725956,0.725956,0.725956,0.725956,0.725956,0.725956,0.725956,0.725956,0.725956,0.725956,...,0.699156,0.749979,0.722023,0.750549,0.797293,0.752717,0.832080,1.000000,0.759443,0.765376
78,0.772721,0.772721,0.772721,0.772721,0.772721,0.772721,0.772721,0.772721,0.772721,0.772721,...,0.740559,0.762598,0.696816,0.785378,0.818542,0.812483,0.801342,0.759443,1.000000,0.712056
79,0.773219,0.773219,0.773219,0.773219,0.773219,0.773219,0.773219,0.773219,0.773219,0.773219,...,0.710023,0.760362,0.713562,0.768768,0.798073,0.786229,0.762384,0.765376,0.712056,1.000000

===== mat2FD =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.818189,0.667240,0.812937,0.745534,0.750655,0.786652,0.806821,0.752666,0.800093,0.822185
1,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.818189,0.667240,0.812937,0.745534,0.750655,0.786652,0.806821,0.752666,0.800093,0.822185
2,0.937798,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.818189,0.667240,0.812937,0.745534,0.750655,0.786652,0.806821,0.752666,0.800093,0.822185
3,0.937798,0.937798,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.818189,0.667240,0.812937,0.745534,0.750655,0.786652,0.806821,0.752666,0.800093,0.822185
4,0.937798,0.937798,0.937798,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.818189,0.667240,0.812937,0.745534,0.750655,0.786652,0.806821,0.752666,0.800093,0.822185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.786652,0.786652,0.786652,0.786652,0.786652,0.786652,0.786652,0.786652,0.786652,0.786652,...,0.726473,0.572207,0.768425,0.677656,0.681837,1.000000,0.630828,0.656737,0.738551,0.682232
76,0.806821,0.806821,0.806821,0.806821,0.806821,0.806821,0.806821,0.806821,0.806821,0.806821,...,0.680583,0.542165,0.741109,0.602614,0.712777,0.630828,1.000000,0.759166,0.757097,0.768961
77,0.752666,0.752666,0.752666,0.752666,0.752666,0.752666,0.752666,0.752666,0.752666,0.752666,...,0.673025,0.600096,0.728700,0.603259,0.716913,0.656737,0.759166,1.000000,0.668635,0.669421
78,0.800093,0.800093,0.800093,0.800093,0.800093,0.800093,0.800093,0.800093,0.800093,0.800093,...,0.758054,0.574225,0.780849,0.618966,0.720292,0.738551,0.757097,0.668635,1.000000,0.745520
79,0.822185,0.822185,0.822185,0.822185,0.822185,0.822185,0.822185,0.822185,0.822185,0.822185,...,0.747060,0.571795,0.741786,0.620100,0.731090,0.682232,0.768961,0.669421,0.745520,1.000000

===== mat3RC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.563820,0.650831,0.573120,0.595089,0.653131,0.642835,0.543712,0.657721,0.776650,0.600614
1,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.563820,0.650831,0.573120,0.595089,0.653131,0.642835,0.543712,0.657721,0.776650,0.600614
2,0.940892,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.563820,0.650831,0.573120,0.595089,0.653131,0.642835,0.543712,0.657721,0.776650,0.600614
3,0.940892,0.940892,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.563820,0.650831,0.573120,0.595089,0.653131,0.642835,0.543712,0.657721,0.776650,0.600614
4,0.940892,0.940892,0.940892,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.563820,0.650831,0.573120,0.595089,0.653131,0.642835,0.543712,0.657721,0.776650,0.600614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.642835,0.642835,0.642835,0.642835,0.642835,0.642835,0.642835,0.642835,0.642835,0.642835,...,0.493201,0.609631,0.658648,0.649327,0.738653,1.000000,0.558875,0.729144,0.603728,0.579598
76,0.543712,0.543712,0.543712,0.543712,0.543712,0.543712,0.543712,0.543712,0.543712,0.543712,...,0.597922,0.648598,0.680382,0.601842,0.541669,0.558875,1.000000,0.590070,0.571669,0.663643
77,0.657721,0.657721,0.657721,0.657721,0.657721,0.657721,0.657721,0.657721,0.657721,0.657721,...,0.548346,0.595903,0.675714,0.662055,0.694387,0.729144,0.590070,1.000000,0.527416,0.593610
78,0.776650,0.776650,0.776650,0.776650,0.776650,0.776650,0.776650,0.776650,0.776650,0.776650,...,0.560489,0.669545,0.591948,0.627245,0.598004,0.603728,0.571669,0.527416,1.000000,0.640039
79,0.600614,0.600614,0.600614,0.600614,0.600614,0.600614,0.600614,0.600614,0.600614,0.600614,...,0.623773,0.687970,0.674382,0.647320,0.622563,0.579598,0.663643,0.593610,0.640039,1.000000

===== mat4MS =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.716093,0.702910,0.693345,0.710664,0.644400,0.692768,0.725513,0.731428,0.700213,0.687980
1,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.716093,0.702910,0.693345,0.710664,0.644400,0.692768,0.725513,0.731428,0.700213,0.687980
2,0.909813,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.716093,0.702910,0.693345,0.710664,0.644400,0.692768,0.725513,0.731428,0.700213,0.687980
3,0.909813,0.909813,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.716093,0.702910,0.693345,0.710664,0.644400,0.692768,0.725513,0.731428,0.700213,0.687980
4,0.909813,0.909813,0.909813,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.716093,0.702910,0.693345,0.710664,0.644400,0.692768,0.725513,0.731428,0.700213,0.687980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.692768,0.692768,0.692768,0.692768,0.692768,0.692768,0.692768,0.692768,0.692768,0.692768,...,0.641159,0.697461,0.684444,0.663434,0.696965,1.000000,0.693231,0.734915,0.710495,0.673236
76,0.725513,0.725513,0.725513,0.725513,0.725513,0.725513,0.725513,0.725513,0.725513,0.725513,...,0.648801,0.677058,0.665975,0.632553,0.733060,0.693231,1.000000,0.685282,0.690487,0.683422
77,0.731428,0.731428,0.731428,0.731428,0.731428,0.731428,0.731428,0.731428,0.731428,0.731428,...,0.625376,0.664588,0.702042,0.638899,0.682396,0.734915,0.685282,1.000000,0.713001,0.712003
78,0.700213,0.700213,0.700213,0.700213,0.700213,0.700213,0.700213,0.700213,0.700213,0.700213,...,0.645179,0.686964,0.702617,0.702710,0.704490,0.710495,0.690487,0.713001,1.000000,0.699483
79,0.687980,0.687980,0.687980,0.687980,0.687980,0.687980,0.687980,0.687980,0.687980,0.687980,...,0.652597,0.708035,0.709929,0.589470,0.626485,0.673236,0.683422,0.712003,0.699483,1.000000

===== mat5INV =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.720711,0.636072,0.759395,0.676514,0.728709,0.764868,0.720728,0.723188,0.709376,0.703691
1,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.720711,0.636072,0.759395,0.676514,0.728709,0.764868,0.720728,0.723188,0.709376,0.703691
2,0.955818,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.720711,0.636072,0.759395,0.676514,0.728709,0.764868,0.720728,0.723188,0.709376,0.703691
3,0.955818,0.955818,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.720711,0.636072,0.759395,0.676514,0.728709,0.764868,0.720728,0.723188,0.709376,0.703691
4,0.955818,0.955818,0.955818,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.720711,0.636072,0.759395,0.676514,0.728709,0.764868,0.720728,0.723188,0.709376,0.703691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.764868,0.764868,0.764868,0.764868,0.764868,0.764868,0.764868,0.764868,0.764868,0.764868,...,0.699867,0.664168,0.695713,0.734203,0.690518,1.000000,0.707132,0.670920,0.635192,0.739996
76,0.720728,0.720728,0.720728,0.720728,0.720728,0.720728,0.720728,0.720728,0.720728,0.720728,...,0.681499,0.682507,0.737578,0.696830,0.735798,0.707132,1.000000,0.688675,0.665681,0.725111
77,0.723188,0.723188,0.723188,0.723188,0.723188,0.723188,0.723188,0.723188,0.723188,0.723188,...,0.718047,0.622570,0.680603,0.631164,0.673761,0.670920,0.688675,1.000000,0.544739,0.593675
78,0.709376,0.709376,0.709376,0.709376,0.709376,0.709376,0.709376,0.709376,0.709376,0.709376,...,0.606976,0.590992,0.652287,0.655131,0.614693,0.635192,0.665681,0.544739,1.000000,0.603191
79,0.703691,0.703691,0.703691,0.703691,0.703691,0.703691,0.703691,0.703691,0.703691,0.703691,...,0.634541,0.679186,0.635166,0.627829,0.712134,0.739996,0.725111,0.593675,0.603191,1.000000

===== mat6POUR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.626579,0.580329,0.607962,0.618898,0.611764,0.651573,0.605249,0.605214,0.623783,0.611210
1,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.626579,0.580329,0.607962,0.618898,0.611764,0.651573,0.605249,0.605214,0.623783,0.611210
2,0.895031,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.626579,0.580329,0.607962,0.618898,0.611764,0.651573,0.605249,0.605214,0.623783,0.611210
3,0.895031,0.895031,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.626579,0.580329,0.607962,0.618898,0.611764,0.651573,0.605249,0.605214,0.623783,0.611210
4,0.895031,0.895031,0.895031,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.626579,0.580329,0.607962,0.618898,0.611764,0.651573,0.605249,0.605214,0.623783,0.611210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.651573,0.651573,0.651573,0.651573,0.651573,0.651573,0.651573,0.651573,0.651573,0.651573,...,0.638375,0.611937,0.620088,0.632776,0.592532,1.000000,0.652324,0.582579,0.598708,0.639333
76,0.605249,0.605249,0.605249,0.605249,0.605249,0.605249,0.605249,0.605249,0.605249,0.605249,...,0.622584,0.610806,0.601222,0.664537,0.611918,0.652324,1.000000,0.605918,0.647769,0.645975
77,0.605214,0.605214,0.605214,0.605214,0.605214,0.605214,0.605214,0.605214,0.605214,0.605214,...,0.608257,0.624955,0.583202,0.658294,0.631963,0.582579,0.605918,1.000000,0.661431,0.576256
78,0.623783,0.623783,0.623783,0.623783,0.623783,0.623783,0.623783,0.623783,0.623783,0.623783,...,0.600278,0.609908,0.590577,0.686763,0.617302,0.598708,0.647769,0.661431,1.000000,0.572814
79,0.611210,0.611210,0.611210,0.611210,0.611210,0.611210,0.611210,0.611210,0.611210,0.611210,...,0.668153,0.625552,0.606800,0.655901,0.591770,0.639333,0.645975,0.576256,0.572814,1.000000

===== mat7OR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.640191,0.658986,0.760100,0.547555,0.663929,0.735002,0.653823,0.663093,0.678870,0.716768
1,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.640191,0.658986,0.760100,0.547555,0.663929,0.735002,0.653823,0.663093,0.678870,0.716768
2,0.969586,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.640191,0.658986,0.760100,0.547555,0.663929,0.735002,0.653823,0.663093,0.678870,0.716768
3,0.969586,0.969586,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.640191,0.658986,0.760100,0.547555,0.663929,0.735002,0.653823,0.663093,0.678870,0.716768
4,0.969586,0.969586,0.969586,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.640191,0.658986,0.760100,0.547555,0.663929,0.735002,0.653823,0.663093,0.678870,0.716768
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.735002,0.735002,0.735002,0.735002,0.735002,0.735002,0.735002,0.735002,0.735002,0.735002,...,0.649235,0.700375,0.775748,0.625017,0.716732,1.000000,0.654571,0.666943,0.703483,0.705952
76,0.653823,0.653823,0.653823,0.653823,0.653823,0.653823,0.653823,0.653823,0.653823,0.653823,...,0.652496,0.704564,0.673355,0.589161,0.786610,0.654571,1.000000,0.640518,0.681404,0.676236
77,0.663093,0.663093,0.663093,0.663093,0.663093,0.663093,0.663093,0.663093,0.663093,0.663093,...,0.692947,0.710306,0.642768,0.712549,0.760006,0.666943,0.640518,1.000000,0.680354,0.643007
78,0.678870,0.678870,0.678870,0.678870,0.678870,0.678870,0.678870,0.678870,0.678870,0.678870,...,0.666671,0.693563,0.686666,0.695542,0.701377,0.703483,0.681404,0.680354,1.000000,0.661742
79,0.716768,0.716768,0.716768,0.716768,0.716768,0.716768,0.716768,0.716768,0.716768,0.716768,...,0.605844,0.652852,0.726461,0.618139,0.733388,0.705952,0.676236,0.643007,0.661742,1.000000

===== mat8ECCC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.553127,0.551050,0.530365,0.592452,0.513073,0.589750,0.516688,0.489776,0.596843,0.499455
1,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.553127,0.551050,0.530365,0.592452,0.513073,0.589750,0.516688,0.489776,0.596843,0.499455
2,0.750305,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.553127,0.551050,0.530365,0.592452,0.513073,0.589750,0.516688,0.489776,0.596843,0.499455
3,0.750305,0.750305,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.553127,0.551050,0.530365,0.592452,0.513073,0.589750,0.516688,0.489776,0.596843,0.499455
4,0.750305,0.750305,0.750305,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.553127,0.551050,0.530365,0.592452,0.513073,0.589750,0.516688,0.489776,0.596843,0.499455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.589750,0.589750,0.589750,0.589750,0.589750,0.589750,0.589750,0.589750,0.589750,0.589750,...,0.613455,0.540519,0.600025,0.561398,0.616657,1.000000,0.549411,0.501417,0.616029,0.526632
76,0.516688,0.516688,0.516688,0.516688,0.516688,0.516688,0.516688,0.516688,0.516688,0.516688,...,0.589394,0.575921,0.581399,0.549064,0.622025,0.549411,1.000000,0.554158,0.612879,0.574872
77,0.489776,0.489776,0.489776,0.489776,0.489776,0.489776,0.489776,0.489776,0.489776,0.489776,...,0.588915,0.526056,0.499602,0.524116,0.599769,0.501417,0.554158,1.000000,0.517812,0.521550
78,0.596843,0.596843,0.596843,0.596843,0.596843,0.596843,0.596843,0.596843,0.596843,0.596843,...,0.650370,0.545967,0.584547,0.595520,0.619309,0.616029,0.612879,0.517812,1.000000,0.552289
79,0.499455,0.499455,0.499455,0.499455,0.499455,0.499455,0.499455,0.499455,0.499455,0.499455,...,0.607008,0.609070,0.548810,0.530725,0.637867,0.526632,0.574872,0.521550,0.552289,1.000000

===== mat9N =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.201497,0.521345,0.377704,0.219456,0.369622,0.174499,0.893429,0.924116,0.208035,0.944298
1,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.201497,0.521345,0.377704,0.219456,0.369622,0.174499,0.893429,0.924116,0.208035,0.944298
2,0.972504,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.201497,0.521345,0.377704,0.219456,0.369622,0.174499,0.893429,0.924116,0.208035,0.944298
3,0.972504,0.972504,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.201497,0.521345,0.377704,0.219456,0.369622,0.174499,0.893429,0.924116,0.208035,0.944298
4,0.972504,0.972504,0.972504,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.201497,0.521345,0.377704,0.219456,0.369622,0.174499,0.893429,0.924116,0.208035,0.944298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.174499,0.174499,0.174499,0.174499,0.174499,0.174499,0.174499,0.174499,0.174499,0.174499,...,0.440648,0.565055,0.428467,0.254509,0.449172,1.000000,0.298288,0.148912,0.207460,0.253191
76,0.893429,0.893429,0.893429,0.893429,0.893429,0.893429,0.893429,0.893429,0.893429,0.893429,...,0.238666,0.558881,0.368989,0.053433,0.395951,0.298288,1.000000,0.901539,0.207893,0.878242
77,0.924116,0.924116,0.924116,0.924116,0.924116,0.924116,0.924116,0.924116,0.924116,0.924116,...,0.109258,0.564173,0.384366,0.148117,0.424958,0.148912,0.901539,1.000000,0.217421,0.909195
78,0.208035,0.208035,0.208035,0.208035,0.208035,0.208035,0.208035,0.208035,0.208035,0.208035,...,0.214319,0.543797,0.356606,0.300048,0.477939,0.207460,0.207893,0.217421,1.000000,0.192965
79,0.944298,0.944298,0.944298,0.944298,0.944298,0.944298,0.944298,0.944298,0.944298,0.944298,...,0.197957,0.567639,0.424662,0.295430,0.437139,0.253191,0.878242,0.909195,0.192965,1.000000

================================================================================
Question index = 0
Question Name = Easy B3666
k = 20
temperature_list = [0.0, 0.2, 0.5, 0.8]
analysis save dir = Questions/Easy B3666/CrossEncoder_Results/analysis
================================================================================

===== Overview Table =====

,matrix,offdiag_mean,offdiag_std,offdiag_min,offdiag_max,overall_within_mean,overall_cross_mean,within_minus_cross,prototype_idx,prototype_score,outlier_idx,outlier_score
0,mat1PI,0.763195,0.057502,0.570674,0.932416,0.800200,0.751477,0.048723,32,0.799049,56,0.658571
1,mat2FD,0.733523,0.082591,0.522326,0.937798,0.754705,0.726815,0.027890,0,0.803777,71,0.638425
2,mat3RC,0.638475,0.106228,0.380689,0.959845,0.699437,0.619170,0.080266,1,0.698554,58,0.534519
3,mat4MS,0.704319,0.065843,0.552930,0.909813,0.734309,0.694822,0.039487,0,0.760732,57,0.652982
4,mat5INV,0.690876,0.087308,0.504538,0.955818,0.727079,0.679412,0.047667,0,0.770363,37,0.616406
5,mat6POUR,0.648243,0.071406,0.487060,0.895031,0.701991,0.631222,0.070769,0,0.693702,24,0.582685
6,mat7OR,0.717442,0.083440,0.525212,0.969586,0.782320,0.696898,0.085422,64,0.749186,73,0.611370
7,mat8ECCC,0.563561,0.064605,0.423086,0.750305,0.596924,0.552996,0.043929,25,0.604515,77,0.515374
8,mat9N,0.501161,0.233259,0.009289,0.972860,0.600769,0.469618,0.131151,31,0.599298,63,0.241310

==============================
Matrix: mat1PI
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.763195     0.057502     0.570674     0.932416

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.932416,0.000000,0.932416,0.932416
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.775268,0.040702,0.669451,0.872105
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.740582,0.045024,0.612807,0.841666
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.752532,0.037913,0.637377,0.844324

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.748010  0.731246  0.753482
0.2  0.748010       NaN  0.760846  0.768769
0.5  0.731246  0.760846       NaN  0.746507
0.8  0.753482  0.768769  0.746507       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.023730  0.029389  0.020601
0.2  0.023730       NaN  0.045312  0.041484
0.5  0.029389  0.045312       NaN  0.049339
0.8  0.020601  0.041484  0.049339       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0               0.8002            0.751477            0.048723

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             32          0.799049          0.2                   12
1             61          0.789889          0.8                    1
2              0          0.789502          0.0                    0
3              1          0.789502          0.0                    1
4              4          0.789502          0.0                    4
..           ...               ...          ...                  ...
75            67          0.720795          0.8                    7
76            44          0.714352          0.5                    4
77            72          0.714326          0.8                   12
78            47          0.690868          0.5                    7
79            56          0.658571          0.5                   16

[80 rows x 4 columns]

prototype_idx = 32, prototype_score = 0.799049
outlier_idx = 56, outlier_score = 0.658571


==============================
Matrix: mat2FD
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.733523     0.082591     0.522326     0.937798

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.937798,0.000000,0.937798,0.937798
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.706534,0.063596,0.550902,0.882532
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.708102,0.066616,0.539791,0.871299
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.666387,0.066203,0.522326,0.812861

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.749407  0.763520  0.771084
0.2  0.749407       NaN  0.700106  0.679844
0.5  0.763520  0.700106       NaN  0.696933
0.8  0.771084  0.679844  0.696933       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.037001  0.044032  0.045298
0.2  0.037001       NaN  0.064678  0.063546
0.5  0.044032  0.064678       NaN  0.060670
0.8  0.045298  0.063546  0.060670       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.754705            0.726815             0.02789

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.803777          0.0                    0
1              1          0.803777          0.0                    1
2              2          0.803777          0.0                    2
3              3          0.803777          0.0                    3
4              4          0.803777          0.0                    4
..           ...               ...          ...                  ...
75            44          0.662426          0.5                    4
76            25          0.660702          0.2                    5
77            24          0.659592          0.2                    4
78            53          0.652434          0.5                   13
79            71          0.638425          0.8                   11

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.803777
outlier_idx = 71, outlier_score = 0.638425


==============================
Matrix: mat3RC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.638475     0.106228     0.380689     0.959845

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.940892,0.000000,0.940892,0.940892
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.659275,0.084596,0.430719,0.959845
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.594868,0.069854,0.391905,0.765210
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.602712,0.074246,0.445141,0.806375

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.661805  0.595328  0.608308
0.2  0.661805       NaN  0.621280  0.627151
0.5  0.595328  0.621280       NaN  0.601150
0.8  0.608308  0.627151  0.601150       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.050036  0.063409  0.061469
0.2  0.050036       NaN  0.079290  0.087574
0.5  0.063409  0.079290       NaN  0.079131
0.8  0.061469  0.087574  0.079131       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.699437             0.61917            0.080266

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              1          0.698554          0.0                    1
1              7          0.698554          0.0                    7
2              6          0.698554          0.0                    6
3             15          0.698554          0.0                   15
4             12          0.698554          0.0                   12
..           ...               ...          ...                  ...
75            67          0.551505          0.8                    7
76            47          0.548317          0.5                    7
77            36          0.541550          0.2                   16
78            41          0.538990          0.5                    1
79            58          0.534519          0.5                   18

[80 rows x 4 columns]

prototype_idx = 1, prototype_score = 0.698554
outlier_idx = 58, outlier_score = 0.534519


==============================
Matrix: mat4MS
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.704319     0.065843      0.55293     0.909813

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.909813,0.000000,0.909813,0.909813
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.691737,0.035950,0.608191,0.813542
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.663016,0.045444,0.552930,0.841913
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.672670,0.037327,0.567501,0.755929

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.721750  0.707962  0.710857
0.2  0.721750       NaN  0.677828  0.680306
0.5  0.707962  0.677828       NaN  0.670229
0.8  0.710857  0.680306  0.670229       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.028966  0.034886  0.035278
0.2  0.028966       NaN  0.036074  0.036768
0.5  0.034886  0.036074       NaN  0.042642
0.8  0.035278  0.036768  0.042642       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.734309            0.694822            0.039487

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.760732          0.0                    0
1              1          0.760732          0.0                    1
2              2          0.760732          0.0                    2
3              3          0.760732          0.0                    3
4              4          0.760732          0.0                    4
..           ...               ...          ...                  ...
75            40          0.662370          0.5                    0
76            56          0.662297          0.5                   16
77            43          0.657137          0.5                    3
78            61          0.653828          0.8                    1
79            57          0.652982          0.5                   17

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.760732
outlier_idx = 57, outlier_score = 0.652982


==============================
Matrix: mat5INV
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.690876     0.087308     0.504538     0.955818

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.955818,0.000000,0.955818,0.955818
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.655276,0.047723,0.564855,0.799483
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.656312,0.061919,0.504538,0.798735
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.640910,0.051313,0.522029,0.800193

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.710448  0.711151  0.713309
0.2  0.710448       NaN  0.648787  0.643833
0.5  0.711151  0.648787       NaN  0.648943
0.8  0.713309  0.643833  0.648943       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.036250  0.052160  0.037354
0.2  0.036250       NaN  0.051286  0.047405
0.5  0.052160  0.051286       NaN  0.054956
0.8  0.037354  0.047405  0.054956       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.727079            0.679412            0.047667

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.770363          0.0                    0
1              1          0.770363          0.0                    1
2              2          0.770363          0.0                    2
3              3          0.770363          0.0                    3
4              4          0.770363          0.0                    4
..           ...               ...          ...                  ...
75            36          0.623587          0.2                   16
76            49          0.621004          0.5                    9
77            63          0.618732          0.8                    3
78            56          0.617186          0.5                   16
79            37          0.616406          0.2                   17

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.770363
outlier_idx = 37, outlier_score = 0.616406


==============================
Matrix: mat6POUR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.648243     0.071406      0.48706     0.895031

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.895031,0.000000,0.895031,0.895031
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.646098,0.046823,0.533799,0.778609
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.644517,0.037904,0.539365,0.758745
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.622320,0.030459,0.551699,0.701652

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.629098  0.640548  0.620197
0.2  0.629098       NaN  0.642345  0.625476
0.5  0.640548  0.642345       NaN  0.629671
0.8  0.620197  0.625476  0.629671       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.025883  0.019490  0.017328
0.2  0.025883       NaN  0.048045  0.041391
0.5  0.019490  0.048045       NaN  0.037103
0.8  0.017328  0.041391  0.037103       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.701991            0.631222            0.070769

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.693702          0.0                    0
1              1          0.693702          0.0                    1
2              2          0.693702          0.0                    2
3              3          0.693702          0.0                    3
4              4          0.693702          0.0                    4
..           ...               ...          ...                  ...
75            77          0.604120          0.8                   17
76            71          0.602234          0.8                   11
77            25          0.594841          0.2                    5
78            49          0.587201          0.5                    9
79            24          0.582685          0.2                    4

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.693702
outlier_idx = 24, outlier_score = 0.582685


==============================
Matrix: mat7OR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.717442      0.08344     0.525212     0.969586

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.969586,0.000000,0.969586,0.969586
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.740430,0.060411,0.596759,0.921786
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.714445,0.050507,0.600631,0.894116
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.704819,0.052127,0.525212,0.841404

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.671584  0.687982  0.673789
0.2  0.671584       NaN  0.721345  0.715254
0.5  0.687982  0.721345       NaN  0.711433
0.8  0.673789  0.715254  0.711433       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.049439  0.038362  0.054486
0.2  0.049439       NaN  0.054072  0.054597
0.5  0.038362  0.054072       NaN  0.050143
0.8  0.054486  0.054597  0.050143       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0              0.78232            0.696898            0.085422

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             64          0.749186          0.8                    4
1              0          0.747965          0.0                    0
2              3          0.747965          0.0                    3
3              2          0.747965          0.0                    2
4              6          0.747965          0.0                    6
..           ...               ...          ...                  ...
75            71          0.673416          0.8                   11
76            39          0.657146          0.2                   19
77            68          0.656916          0.8                    8
78            54          0.648976          0.5                   14
79            73          0.611370          0.8                   13

[80 rows x 4 columns]

prototype_idx = 64, prototype_score = 0.749186
outlier_idx = 73, outlier_score = 0.611370


==============================
Matrix: mat8ECCC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.563561     0.064605     0.423086     0.750305

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.750305,0.000000,0.750305,0.750305
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.545243,0.057012,0.479259,0.678587
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.531467,0.050438,0.458970,0.668832
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.560683,0.045820,0.429656,0.686769

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.554684  0.560394  0.543795
0.2  0.554684       NaN  0.537555  0.561747
0.5  0.560394  0.537555       NaN  0.559800
0.8  0.543795  0.561747  0.559800       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.020780  0.020645  0.033427
0.2  0.020780       NaN  0.054494  0.053498
0.5  0.020645  0.054494       NaN  0.055007
0.8  0.033427  0.053498  0.055007       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.596924            0.552996            0.043929

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             25          0.604515          0.2                    5
1             30          0.602602          0.2                   10
2             27          0.600527          0.2                    7
3              0          0.600421          0.0                    0
4              4          0.600421          0.0                    4
..           ...               ...          ...                  ...
75            34          0.530681          0.2                   14
76            39          0.526738          0.2                   19
77            69          0.523075          0.8                    9
78            68          0.519470          0.8                    8
79            77          0.515374          0.8                   17

[80 rows x 4 columns]

prototype_idx = 25, prototype_score = 0.604515
outlier_idx = 77, outlier_score = 0.515374


==============================
Matrix: mat9N
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.501161     0.233259     0.009289      0.97286

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.972504,0.000000,0.972504,0.972504
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.522738,0.137254,0.010807,0.953477
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.510997,0.137900,0.009289,0.867514
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.396838,0.201003,0.010212,0.909195

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.476040  0.470903  0.396524
0.2  0.476040       NaN  0.522619  0.483737
0.5  0.470903  0.522619       NaN  0.467886
0.8  0.396524  0.483737  0.467886       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.240285  0.217008  0.293839
0.2  0.240285       NaN  0.129456  0.169315
0.5  0.217008  0.129456       NaN  0.175313
0.8  0.293839  0.169315  0.175313       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.600769            0.469618            0.131151

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             31          0.599298          0.2                   11
1             79          0.594687          0.8                   19
2             45          0.587792          0.5                    5
3             54          0.582464          0.5                   14
4             64          0.581039          0.8                    4
..           ...               ...          ...                  ...
75            48          0.322243          0.5                    8
76            21          0.319778          0.2                    1
77            25          0.283374          0.2                    5
78            47          0.271053          0.5                    7
79            63          0.241310          0.8                    3

[80 rows x 4 columns]

prototype_idx = 31, prototype_score = 0.599298
outlier_idx = 63, outlier_score = 0.241310


####################################################################################################
Processing question 1/17: Easy P15288
####################################################################################################

================================================================================
题目 index = 1
题目名称 = Easy P15288
矩阵保存目录 = Questions/Easy P15288/CrossEncoder_Results/matrices
================================================================================

===== mat1PI =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,...,0.707889,0.721270,0.692251,0.780272,0.725640,0.702296,0.822729,0.702727,0.766981,0.712381
1,0.833391,1.000000,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,...,0.707889,0.721270,0.692251,0.780272,0.725640,0.702296,0.822729,0.702727,0.766981,0.712381
2,0.833391,0.833391,1.000000,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,...,0.707889,0.721270,0.692251,0.780272,0.725640,0.702296,0.822729,0.702727,0.766981,0.712381
3,0.833391,0.833391,0.833391,1.000000,0.833391,0.833391,0.833391,0.833391,0.833391,0.833391,...,0.707889,0.721270,0.692251,0.780272,0.725640,0.702296,0.822729,0.702727,0.766981,0.712381
4,0.833391,0.833391,0.833391,0.833391,1.000000,0.833391,0.833391,0.833391,0.833391,0.833391,...,0.707889,0.721270,0.692251,0.780272,0.725640,0.702296,0.822729,0.702727,0.766981,0.712381
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.702296,0.702296,0.702296,0.702296,0.702296,0.702296,0.702296,0.702296,0.702296,0.702296,...,0.645414,0.644210,0.695452,0.711890,0.721452,1.000000,0.775157,0.666773,0.723875,0.655582
76,0.822729,0.822729,0.822729,0.822729,0.822729,0.822729,0.822729,0.822729,0.822729,0.822729,...,0.748328,0.729605,0.727866,0.820926,0.769596,0.775157,1.000000,0.684502,0.754677,0.709164
77,0.702727,0.702727,0.702727,0.702727,0.702727,0.702727,0.702727,0.702727,0.702727,0.702727,...,0.684397,0.613751,0.634448,0.671318,0.706788,0.666773,0.684502,1.000000,0.685603,0.629572
78,0.766981,0.766981,0.766981,0.766981,0.766981,0.766981,0.766981,0.766981,0.766981,0.766981,...,0.739857,0.758039,0.713694,0.802080,0.757247,0.723875,0.754677,0.685603,1.000000,0.710168
79,0.712381,0.712381,0.712381,0.712381,0.712381,0.712381,0.712381,0.712381,0.712381,0.712381,...,0.712919,0.682069,0.670373,0.724551,0.724462,0.655582,0.709164,0.629572,0.710168,1.000000

===== mat2FD =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,...,0.632722,0.625077,0.588892,0.573394,0.667853,0.647422,0.603648,0.630835,0.616588,0.652032
1,0.781655,1.000000,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,...,0.632722,0.625077,0.588892,0.573394,0.667853,0.647422,0.603648,0.630835,0.616588,0.652032
2,0.781655,0.781655,1.000000,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,...,0.632722,0.625077,0.588892,0.573394,0.667853,0.647422,0.603648,0.630835,0.616588,0.652032
3,0.781655,0.781655,0.781655,1.000000,0.781655,0.781655,0.781655,0.781655,0.781655,0.781655,...,0.632722,0.625077,0.588892,0.573394,0.667853,0.647422,0.603648,0.630835,0.616588,0.652032
4,0.781655,0.781655,0.781655,0.781655,1.000000,0.781655,0.781655,0.781655,0.781655,0.781655,...,0.632722,0.625077,0.588892,0.573394,0.667853,0.647422,0.603648,0.630835,0.616588,0.652032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.647422,0.647422,0.647422,0.647422,0.647422,0.647422,0.647422,0.647422,0.647422,0.647422,...,0.665868,0.637736,0.671611,0.716783,0.724247,1.000000,0.624722,0.690579,0.627030,0.696621
76,0.603648,0.603648,0.603648,0.603648,0.603648,0.603648,0.603648,0.603648,0.603648,0.603648,...,0.684453,0.598123,0.584994,0.676803,0.669089,0.624722,1.000000,0.648968,0.652890,0.727232
77,0.630835,0.630835,0.630835,0.630835,0.630835,0.630835,0.630835,0.630835,0.630835,0.630835,...,0.720615,0.581548,0.593822,0.665167,0.747792,0.690579,0.648968,1.000000,0.719288,0.722448
78,0.616588,0.616588,0.616588,0.616588,0.616588,0.616588,0.616588,0.616588,0.616588,0.616588,...,0.729534,0.607624,0.571900,0.650355,0.723649,0.627030,0.652890,0.719288,1.000000,0.701709
79,0.652032,0.652032,0.652032,0.652032,0.652032,0.652032,0.652032,0.652032,0.652032,0.652032,...,0.695945,0.586744,0.667429,0.671637,0.726221,0.696621,0.727232,0.722448,0.701709,1.000000

===== mat3RC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,...,0.650945,0.684907,0.631780,0.687296,0.762861,0.625367,0.707517,0.759919,0.673527,0.627238
1,0.874042,1.000000,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,...,0.650945,0.684907,0.631780,0.687296,0.762861,0.625367,0.707517,0.759919,0.673527,0.627238
2,0.874042,0.874042,1.000000,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,...,0.650945,0.684907,0.631780,0.687296,0.762861,0.625367,0.707517,0.759919,0.673527,0.627238
3,0.874042,0.874042,0.874042,1.000000,0.874042,0.874042,0.874042,0.874042,0.874042,0.874042,...,0.650945,0.684907,0.631780,0.687296,0.762861,0.625367,0.707517,0.759919,0.673527,0.627238
4,0.874042,0.874042,0.874042,0.874042,1.000000,0.874042,0.874042,0.874042,0.874042,0.874042,...,0.650945,0.684907,0.631780,0.687296,0.762861,0.625367,0.707517,0.759919,0.673527,0.627238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.625367,0.625367,0.625367,0.625367,0.625367,0.625367,0.625367,0.625367,0.625367,0.625367,...,0.602751,0.631004,0.632906,0.666666,0.646035,1.000000,0.635205,0.624423,0.613113,0.627263
76,0.707517,0.707517,0.707517,0.707517,0.707517,0.707517,0.707517,0.707517,0.707517,0.707517,...,0.681279,0.671816,0.612779,0.644921,0.668607,0.635205,1.000000,0.670697,0.697834,0.755334
77,0.759919,0.759919,0.759919,0.759919,0.759919,0.759919,0.759919,0.759919,0.759919,0.759919,...,0.703057,0.643892,0.647590,0.686126,0.704941,0.624423,0.670697,1.000000,0.570401,0.614796
78,0.673527,0.673527,0.673527,0.673527,0.673527,0.673527,0.673527,0.673527,0.673527,0.673527,...,0.633488,0.627196,0.600828,0.631386,0.641985,0.613113,0.697834,0.570401,1.000000,0.633695
79,0.627238,0.627238,0.627238,0.627238,0.627238,0.627238,0.627238,0.627238,0.627238,0.627238,...,0.659280,0.690760,0.640561,0.616451,0.659561,0.627263,0.755334,0.614796,0.633695,1.000000

===== mat4MS =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,...,0.683150,0.719652,0.769975,0.684826,0.696569,0.661825,0.630509,0.785825,0.644523,0.635172
1,0.952789,1.000000,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,...,0.683150,0.719652,0.769975,0.684826,0.696569,0.661825,0.630509,0.785825,0.644523,0.635172
2,0.952789,0.952789,1.000000,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,...,0.683150,0.719652,0.769975,0.684826,0.696569,0.661825,0.630509,0.785825,0.644523,0.635172
3,0.952789,0.952789,0.952789,1.000000,0.952789,0.952789,0.952789,0.952789,0.952789,0.952789,...,0.683150,0.719652,0.769975,0.684826,0.696569,0.661825,0.630509,0.785825,0.644523,0.635172
4,0.952789,0.952789,0.952789,0.952789,1.000000,0.952789,0.952789,0.952789,0.952789,0.952789,...,0.683150,0.719652,0.769975,0.684826,0.696569,0.661825,0.630509,0.785825,0.644523,0.635172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.661825,0.661825,0.661825,0.661825,0.661825,0.661825,0.661825,0.661825,0.661825,0.661825,...,0.610131,0.593718,0.655222,0.578311,0.595082,1.000000,0.626706,0.665872,0.614771,0.632927
76,0.630509,0.630509,0.630509,0.630509,0.630509,0.630509,0.630509,0.630509,0.630509,0.630509,...,0.606821,0.609094,0.615196,0.532935,0.622751,0.626706,1.000000,0.585796,0.562848,0.647298
77,0.785825,0.785825,0.785825,0.785825,0.785825,0.785825,0.785825,0.785825,0.785825,0.785825,...,0.721807,0.676169,0.711177,0.675287,0.695721,0.665872,0.585796,1.000000,0.652781,0.679375
78,0.644523,0.644523,0.644523,0.644523,0.644523,0.644523,0.644523,0.644523,0.644523,0.644523,...,0.629883,0.609835,0.598537,0.547744,0.621707,0.614771,0.562848,0.652781,1.000000,0.650748
79,0.635172,0.635172,0.635172,0.635172,0.635172,0.635172,0.635172,0.635172,0.635172,0.635172,...,0.602276,0.617215,0.617321,0.539904,0.655289,0.632927,0.647298,0.679375,0.650748,1.000000

===== mat5INV =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,...,0.613284,0.654569,0.642053,0.719133,0.659440,0.636931,0.635590,0.764884,0.648198,0.702211
1,0.900182,1.000000,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,...,0.613284,0.654569,0.642053,0.719133,0.659440,0.636931,0.635590,0.764884,0.648198,0.702211
2,0.900182,0.900182,1.000000,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,...,0.613284,0.654569,0.642053,0.719133,0.659440,0.636931,0.635590,0.764884,0.648198,0.702211
3,0.900182,0.900182,0.900182,1.000000,0.900182,0.900182,0.900182,0.900182,0.900182,0.900182,...,0.613284,0.654569,0.642053,0.719133,0.659440,0.636931,0.635590,0.764884,0.648198,0.702211
4,0.900182,0.900182,0.900182,0.900182,1.000000,0.900182,0.900182,0.900182,0.900182,0.900182,...,0.613284,0.654569,0.642053,0.719133,0.659440,0.636931,0.635590,0.764884,0.648198,0.702211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.636931,0.636931,0.636931,0.636931,0.636931,0.636931,0.636931,0.636931,0.636931,0.636931,...,0.604307,0.662010,0.564028,0.693358,0.683859,1.000000,0.655693,0.691666,0.593367,0.616510
76,0.635590,0.635590,0.635590,0.635590,0.635590,0.635590,0.635590,0.635590,0.635590,0.635590,...,0.608172,0.608899,0.580938,0.672283,0.704647,0.655693,1.000000,0.691037,0.570612,0.691105
77,0.764884,0.764884,0.764884,0.764884,0.764884,0.764884,0.764884,0.764884,0.764884,0.764884,...,0.630597,0.648870,0.646442,0.738086,0.769214,0.691666,0.691037,1.000000,0.624327,0.624505
78,0.648198,0.648198,0.648198,0.648198,0.648198,0.648198,0.648198,0.648198,0.648198,0.648198,...,0.521080,0.651517,0.697230,0.688214,0.670144,0.593367,0.570612,0.624327,1.000000,0.537465
79,0.702211,0.702211,0.702211,0.702211,0.702211,0.702211,0.702211,0.702211,0.702211,0.702211,...,0.645890,0.645063,0.632806,0.676763,0.633613,0.616510,0.691105,0.624505,0.537465,1.000000

===== mat6POUR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,...,0.551019,0.530052,0.552202,0.564262,0.627565,0.532997,0.586618,0.616055,0.529114,0.548128
1,0.688261,1.000000,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,...,0.551019,0.530052,0.552202,0.564262,0.627565,0.532997,0.586618,0.616055,0.529114,0.548128
2,0.688261,0.688261,1.000000,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,...,0.551019,0.530052,0.552202,0.564262,0.627565,0.532997,0.586618,0.616055,0.529114,0.548128
3,0.688261,0.688261,0.688261,1.000000,0.688261,0.688261,0.688261,0.688261,0.688261,0.688261,...,0.551019,0.530052,0.552202,0.564262,0.627565,0.532997,0.586618,0.616055,0.529114,0.548128
4,0.688261,0.688261,0.688261,0.688261,1.000000,0.688261,0.688261,0.688261,0.688261,0.688261,...,0.551019,0.530052,0.552202,0.564262,0.627565,0.532997,0.586618,0.616055,0.529114,0.548128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.532997,0.532997,0.532997,0.532997,0.532997,0.532997,0.532997,0.532997,0.532997,0.532997,...,0.538982,0.497918,0.483119,0.544881,0.588512,1.000000,0.529559,0.594672,0.531435,0.559675
76,0.586618,0.586618,0.586618,0.586618,0.586618,0.586618,0.586618,0.586618,0.586618,0.586618,...,0.612013,0.555154,0.512233,0.560929,0.612125,0.529559,1.000000,0.586693,0.556121,0.698802
77,0.616055,0.616055,0.616055,0.616055,0.616055,0.616055,0.616055,0.616055,0.616055,0.616055,...,0.588282,0.573424,0.584797,0.585275,0.636665,0.594672,0.586693,1.000000,0.605524,0.611778
78,0.529114,0.529114,0.529114,0.529114,0.529114,0.529114,0.529114,0.529114,0.529114,0.529114,...,0.540353,0.454143,0.540446,0.498023,0.566356,0.531435,0.556121,0.605524,1.000000,0.557672
79,0.548128,0.548128,0.548128,0.548128,0.548128,0.548128,0.548128,0.548128,0.548128,0.548128,...,0.615973,0.536872,0.528569,0.569623,0.599337,0.559675,0.698802,0.611778,0.557672,1.000000

===== mat7OR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,...,0.733279,0.718233,0.710196,0.737233,0.736736,0.680505,0.688861,0.706963,0.706288,0.709550
1,0.967649,1.000000,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,...,0.733279,0.718233,0.710196,0.737233,0.736736,0.680505,0.688861,0.706963,0.706288,0.709550
2,0.967649,0.967649,1.000000,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,...,0.733279,0.718233,0.710196,0.737233,0.736736,0.680505,0.688861,0.706963,0.706288,0.709550
3,0.967649,0.967649,0.967649,1.000000,0.967649,0.967649,0.967649,0.967649,0.967649,0.967649,...,0.733279,0.718233,0.710196,0.737233,0.736736,0.680505,0.688861,0.706963,0.706288,0.709550
4,0.967649,0.967649,0.967649,0.967649,1.000000,0.967649,0.967649,0.967649,0.967649,0.967649,...,0.733279,0.718233,0.710196,0.737233,0.736736,0.680505,0.688861,0.706963,0.706288,0.709550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.680505,0.680505,0.680505,0.680505,0.680505,0.680505,0.680505,0.680505,0.680505,0.680505,...,0.733750,0.645725,0.676761,0.729867,0.678662,1.000000,0.799179,0.735627,0.728793,0.753238
76,0.688861,0.688861,0.688861,0.688861,0.688861,0.688861,0.688861,0.688861,0.688861,0.688861,...,0.768015,0.710732,0.666523,0.751770,0.724982,0.799179,1.000000,0.778605,0.763807,0.796339
77,0.706963,0.706963,0.706963,0.706963,0.706963,0.706963,0.706963,0.706963,0.706963,0.706963,...,0.758326,0.749592,0.696434,0.765498,0.832278,0.735627,0.778605,1.000000,0.729853,0.823472
78,0.706288,0.706288,0.706288,0.706288,0.706288,0.706288,0.706288,0.706288,0.706288,0.706288,...,0.767054,0.657357,0.602129,0.689217,0.694352,0.728793,0.763807,0.729853,1.000000,0.737108
79,0.709550,0.709550,0.709550,0.709550,0.709550,0.709550,0.709550,0.709550,0.709550,0.709550,...,0.792344,0.681122,0.631629,0.737889,0.739806,0.753238,0.796339,0.823472,0.737108,1.000000

===== mat8ECCC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,...,0.660834,0.673881,0.769067,0.717573,0.729671,0.702686,0.626524,0.741567,0.689674,0.654161
1,0.938991,1.000000,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,...,0.660834,0.673881,0.769067,0.717573,0.729671,0.702686,0.626524,0.741567,0.689674,0.654161
2,0.938991,0.938991,1.000000,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,...,0.660834,0.673881,0.769067,0.717573,0.729671,0.702686,0.626524,0.741567,0.689674,0.654161
3,0.938991,0.938991,0.938991,1.000000,0.938991,0.938991,0.938991,0.938991,0.938991,0.938991,...,0.660834,0.673881,0.769067,0.717573,0.729671,0.702686,0.626524,0.741567,0.689674,0.654161
4,0.938991,0.938991,0.938991,0.938991,1.000000,0.938991,0.938991,0.938991,0.938991,0.938991,...,0.660834,0.673881,0.769067,0.717573,0.729671,0.702686,0.626524,0.741567,0.689674,0.654161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.702686,0.702686,0.702686,0.702686,0.702686,0.702686,0.702686,0.702686,0.702686,0.702686,...,0.595252,0.589154,0.672909,0.669780,0.591190,1.000000,0.628602,0.697186,0.663482,0.634113
76,0.626524,0.626524,0.626524,0.626524,0.626524,0.626524,0.626524,0.626524,0.626524,0.626524,...,0.597255,0.632525,0.633296,0.653893,0.596078,0.628602,1.000000,0.622654,0.591883,0.577213
77,0.741567,0.741567,0.741567,0.741567,0.741567,0.741567,0.741567,0.741567,0.741567,0.741567,...,0.611891,0.619773,0.708017,0.690914,0.634781,0.697186,0.622654,1.000000,0.599111,0.584166
78,0.689674,0.689674,0.689674,0.689674,0.689674,0.689674,0.689674,0.689674,0.689674,0.689674,...,0.590238,0.586359,0.671223,0.679788,0.610579,0.663482,0.591883,0.599111,1.000000,0.666333
79,0.654161,0.654161,0.654161,0.654161,0.654161,0.654161,0.654161,0.654161,0.654161,0.654161,...,0.574776,0.562748,0.658120,0.646121,0.578099,0.634113,0.577213,0.584166,0.666333,1.000000

===== mat9N =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,...,0.008935,0.899014,0.008935,0.904855,0.008821,0.016271,0.910281,0.906677,0.011963,0.173557
1,0.972853,1.000000,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,...,0.008935,0.899014,0.008935,0.904855,0.008821,0.016271,0.910281,0.906677,0.011963,0.173557
2,0.972853,0.972853,1.000000,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,...,0.008935,0.899013,0.008935,0.904855,0.008821,0.016271,0.910281,0.906677,0.011963,0.173556
3,0.972853,0.972853,0.972853,1.000000,0.972853,0.972853,0.972853,0.972853,0.972853,0.972853,...,0.008935,0.899014,0.008935,0.904855,0.008821,0.016271,0.910281,0.906677,0.011963,0.173557
4,0.972853,0.972853,0.972853,0.972853,1.000000,0.972853,0.972853,0.972853,0.972853,0.972853,...,0.008935,0.899014,0.008935,0.904855,0.008821,0.016271,0.910281,0.906677,0.011963,0.173557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.016271,0.016271,0.016271,0.016271,0.016271,0.016271,0.016271,0.016271,0.016271,0.016271,...,0.414750,0.079688,0.414750,0.028676,0.407051,1.000000,0.095405,0.151654,0.024986,0.093568
76,0.910281,0.910281,0.910281,0.910281,0.910281,0.910281,0.910281,0.910281,0.910281,0.910281,...,0.009856,0.962806,0.009856,0.973810,0.009627,0.095405,1.000000,0.949423,0.027338,0.131969
77,0.906677,0.906677,0.906677,0.906677,0.906677,0.906677,0.906677,0.906677,0.906677,0.906677,...,0.009445,0.968807,0.009445,0.949471,0.009245,0.151654,0.949423,1.000000,0.014252,0.067854
78,0.011963,0.011963,0.011963,0.011963,0.011963,0.011963,0.011963,0.011963,0.011963,0.011963,...,0.009216,0.108227,0.009216,0.020964,0.009237,0.024986,0.027338,0.014252,1.000000,0.199006
79,0.173557,0.173557,0.173556,0.173557,0.173557,0.173557,0.173557,0.173557,0.173557,0.173557,...,0.009198,0.133102,0.009198,0.149595,0.010130,0.093568,0.131969,0.067854,0.199006,1.000000

================================================================================
Question index = 1
Question Name = Easy P15288
k = 20
temperature_list = [0.0, 0.2, 0.5, 0.8]
analysis save dir = Questions/Easy P15288/CrossEncoder_Results/analysis
================================================================================

===== Overview Table =====

,matrix,offdiag_mean,offdiag_std,offdiag_min,offdiag_max,overall_within_mean,overall_cross_mean,within_minus_cross,prototype_idx,prototype_score,outlier_idx,outlier_score
0,mat1PI,0.741286,0.047630,0.580839,0.897887,0.754799,0.737008,0.017791,36,0.791768,46,0.680235
1,mat2FD,0.671017,0.055843,0.544923,0.866215,0.709755,0.658750,0.051004,24,0.731138,28,0.628860
2,mat3RC,0.665645,0.068349,0.423707,0.874042,0.698833,0.655136,0.043697,0,0.721526,66,0.583673
3,mat4MS,0.669439,0.090261,0.389983,0.952789,0.710232,0.656522,0.053710,39,0.749464,31,0.549581
4,mat5INV,0.682592,0.081812,0.447104,0.900182,0.718105,0.671347,0.046759,27,0.750856,53,0.577924
5,mat6POUR,0.584183,0.048459,0.453294,0.751072,0.605026,0.577583,0.027443,39,0.631613,64,0.518563
6,mat7OR,0.734073,0.075782,0.436913,0.967649,0.785568,0.717767,0.067801,0,0.772054,40,0.620553
7,mat8ECCC,0.690341,0.088717,0.454073,0.938991,0.719145,0.681220,0.037925,0,0.773896,25,0.597841
8,mat9N,0.360248,0.377897,0.008737,0.974466,0.514520,0.311395,0.203125,59,0.609582,45,0.071077

==============================
Matrix: mat1PI
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.741286      0.04763     0.580839     0.897887

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.833391,0.000000,0.833391,0.833391
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.748487,0.040753,0.637966,0.897683
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.720654,0.051433,0.589873,0.872684
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.716663,0.043841,0.613751,0.846098

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.764429  0.733422  0.737412
0.2  0.764429       NaN  0.734190  0.731411
0.5  0.733422  0.734190       NaN  0.721180
0.8  0.737412  0.731411  0.721180       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.036238  0.022939  0.033060
0.2  0.036238       NaN  0.043583  0.043275
0.5  0.022939  0.043583       NaN  0.050503
0.8  0.033060  0.043275  0.050503       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.754799            0.737008            0.017791

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             36          0.791768          0.2                   16
1             53          0.786032          0.5                   13
2             22          0.782919          0.2                    2
3             76          0.777536          0.8                   16
4             38          0.766462          0.2                   18
..           ...               ...          ...                  ...
75            55          0.696012          0.5                   15
76            42          0.694652          0.5                    2
77            35          0.692924          0.2                   15
78            77          0.687902          0.8                   17
79            46          0.680235          0.5                    6

[80 rows x 4 columns]

prototype_idx = 36, prototype_score = 0.791768
outlier_idx = 46, outlier_score = 0.680235


==============================
Matrix: mat2FD
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.671017     0.055843     0.544923     0.866215

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.781655,0.000000,0.781655,0.781655
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.702184,0.050158,0.599174,0.866215
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.681013,0.041331,0.555919,0.830389
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.674166,0.051115,0.547520,0.789219

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.637128  0.626590  0.624517
0.2  0.637128       NaN  0.693135  0.689169
0.5  0.626590  0.693135       NaN  0.681962
0.8  0.624517  0.689169  0.681962       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.029801  0.038709  0.020891
0.2  0.029801       NaN  0.043834  0.045551
0.5  0.038709  0.043834       NaN  0.044926
0.8  0.020891  0.045551  0.044926       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.709755             0.65875            0.051004

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             24          0.731138          0.2                    4
1             33          0.720472          0.2                   13
2             35          0.708866          0.2                   15
3             36          0.703031          0.2                   16
4             29          0.698247          0.2                    9
..           ...               ...          ...                  ...
75            72          0.639733          0.8                   12
76            71          0.638650          0.8                   11
77            44          0.636036          0.5                    4
78            73          0.631471          0.8                   13
79            28          0.628860          0.2                    8

[80 rows x 4 columns]

prototype_idx = 24, prototype_score = 0.731138
outlier_idx = 28, outlier_score = 0.628860


==============================
Matrix: mat3RC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.665645     0.068349     0.423707     0.874042

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.874042,0.000000,0.874042,0.874042
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.639402,0.042454,0.542518,0.819027
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.649818,0.048113,0.432926,0.784828
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.632071,0.046517,0.497536,0.787245

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.668361  0.672515  0.678812
0.2  0.668361       NaN  0.638634  0.630354
0.5  0.672515  0.638634       NaN  0.642140
0.8  0.678812  0.630354  0.642140       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.025992  0.033533  0.047109
0.2  0.025992       NaN  0.040306  0.042971
0.5  0.033533  0.040306       NaN  0.045449
0.8  0.047109  0.042971  0.045449       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.698833            0.655136            0.043697

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.721526          0.0                    0
1              1          0.721526          0.0                    1
2              2          0.721526          0.0                    2
3              3          0.721526          0.0                    3
4              4          0.721526          0.0                    4
..           ...               ...          ...                  ...
75            72          0.625568          0.8                   12
76            26          0.614793          0.2                    6
77            34          0.611042          0.2                   14
78            45          0.602993          0.5                    5
79            66          0.583673          0.8                    6

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.721526
outlier_idx = 66, outlier_score = 0.583673


==============================
Matrix: mat4MS
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.669439     0.090261     0.389983     0.952789

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.952789,0.000000,0.952789,0.952789
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.633388,0.060070,0.457746,0.772077
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.626891,0.045011,0.478978,0.753408
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.627859,0.046558,0.501486,0.731436

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.675840  0.691395  0.677053
0.2  0.675840       NaN  0.634084  0.633333
0.5  0.691395  0.634084       NaN  0.627424
0.8  0.677053  0.633333  0.627424       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.042332  0.051783  0.047855
0.2  0.042332       NaN  0.056769  0.060128
0.5  0.051783  0.056769       NaN  0.041459
0.8  0.047855  0.060128  0.041459       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.710232            0.656522             0.05371

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             39          0.749464          0.2                   19
1              0          0.746693          0.0                    0
2              2          0.746693          0.0                    2
3              1          0.746693          0.0                    1
4              4          0.746693          0.0                    4
..           ...               ...          ...                  ...
75            65          0.606242          0.8                    5
76            36          0.600386          0.2                   16
77            63          0.589117          0.8                    3
78            40          0.587559          0.5                    0
79            31          0.549581          0.2                   11

[80 rows x 4 columns]

prototype_idx = 39, prototype_score = 0.749464
outlier_idx = 31, outlier_score = 0.549581


==============================
Matrix: mat5INV
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.682592     0.081812     0.447104     0.900182

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.900182,0.000000,0.900182,0.900182
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.678152,0.073501,0.447104,0.885702
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.647465,0.056382,0.518816,0.775145
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.646622,0.055846,0.508213,0.825864

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.700353  0.679954  0.675892
0.2  0.700353       NaN  0.666096  0.660927
0.5  0.679954  0.666096       NaN  0.644858
0.8  0.675892  0.660927  0.644858       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.067729  0.046761  0.046485
0.2  0.067729       NaN  0.066587  0.064897
0.5  0.046761  0.066587       NaN  0.059219
0.8  0.046485  0.064897  0.059219       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.718105            0.671347            0.046759

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             27          0.750856          0.2                    7
1              0          0.737056          0.0                    0
2              2          0.737056          0.0                    2
3              1          0.737056          0.0                    1
4              4          0.737056          0.0                    4
..           ...               ...          ...                  ...
75            70          0.613330          0.8                   10
76            64          0.610140          0.8                    4
77            21          0.609745          0.2                    1
78            46          0.588997          0.5                    6
79            53          0.577924          0.5                   13

[80 rows x 4 columns]

prototype_idx = 27, prototype_score = 0.750856
outlier_idx = 53, outlier_score = 0.577924


==============================
Matrix: mat6POUR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.584183     0.048459     0.453294     0.751072

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.688261,0.000000,0.688261,0.688261
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.582917,0.038736,0.506715,0.698768
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.583670,0.044248,0.491992,0.748681
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.565256,0.050291,0.453294,0.704571

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.573908  0.575234  0.565289
0.2  0.573908       NaN  0.583726  0.581002
0.5  0.575234  0.583726       NaN  0.586339
0.8  0.565289  0.581002  0.586339       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.043551  0.033147  0.034371
0.2  0.043551       NaN  0.040803  0.041650
0.5  0.033147  0.040803       NaN  0.047506
0.8  0.034371  0.041650  0.047506       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.605026            0.577583            0.027443

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             39          0.631613          0.2                   19
1             42          0.623008          0.5                    2
2             74          0.622891          0.8                   14
3             47          0.618253          0.5                    7
4             27          0.615922          0.2                    7
..           ...               ...          ...                  ...
75            75          0.545839          0.8                   15
76            78          0.545463          0.8                   18
77            44          0.543168          0.5                    4
78            66          0.531626          0.8                    6
79            64          0.518563          0.8                    4

[80 rows x 4 columns]

prototype_idx = 39, prototype_score = 0.631613
outlier_idx = 64, outlier_score = 0.518563


==============================
Matrix: mat7OR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.734073     0.075782     0.436913     0.967649

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.967649,0.000000,0.967649,0.967649
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.739476,0.063142,0.515910,0.938231
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.706458,0.055194,0.495069,0.890982
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.728688,0.055340,0.556773,0.882981

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.710766  0.704713  0.714870
0.2  0.710766       NaN  0.721856  0.734486
0.5  0.704713  0.721856       NaN  0.719911
0.8  0.714870  0.734486  0.719911       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.012121  0.025011  0.018865
0.2  0.012121       NaN  0.058122  0.062883
0.5  0.025011  0.058122       NaN  0.060699
0.8  0.018865  0.062883  0.060699       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.785568            0.717767            0.067801

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.772054          0.0                    0
1              1          0.772054          0.0                    1
2              2          0.772054          0.0                    2
3              3          0.772054          0.0                    3
4              4          0.772054          0.0                    4
..           ...               ...          ...                  ...
75            44          0.688230          0.5                    4
76            50          0.680514          0.5                   10
77            72          0.680478          0.8                   12
78            66          0.649574          0.8                    6
79            40          0.620553          0.5                    0

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.772054
outlier_idx = 40, outlier_score = 0.620553


==============================
Matrix: mat8ECCC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.690341     0.088717     0.454073     0.938991

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.938991,0.000000,0.938991,0.938991
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.627051,0.050501,0.454073,0.744870
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.667250,0.058509,0.479259,0.834579
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.643287,0.043145,0.539045,0.736299

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.719788  0.735695  0.709364
0.2  0.719788       NaN  0.636522  0.628973
0.5  0.735695  0.636522       NaN  0.656976
0.8  0.709364  0.628973  0.656976       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.037584  0.045200  0.049370
0.2  0.037584       NaN  0.055868  0.053194
0.5  0.045200  0.055868       NaN  0.054547
0.8  0.049370  0.053194  0.054547       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.719145             0.68122            0.037925

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.773896          0.0                    0
1              1          0.773896          0.0                    1
2              2          0.773896          0.0                    2
3              3          0.773896          0.0                    3
4              4          0.773896          0.0                    4
..           ...               ...          ...                  ...
75            31          0.620772          0.2                   11
76            50          0.618099          0.5                   10
77            67          0.612130          0.8                    7
78            36          0.604229          0.2                   16
79            25          0.597841          0.2                    5

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.773896
outlier_idx = 25, outlier_score = 0.597841


==============================
Matrix: mat9N
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.360248     0.377897     0.008737     0.974466

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.972853,0.000000,0.972853,0.972853
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.390957,0.387925,0.008788,0.967762
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.404832,0.330439,0.008737,0.968084
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.289437,0.332133,0.009000,0.973810

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.291378  0.206816  0.273133
0.2  0.291378       NaN  0.409393  0.339809
0.5  0.206816  0.409393       NaN  0.347842
0.8  0.273133  0.339809  0.347842       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.377971  0.304323  0.378172
0.2  0.377971       NaN  0.357759  0.344004
0.5  0.304323  0.357759       NaN  0.326666
0.8  0.378172  0.344004  0.326666       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0              0.51452            0.311395            0.203125

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             59          0.609582          0.5                   19
1             26          0.512180          0.2                    6
2             58          0.511785          0.5                   18
3             21          0.509313          0.2                    1
4             69          0.499541          0.8                    9
..           ...               ...          ...                  ...
75            47          0.105453          0.5                    7
76            50          0.098342          0.5                   10
77            78          0.081414          0.8                   18
78            23          0.072550          0.2                    3
79            45          0.071077          0.5                    5

[80 rows x 4 columns]

prototype_idx = 59, prototype_score = 0.609582
outlier_idx = 45, outlier_score = 0.071077


####################################################################################################
Processing question 2/17: Easy P15457
####################################################################################################

================================================================================
题目 index = 2
题目名称 = Easy P15457
矩阵保存目录 = Questions/Easy P15457/CrossEncoder_Results/matrices
================================================================================

===== mat1PI =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,...,0.724953,0.680460,0.709982,0.707757,0.680531,0.701454,0.711983,0.740332,0.742170,0.676735
1,0.724459,1.000000,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,...,0.724953,0.680460,0.709982,0.707757,0.680531,0.701454,0.711983,0.740332,0.742170,0.676735
2,0.724459,0.724459,1.000000,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,...,0.724953,0.680460,0.709982,0.707757,0.680531,0.701454,0.711983,0.740332,0.742170,0.676735
3,0.724459,0.724459,0.724459,1.000000,0.724459,0.724459,0.724459,0.724459,0.724459,0.724459,...,0.724953,0.680460,0.709982,0.707757,0.680531,0.701454,0.711983,0.740332,0.742170,0.676735
4,0.724459,0.724459,0.724459,0.724459,1.000000,0.724459,0.724459,0.724459,0.724459,0.724459,...,0.724953,0.680460,0.709982,0.707757,0.680531,0.701454,0.711983,0.740332,0.742170,0.676735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.701454,0.701454,0.701454,0.701454,0.701454,0.701454,0.701454,0.701454,0.701454,0.701454,...,0.702524,0.698310,0.767975,0.778100,0.697571,1.000000,0.768479,0.739701,0.795584,0.711323
76,0.711983,0.711983,0.711983,0.711983,0.711983,0.711983,0.711983,0.711983,0.711983,0.711983,...,0.677048,0.724392,0.827194,0.731837,0.738243,0.768479,1.000000,0.779477,0.756757,0.663983
77,0.740332,0.740332,0.740332,0.740332,0.740332,0.740332,0.740332,0.740332,0.740332,0.740332,...,0.713706,0.705567,0.804211,0.776360,0.735507,0.739701,0.779477,1.000000,0.796045,0.750768
78,0.742170,0.742170,0.742170,0.742170,0.742170,0.742170,0.742170,0.742170,0.742170,0.742170,...,0.729513,0.739615,0.854612,0.767113,0.749490,0.795584,0.756757,0.796045,1.000000,0.723187
79,0.676735,0.676735,0.676735,0.676735,0.676735,0.676735,0.676735,0.676735,0.676735,0.676735,...,0.653828,0.709192,0.775793,0.682198,0.704537,0.711323,0.663983,0.750768,0.723187,1.000000

===== mat2FD =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,...,0.810915,0.756297,0.795547,0.785934,0.798627,0.750594,0.737489,0.813335,0.840505,0.748698
1,0.953927,1.000000,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,...,0.810915,0.756297,0.795547,0.785934,0.798627,0.750594,0.737489,0.813335,0.840505,0.748698
2,0.953927,0.953927,1.000000,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,...,0.810915,0.756297,0.795547,0.785934,0.798627,0.750594,0.737489,0.813335,0.840505,0.748698
3,0.953927,0.953927,0.953927,1.000000,0.953927,0.953927,0.953927,0.953927,0.953927,0.953927,...,0.810915,0.756297,0.795547,0.785934,0.798627,0.750594,0.737489,0.813335,0.840505,0.748698
4,0.953927,0.953927,0.953927,0.953927,1.000000,0.953927,0.953927,0.953927,0.953927,0.953927,...,0.810915,0.756297,0.795547,0.785934,0.798627,0.750594,0.737489,0.813335,0.840505,0.748698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.750594,0.750594,0.750594,0.750594,0.750594,0.750594,0.750594,0.750594,0.750594,0.750594,...,0.718861,0.780026,0.714945,0.731642,0.685870,1.000000,0.693906,0.685242,0.659275,0.733589
76,0.737489,0.737489,0.737489,0.737489,0.737489,0.737489,0.737489,0.737489,0.737489,0.737489,...,0.710844,0.711914,0.708362,0.731799,0.658239,0.693906,1.000000,0.702586,0.758713,0.662763
77,0.813335,0.813335,0.813335,0.813335,0.813335,0.813335,0.813335,0.813335,0.813335,0.813335,...,0.750993,0.764662,0.786246,0.758320,0.719740,0.685242,0.702586,1.000000,0.706883,0.717774
78,0.840505,0.840505,0.840505,0.840505,0.840505,0.840505,0.840505,0.840505,0.840505,0.840505,...,0.719403,0.760542,0.808080,0.798194,0.728122,0.659275,0.758713,0.706883,1.000000,0.723871
79,0.748698,0.748698,0.748698,0.748698,0.748698,0.748698,0.748698,0.748698,0.748698,0.748698,...,0.754347,0.754226,0.772896,0.795939,0.716458,0.733589,0.662763,0.717774,0.723871,1.000000

===== mat3RC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,...,0.551962,0.592690,0.657983,0.580377,0.564964,0.647219,0.601655,0.602188,0.604911,0.577241
1,0.855020,1.000000,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,...,0.551962,0.592690,0.657983,0.580377,0.564964,0.647219,0.601655,0.602188,0.604911,0.577241
2,0.855020,0.855020,1.000000,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,...,0.551962,0.592690,0.657983,0.580377,0.564964,0.647219,0.601655,0.602188,0.604911,0.577241
3,0.855020,0.855020,0.855020,1.000000,0.855020,0.855020,0.855020,0.855020,0.855020,0.855020,...,0.551962,0.592690,0.657983,0.580377,0.564964,0.647219,0.601655,0.602188,0.604911,0.577241
4,0.855020,0.855020,0.855020,0.855020,1.000000,0.855020,0.855020,0.855020,0.855020,0.855020,...,0.551962,0.592690,0.657983,0.580377,0.564964,0.647219,0.601655,0.602188,0.604911,0.577241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.647219,0.647219,0.647219,0.647219,0.647219,0.647219,0.647219,0.647219,0.647219,0.647219,...,0.684650,0.629823,0.683088,0.667109,0.668309,1.000000,0.645463,0.671126,0.642543,0.635129
76,0.601655,0.601655,0.601655,0.601655,0.601655,0.601655,0.601655,0.601655,0.601655,0.601655,...,0.589128,0.532143,0.634123,0.623318,0.618738,0.645463,1.000000,0.564731,0.646715,0.630642
77,0.602188,0.602188,0.602188,0.602188,0.602188,0.602188,0.602188,0.602188,0.602188,0.602188,...,0.750691,0.539711,0.662010,0.731068,0.719230,0.671126,0.564731,1.000000,0.595279,0.638749
78,0.604911,0.604911,0.604911,0.604911,0.604911,0.604911,0.604911,0.604911,0.604911,0.604911,...,0.584327,0.647244,0.646579,0.600466,0.594945,0.642543,0.646715,0.595279,1.000000,0.576994
79,0.577241,0.577241,0.577241,0.577241,0.577241,0.577241,0.577241,0.577241,0.577241,0.577241,...,0.617437,0.601731,0.683937,0.663399,0.648195,0.635129,0.630642,0.638749,0.576994,1.000000

===== mat4MS =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,...,0.647141,0.591362,0.691486,0.674438,0.689306,0.584853,0.656464,0.705292,0.581468,0.597708
1,0.872133,1.000000,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,...,0.647141,0.591362,0.691486,0.674438,0.689306,0.584853,0.656464,0.705292,0.581468,0.597708
2,0.872133,0.872133,1.000000,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,...,0.647141,0.591362,0.691486,0.674438,0.689306,0.584853,0.656464,0.705292,0.581468,0.597708
3,0.872133,0.872133,0.872133,1.000000,0.872133,0.872133,0.872133,0.872133,0.872133,0.872133,...,0.647141,0.591362,0.691486,0.674438,0.689306,0.584853,0.656464,0.705292,0.581468,0.597708
4,0.872133,0.872133,0.872133,0.872133,1.000000,0.872133,0.872133,0.872133,0.872133,0.872133,...,0.647141,0.591362,0.691486,0.674438,0.689306,0.584853,0.656464,0.705292,0.581468,0.597708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.584853,0.584853,0.584853,0.584853,0.584853,0.584853,0.584853,0.584853,0.584853,0.584853,...,0.637076,0.582651,0.564797,0.633806,0.598096,1.000000,0.534815,0.516003,0.512180,0.504202
76,0.656464,0.656464,0.656464,0.656464,0.656464,0.656464,0.656464,0.656464,0.656464,0.656464,...,0.612122,0.557389,0.652117,0.654754,0.630073,0.534815,1.000000,0.667742,0.616298,0.596131
77,0.705292,0.705292,0.705292,0.705292,0.705292,0.705292,0.705292,0.705292,0.705292,0.705292,...,0.608402,0.575721,0.696877,0.669909,0.671097,0.516003,0.667742,1.000000,0.597749,0.612583
78,0.581468,0.581468,0.581468,0.581468,0.581468,0.581468,0.581468,0.581468,0.581468,0.581468,...,0.604242,0.531458,0.599658,0.554524,0.635680,0.512180,0.616298,0.597749,1.000000,0.583840
79,0.597708,0.597708,0.597708,0.597708,0.597708,0.597708,0.597708,0.597708,0.597708,0.597708,...,0.554562,0.537825,0.612286,0.576096,0.582204,0.504202,0.596131,0.612583,0.583840,1.000000

===== mat5INV =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,...,0.655655,0.631307,0.606755,0.707095,0.713551,0.587282,0.683685,0.786710,0.614041,0.639042
1,0.953184,1.000000,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,...,0.655655,0.631307,0.606755,0.707095,0.713551,0.587282,0.683685,0.786710,0.614041,0.639042
2,0.953184,0.953184,1.000000,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,...,0.655655,0.631307,0.606755,0.707095,0.713551,0.587282,0.683685,0.786710,0.614041,0.639042
3,0.953184,0.953184,0.953184,1.000000,0.953184,0.953184,0.953184,0.953184,0.953184,0.953184,...,0.655655,0.631307,0.606755,0.707095,0.713551,0.587282,0.683685,0.786710,0.614041,0.639042
4,0.953184,0.953184,0.953184,0.953184,1.000000,0.953184,0.953184,0.953184,0.953184,0.953184,...,0.655655,0.631307,0.606755,0.707095,0.713551,0.587282,0.683685,0.786710,0.614041,0.639042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.587282,0.587282,0.587282,0.587282,0.587282,0.587282,0.587282,0.587282,0.587282,0.587282,...,0.600467,0.615541,0.571401,0.612831,0.524950,1.000000,0.588671,0.587921,0.573211,0.552885
76,0.683685,0.683685,0.683685,0.683685,0.683685,0.683685,0.683685,0.683685,0.683685,0.683685,...,0.665715,0.674769,0.604843,0.669881,0.852994,0.588671,1.000000,0.745339,0.687764,0.678345
77,0.786710,0.786710,0.786710,0.786710,0.786710,0.786710,0.786710,0.786710,0.786710,0.786710,...,0.654145,0.696943,0.608684,0.676013,0.680870,0.587921,0.745339,1.000000,0.733891,0.705514
78,0.614041,0.614041,0.614041,0.614041,0.614041,0.614041,0.614041,0.614041,0.614041,0.614041,...,0.617454,0.682023,0.576602,0.595265,0.585391,0.573211,0.687764,0.733891,1.000000,0.623098
79,0.639042,0.639042,0.639042,0.639042,0.639042,0.639042,0.639042,0.639042,0.639042,0.639042,...,0.624464,0.686791,0.620370,0.610148,0.595204,0.552885,0.678345,0.705514,0.623098,1.000000

===== mat6POUR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,...,0.593718,0.658074,0.613638,0.695993,0.641248,0.553638,0.593172,0.687861,0.610703,0.618113
1,0.763544,1.000000,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,...,0.593718,0.658074,0.613638,0.695993,0.641248,0.553638,0.593172,0.687861,0.610703,0.618113
2,0.763544,0.763544,1.000000,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,...,0.593718,0.658074,0.613638,0.695993,0.641248,0.553638,0.593172,0.687861,0.610703,0.618113
3,0.763544,0.763544,0.763544,1.000000,0.763544,0.763544,0.763544,0.763544,0.763544,0.763544,...,0.593718,0.658074,0.613638,0.695993,0.641248,0.553638,0.593172,0.687861,0.610703,0.618113
4,0.763544,0.763544,0.763544,0.763544,1.000000,0.763544,0.763544,0.763544,0.763544,0.763544,...,0.593718,0.658074,0.613638,0.695993,0.641248,0.553638,0.593172,0.687861,0.610703,0.618113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.553638,0.553638,0.553638,0.553638,0.553638,0.553638,0.553638,0.553638,0.553638,0.553638,...,0.589746,0.650005,0.573220,0.648481,0.620124,1.000000,0.557976,0.555922,0.573660,0.575354
76,0.593172,0.593172,0.593172,0.593172,0.593172,0.593172,0.593172,0.593172,0.593172,0.593172,...,0.608247,0.675773,0.587629,0.687075,0.588065,0.557976,1.000000,0.654942,0.599827,0.595957
77,0.687861,0.687861,0.687861,0.687861,0.687861,0.687861,0.687861,0.687861,0.687861,0.687861,...,0.642177,0.650227,0.625785,0.698615,0.622278,0.555922,0.654942,1.000000,0.604508,0.627016
78,0.610703,0.610703,0.610703,0.610703,0.610703,0.610703,0.610703,0.610703,0.610703,0.610703,...,0.666507,0.671957,0.591105,0.645367,0.634009,0.573660,0.599827,0.604508,1.000000,0.620580
79,0.618113,0.618113,0.618113,0.618113,0.618113,0.618113,0.618113,0.618113,0.618113,0.618113,...,0.648657,0.658027,0.605220,0.656332,0.649554,0.575354,0.595957,0.627016,0.620580,1.000000

===== mat7OR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,...,0.744587,0.714183,0.817471,0.726316,0.676933,0.580043,0.656459,0.688279,0.694474,0.619287
1,0.965986,1.000000,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,...,0.744587,0.714183,0.817471,0.726316,0.676933,0.580043,0.656459,0.688279,0.694474,0.619287
2,0.965986,0.965986,1.000000,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,...,0.744587,0.714183,0.817471,0.726316,0.676933,0.580043,0.656459,0.688279,0.694474,0.619287
3,0.965986,0.965986,0.965986,1.000000,0.965986,0.965986,0.965986,0.965986,0.965986,0.965986,...,0.744587,0.714183,0.817471,0.726316,0.676933,0.580043,0.656459,0.688279,0.694474,0.619287
4,0.965986,0.965986,0.965986,0.965986,1.000000,0.965986,0.965986,0.965986,0.965986,0.965986,...,0.744587,0.714183,0.817471,0.726316,0.676933,0.580043,0.656459,0.688279,0.694474,0.619287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.580043,0.580043,0.580043,0.580043,0.580043,0.580043,0.580043,0.580043,0.580043,0.580043,...,0.650282,0.677215,0.697417,0.564665,0.684596,1.000000,0.541680,0.457051,0.675440,0.660100
76,0.656459,0.656459,0.656459,0.656459,0.656459,0.656459,0.656459,0.656459,0.656459,0.656459,...,0.657847,0.626901,0.666323,0.550079,0.714219,0.541680,1.000000,0.653255,0.631053,0.593846
77,0.688279,0.688279,0.688279,0.688279,0.688279,0.688279,0.688279,0.688279,0.688279,0.688279,...,0.621067,0.567813,0.702852,0.633431,0.683646,0.457051,0.653255,1.000000,0.608886,0.549568
78,0.694474,0.694474,0.694474,0.694474,0.694474,0.694474,0.694474,0.694474,0.694474,0.694474,...,0.684722,0.748282,0.678118,0.695465,0.733704,0.675440,0.631053,0.608886,1.000000,0.703080
79,0.619287,0.619287,0.619287,0.619287,0.619287,0.619287,0.619287,0.619287,0.619287,0.619287,...,0.577049,0.683528,0.663429,0.610833,0.664604,0.660100,0.593846,0.549568,0.703080,1.000000

===== mat8ECCC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,...,0.652333,0.831050,0.716111,0.646191,0.521547,0.580742,0.783936,0.739779,0.796671,0.636794
1,0.479259,1.000000,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,...,0.652333,0.831050,0.716111,0.646191,0.521547,0.580742,0.783936,0.739779,0.796671,0.636794
2,0.479259,0.479259,1.000000,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,...,0.652333,0.831050,0.716111,0.646191,0.521547,0.580742,0.783936,0.739779,0.796671,0.636794
3,0.479259,0.479259,0.479259,1.000000,0.479259,0.479259,0.479259,0.479259,0.479259,0.479259,...,0.652333,0.831050,0.716111,0.646191,0.521547,0.580742,0.783936,0.739779,0.796671,0.636794
4,0.479259,0.479259,0.479259,0.479259,1.000000,0.479259,0.479259,0.479259,0.479259,0.479259,...,0.652333,0.831050,0.716111,0.646191,0.521547,0.580742,0.783936,0.739779,0.796671,0.636794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.580742,0.580742,0.580742,0.580742,0.580742,0.580742,0.580742,0.580742,0.580742,0.580742,...,0.589996,0.723890,0.650058,0.598112,0.555998,1.000000,0.633038,0.665601,0.661383,0.592370
76,0.783936,0.783936,0.783936,0.783936,0.783936,0.783936,0.783936,0.783936,0.783936,0.783936,...,0.648951,0.823527,0.716268,0.625247,0.588202,0.633038,1.000000,0.714565,0.750562,0.628785
77,0.739779,0.739779,0.739779,0.739779,0.739779,0.739779,0.739779,0.739779,0.739779,0.739779,...,0.675395,0.822385,0.723763,0.645389,0.644771,0.665601,0.714565,1.000000,0.749414,0.639273
78,0.796671,0.796671,0.796671,0.796671,0.796671,0.796671,0.796671,0.796671,0.796671,0.796671,...,0.673267,0.825576,0.689079,0.658911,0.648691,0.661383,0.750562,0.749414,1.000000,0.697098
79,0.636794,0.636794,0.636794,0.636794,0.636794,0.636794,0.636794,0.636794,0.636794,0.636794,...,0.576315,0.708108,0.643036,0.590928,0.531162,0.592370,0.628785,0.639273,0.697098,1.000000

===== mat9N =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,...,0.639047,0.630647,0.596697,0.609082,0.627285,0.629718,0.597138,0.633717,0.635994,0.625667
1,0.726676,1.000000,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,...,0.639047,0.630647,0.596697,0.609082,0.627285,0.629718,0.597138,0.633717,0.635994,0.625667
2,0.726676,0.726676,1.000000,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,...,0.639047,0.630647,0.596697,0.609082,0.627285,0.629718,0.597138,0.633717,0.635994,0.625667
3,0.726676,0.726676,0.726676,1.000000,0.726676,0.726676,0.726676,0.726676,0.726676,0.726676,...,0.639047,0.630647,0.596697,0.609082,0.627285,0.629718,0.597138,0.633717,0.635994,0.625667
4,0.726676,0.726676,0.726676,0.726676,1.000000,0.726676,0.726676,0.726676,0.726676,0.726676,...,0.639047,0.630647,0.596697,0.609082,0.627285,0.629718,0.597138,0.633717,0.635994,0.625667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.629718,0.629718,0.629718,0.629718,0.629718,0.629718,0.629718,0.629718,0.629718,0.629718,...,0.369212,0.289143,0.232779,0.253757,0.275473,1.000000,0.535367,0.312410,0.324068,0.318791
76,0.597138,0.597138,0.597138,0.597138,0.597138,0.597138,0.597138,0.597138,0.597138,0.597138,...,0.527953,0.510437,0.594980,0.509506,0.501939,0.535367,1.000000,0.507781,0.501150,0.498922
77,0.633717,0.633717,0.633717,0.633717,0.633717,0.633717,0.633717,0.633717,0.633717,0.633717,...,0.266448,0.918606,0.095674,0.942009,0.910813,0.312410,0.507781,1.000000,0.719415,0.765539
78,0.635994,0.635994,0.635994,0.635994,0.635994,0.635994,0.635994,0.635994,0.635994,0.635994,...,0.042920,0.745556,0.100399,0.794006,0.786028,0.324068,0.501150,0.719415,1.000000,0.887715
79,0.625667,0.625667,0.625667,0.625667,0.625667,0.625667,0.625667,0.625667,0.625667,0.625667,...,0.246141,0.768039,0.120015,0.816154,0.794789,0.318791,0.498922,0.765539,0.887715,1.000000

================================================================================
Question index = 2
Question Name = Easy P15457
k = 20
temperature_list = [0.0, 0.2, 0.5, 0.8]
analysis save dir = Questions/Easy P15457/CrossEncoder_Results/analysis
================================================================================

===== Overview Table =====

,matrix,offdiag_mean,offdiag_std,offdiag_min,offdiag_max,overall_within_mean,overall_cross_mean,within_minus_cross,prototype_idx,prototype_score,outlier_idx,outlier_score
0,mat1PI,0.727356,0.045101,0.613700,0.909187,0.740240,0.723276,0.016964,25,0.794368,22,0.683074
1,mat2FD,0.769316,0.077125,0.563835,0.953927,0.792348,0.762023,0.030326,0,0.831784,61,0.670056
2,mat3RC,0.674298,0.105738,0.485623,0.963537,0.745007,0.651907,0.093100,32,0.725320,71,0.578458
3,mat4MS,0.679881,0.069616,0.503964,0.872133,0.710598,0.670154,0.040445,0,0.727638,71,0.586874
4,mat5INV,0.698804,0.085033,0.512083,0.953184,0.740335,0.685653,0.054683,0,0.760713,32,0.590171
5,mat6POUR,0.628158,0.052235,0.474508,0.769167,0.649364,0.621443,0.027921,52,0.665933,64,0.560493
6,mat7OR,0.733341,0.090474,0.452711,0.965986,0.763437,0.723810,0.039626,0,0.802913,75,0.611074
7,mat8ECCC,0.626139,0.082410,0.419640,0.831050,0.599362,0.634619,-0.035257,71,0.739056,67,0.533986
8,mat9N,0.577605,0.216139,0.008764,0.974466,0.577488,0.577643,-0.000155,40,0.658489,64,0.290163

==============================
Matrix: mat1PI
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.727356     0.045101       0.6137     0.909187

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.724459,0.000000,0.724459,0.724459
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.743513,0.050047,0.635002,0.862619
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.752659,0.044890,0.640655,0.884880
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.740329,0.045634,0.620157,0.866474

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.700125  0.708410  0.703151
0.2  0.700125       NaN  0.741301  0.740017
0.5  0.708410  0.741301       NaN  0.746652
0.8  0.703151  0.740017  0.746652       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.028072  0.032042  0.035238
0.2  0.028072       NaN  0.048681  0.051241
0.5  0.032042  0.048681       NaN  0.044230
0.8  0.035238  0.051241  0.044230       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0              0.74024            0.723276            0.016964

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             25          0.794368          0.2                    5
1             55          0.782149          0.5                   15
2             60          0.774842          0.8                    0
3             78          0.773628          0.8                   18
4             31          0.772022          0.2                   11
..           ...               ...          ...                  ...
75            30          0.696561          0.2                   10
76            69          0.692426          0.8                    9
77            61          0.691658          0.8                    1
78            36          0.687159          0.2                   16
79            22          0.683074          0.2                    2

[80 rows x 4 columns]

prototype_idx = 25, prototype_score = 0.794368
outlier_idx = 22, outlier_score = 0.683074


==============================
Matrix: mat2FD
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.769316     0.077125     0.563835     0.953927

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.953927,0.000000,0.953927,0.953927
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.748507,0.061037,0.631022,0.910616
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.740567,0.054527,0.602252,0.917925
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.726393,0.045642,0.626309,0.850158

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.807137  0.796440  0.775738
0.2  0.807137       NaN  0.734870  0.724939
0.5  0.796440  0.734870       NaN  0.733012
0.8  0.775738  0.724939  0.733012       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.059748  0.053473  0.037068
0.2  0.059748       NaN  0.064787  0.057552
0.5  0.053473  0.064787       NaN  0.056248
0.8  0.037068  0.057552  0.056248       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.792348            0.762023            0.030326

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.831784          0.0                    0
1              1          0.831784          0.0                    1
2              2          0.831784          0.0                    2
3              3          0.831784          0.0                    3
4              4          0.831784          0.0                    4
..           ...               ...          ...                  ...
75            21          0.695199          0.2                    1
76            47          0.693444          0.5                    7
77            59          0.689253          0.5                   19
78            39          0.678359          0.2                   19
79            61          0.670056          0.8                    1

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.831784
outlier_idx = 61, outlier_score = 0.670056


==============================
Matrix: mat3RC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.674298     0.105738     0.485623     0.963537

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.855020,0.000000,0.855020,0.855020
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.741293,0.097053,0.594336,0.961909
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.728203,0.107997,0.518711,0.951447
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.655511,0.080241,0.503934,0.954201

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.600831  0.592748  0.594048
0.2  0.600831       NaN  0.737089  0.694706
0.5  0.592748  0.737089       NaN  0.692021
0.8  0.594048  0.694706  0.692021       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.033866  0.031021  0.041026
0.2  0.033866       NaN  0.109382  0.091662
0.5  0.031021  0.109382       NaN  0.093490
0.8  0.041026  0.091662  0.093490       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.745007            0.651907              0.0931

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             32          0.725320          0.2                   12
1             35          0.725281          0.2                   15
2             41          0.725216          0.5                    1
3             38          0.724913          0.2                   18
4             33          0.724649          0.2                   13
..           ...               ...          ...                  ...
75            44          0.606765          0.5                    4
76            78          0.605599          0.8                   18
77            22          0.603978          0.2                    2
78            40          0.596408          0.5                    0
79            71          0.578458          0.8                   11

[80 rows x 4 columns]

prototype_idx = 32, prototype_score = 0.725320
outlier_idx = 71, outlier_score = 0.578458


==============================
Matrix: mat4MS
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.679881     0.069616     0.503964     0.872133

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.872133,0.000000,0.872133,0.872133
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.665239,0.055236,0.517250,0.832250
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.685976,0.048798,0.572370,0.830523
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.619046,0.051001,0.504202,0.739861

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.694730  0.695564  0.655349
0.2  0.694730       NaN  0.671767  0.644942
0.5  0.695564  0.671767       NaN  0.658571
0.8  0.655349  0.644942  0.658571       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.032406  0.031120  0.039927
0.2  0.032406       NaN  0.054693  0.055527
0.5  0.031120  0.054693       NaN  0.050409
0.8  0.039927  0.055527  0.050409       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.710598            0.670154            0.040445

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.727638          0.0                    0
1              1          0.727638          0.0                    1
2              2          0.727638          0.0                    2
3              3          0.727638          0.0                    3
4              4          0.727638          0.0                    4
..           ...               ...          ...                  ...
75            35          0.604744          0.2                   15
76            78          0.594983          0.8                   18
77            79          0.594377          0.8                   19
78            75          0.591644          0.8                   15
79            71          0.586874          0.8                   11

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.727638
outlier_idx = 71, outlier_score = 0.586874


==============================
Matrix: mat5INV
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.698804     0.085033     0.512083     0.953184

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.953184,0.000000,0.953184,0.953184
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.686088,0.053718,0.541014,0.838685
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.676755,0.060150,0.531654,0.826252
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.645314,0.059803,0.512083,0.852994

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.711504  0.701639  0.686150
0.2  0.711504       NaN  0.684136  0.666149
0.5  0.701639  0.684136       NaN  0.664339
0.8  0.686150  0.666149  0.664339       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.045544  0.046991  0.056646
0.2  0.045544       NaN  0.053061  0.054173
0.5  0.046991  0.053061       NaN  0.062373
0.8  0.056646  0.054173  0.062373       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.740335            0.685653            0.054683

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.760713          0.0                    0
1              1          0.760713          0.0                    1
2              2          0.760713          0.0                    2
3              3          0.760713          0.0                    3
4              4          0.760713          0.0                    4
..           ...               ...          ...                  ...
75            78          0.626171          0.8                   18
76            55          0.621355          0.5                   15
77            72          0.614215          0.8                   12
78            75          0.591283          0.8                   15
79            32          0.590171          0.2                   12

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.760713
outlier_idx = 32, outlier_score = 0.590171


==============================
Matrix: mat6POUR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.628158     0.052235     0.474508     0.769167

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.763544,0.000000,0.763544,0.763544
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.615699,0.037699,0.493767,0.705432
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.601697,0.041994,0.498641,0.747464
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.616515,0.043668,0.526853,0.730035

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.632705  0.627591  0.631743
0.2  0.632705       NaN  0.610220  0.612921
0.5  0.627591  0.610220       NaN  0.613476
0.8  0.631743  0.612921  0.613476       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.026950  0.036376  0.037452
0.2  0.026950       NaN  0.040942  0.043013
0.5  0.036376  0.040942       NaN  0.046662
0.8  0.037452  0.043013  0.046662       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.649364            0.621443            0.027921

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             52          0.665933          0.5                   12
1             73          0.664474          0.8                   13
2              0          0.662634          0.0                    0
3              1          0.662634          0.0                    1
4              4          0.662634          0.0                    4
..           ...               ...          ...                  ...
75            75          0.577959          0.8                   15
76            30          0.572909          0.2                   10
77            40          0.565666          0.5                    0
78            59          0.562361          0.5                   19
79            64          0.560493          0.8                    4

[80 rows x 4 columns]

prototype_idx = 52, prototype_score = 0.665933
outlier_idx = 64, outlier_score = 0.560493


==============================
Matrix: mat7OR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.733341     0.090474     0.452711     0.965986

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.965986,0.000000,0.965986,0.965986
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.706357,0.061670,0.545174,0.856716
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.706579,0.066798,0.548575,0.883963
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.674824,0.063976,0.452832,0.827124

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.769659  0.755506  0.728654
0.2  0.769659       NaN  0.704529  0.693704
0.5  0.755506  0.704529       NaN  0.690810
0.8  0.728654  0.693704  0.690810       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.058101  0.055733  0.070885
0.2  0.058101       NaN  0.069501  0.064168
0.5  0.055733  0.069501       NaN  0.065408
0.8  0.070885  0.064168  0.065408       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.763437             0.72381            0.039626

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.802913          0.0                    0
1              1          0.802913          0.0                    1
2              2          0.802913          0.0                    2
3              3          0.802913          0.0                    3
4              4          0.802913          0.0                    4
..           ...               ...          ...                  ...
75            50          0.650714          0.5                   10
76            64          0.650054          0.8                    4
77            40          0.647733          0.5                    0
78            79          0.619500          0.8                   19
79            75          0.611074          0.8                   15

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.802913
outlier_idx = 75, outlier_score = 0.611074


==============================
Matrix: mat8ECCC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.626139      0.08241      0.41964      0.83105

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.479259,0.000000,0.479259,0.479259
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.642125,0.058661,0.508072,0.782119
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.627958,0.067143,0.479259,0.808483
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.648105,0.076244,0.419640,0.831050

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.633033  0.592037  0.650612
0.2  0.633033       NaN  0.642456  0.646781
0.5  0.592037  0.642456       NaN  0.642792
0.8  0.650612  0.646781  0.642792       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.068615  0.083751  0.098894
0.2  0.068615       NaN  0.059670  0.059547
0.5  0.083751  0.059670       NaN  0.071609
0.8  0.098894  0.059547  0.071609       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.599362            0.634619           -0.035257

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             71          0.739056          0.8                   11
1             78          0.723111          0.8                   18
2             20          0.707306          0.2                    0
3             76          0.706854          0.8                   16
4             33          0.698840          0.2                   13
..           ...               ...          ...                  ...
75            32          0.580663          0.2                   12
76            21          0.573961          0.2                    1
77            47          0.572189          0.5                    7
78            26          0.554436          0.2                    6
79            67          0.533986          0.8                    7

[80 rows x 4 columns]

prototype_idx = 71, prototype_score = 0.739056
outlier_idx = 67, outlier_score = 0.533986


==============================
Matrix: mat9N
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.577605     0.216139     0.008764     0.974466

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.726676,0.000000,0.726676,0.726676
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.511553,0.327683,0.008764,0.974466
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.530577,0.209763,0.039219,0.974466
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.541144,0.277063,0.009706,0.974466

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.632051  0.630365  0.620848
0.2  0.632051       NaN  0.523728  0.529568
0.5  0.630365  0.523728       NaN  0.529297
0.8  0.620848  0.529568  0.529297       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.010164  0.018923  0.015348
0.2  0.010164       NaN  0.271060  0.302731
0.5  0.018923  0.271060       NaN  0.255740
0.8  0.015348  0.302731  0.255740       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.577488            0.577643           -0.000155

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             40          0.658489          0.5                    0
1              0          0.651546          0.0                    0
2              2          0.651546          0.0                    2
3              1          0.651546          0.0                    1
4              4          0.651546          0.0                    4
..           ...               ...          ...                  ...
75            44          0.346018          0.5                    4
76            72          0.328893          0.8                   12
77            26          0.304985          0.2                    6
78            39          0.293284          0.2                   19
79            64          0.290163          0.8                    4

[80 rows x 4 columns]

prototype_idx = 40, prototype_score = 0.658489
outlier_idx = 64, outlier_score = 0.290163


####################################################################################################
Processing question 3/17: Easy P4306
####################################################################################################

================================================================================
题目 index = 3
题目名称 = Easy P4306
矩阵保存目录 = Questions/Easy P4306/CrossEncoder_Results/matrices
================================================================================

===== mat1PI =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,...,0.714557,0.741829,0.793302,0.766407,0.717643,0.816543,0.783136,0.732816,0.756001,0.740724
1,0.905615,1.000000,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,...,0.714557,0.741829,0.793302,0.766407,0.717643,0.816543,0.783136,0.732816,0.756001,0.740724
2,0.905615,0.905615,1.000000,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,...,0.714557,0.741829,0.793302,0.766407,0.717643,0.816543,0.783136,0.732816,0.756001,0.740724
3,0.905615,0.905615,0.905615,1.000000,0.905615,0.905615,0.905615,0.905615,0.905615,0.905615,...,0.714557,0.741829,0.793302,0.766407,0.717643,0.816543,0.783136,0.732816,0.756001,0.740724
4,0.905615,0.905615,0.905615,0.905615,1.000000,0.905615,0.905615,0.905615,0.905615,0.905615,...,0.714557,0.741829,0.793302,0.766407,0.717643,0.816543,0.783136,0.732816,0.756001,0.740724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.816543,0.816543,0.816543,0.816543,0.816543,0.816543,0.816543,0.816543,0.816543,0.816543,...,0.744606,0.755614,0.751789,0.741069,0.732178,1.000000,0.745734,0.721272,0.772196,0.744336
76,0.783136,0.783136,0.783136,0.783136,0.783136,0.783136,0.783136,0.783136,0.783136,0.783136,...,0.714847,0.720526,0.727720,0.695466,0.696745,0.745734,1.000000,0.720220,0.763471,0.747360
77,0.732816,0.732816,0.732816,0.732816,0.732816,0.732816,0.732816,0.732816,0.732816,0.732816,...,0.751549,0.759075,0.716105,0.729446,0.713985,0.721272,0.720220,1.000000,0.742835,0.784912
78,0.756001,0.756001,0.756001,0.756001,0.756001,0.756001,0.756001,0.756001,0.756001,0.756001,...,0.747397,0.771318,0.717916,0.731413,0.754618,0.772196,0.763471,0.742835,1.000000,0.706438
79,0.740724,0.740724,0.740724,0.740724,0.740724,0.740724,0.740724,0.740724,0.740724,0.740724,...,0.744156,0.774468,0.724588,0.726222,0.737352,0.744336,0.747360,0.784912,0.706438,1.000000

===== mat2FD =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,...,0.723991,0.688485,0.694659,0.754474,0.733695,0.698074,0.785076,0.739494,0.695541,0.758525
1,0.904130,1.000000,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,...,0.723991,0.688485,0.694659,0.754474,0.733695,0.698074,0.785076,0.739494,0.695541,0.758525
2,0.904130,0.904130,1.000000,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,...,0.723991,0.688485,0.694659,0.754474,0.733695,0.698074,0.785076,0.739494,0.695541,0.758525
3,0.904130,0.904130,0.904130,1.000000,0.904130,0.904130,0.904130,0.904130,0.904130,0.904130,...,0.723991,0.688485,0.694659,0.754474,0.733695,0.698074,0.785076,0.739494,0.695541,0.758525
4,0.904130,0.904130,0.904130,0.904130,1.000000,0.904130,0.904130,0.904130,0.904130,0.904130,...,0.723991,0.688485,0.694659,0.754474,0.733695,0.698074,0.785076,0.739494,0.695541,0.758525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.698074,0.698074,0.698074,0.698074,0.698074,0.698074,0.698074,0.698074,0.698074,0.698074,...,0.799759,0.676591,0.713721,0.693660,0.671384,1.000000,0.685916,0.706851,0.720995,0.698262
76,0.785076,0.785076,0.785076,0.785076,0.785076,0.785076,0.785076,0.785076,0.785076,0.785076,...,0.716166,0.695385,0.703130,0.750583,0.759755,0.685916,1.000000,0.726062,0.716678,0.693987
77,0.739494,0.739494,0.739494,0.739494,0.739494,0.739494,0.739494,0.739494,0.739494,0.739494,...,0.724756,0.799169,0.695670,0.758112,0.739501,0.706851,0.726062,1.000000,0.751991,0.786797
78,0.695541,0.695541,0.695541,0.695541,0.695541,0.695541,0.695541,0.695541,0.695541,0.695541,...,0.727975,0.725517,0.676642,0.705585,0.687012,0.720995,0.716678,0.751991,1.000000,0.711739
79,0.758525,0.758525,0.758525,0.758525,0.758525,0.758525,0.758525,0.758525,0.758525,0.758525,...,0.772427,0.718657,0.666183,0.782821,0.751675,0.698262,0.693987,0.786797,0.711739,1.000000

===== mat3RC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,...,0.721775,0.742227,0.707391,0.694039,0.683316,0.741458,0.741317,0.698276,0.721524,0.671070
1,0.946678,1.000000,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,...,0.721775,0.742227,0.707391,0.694039,0.683316,0.741458,0.741317,0.698276,0.721524,0.671070
2,0.946678,0.946678,1.000000,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,...,0.721775,0.742227,0.707391,0.694039,0.683316,0.741458,0.741317,0.698276,0.721524,0.671070
3,0.946678,0.946678,0.946678,1.000000,0.946678,0.946678,0.946678,0.946678,0.946678,0.946678,...,0.721775,0.742227,0.707391,0.694039,0.683316,0.741458,0.741317,0.698276,0.721524,0.671070
4,0.946678,0.946678,0.946678,0.946678,1.000000,0.946678,0.946678,0.946678,0.946678,0.946678,...,0.721775,0.742227,0.707391,0.694039,0.683316,0.741458,0.741317,0.698276,0.721524,0.671070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.741458,0.741458,0.741458,0.741458,0.741458,0.741458,0.741458,0.741458,0.741458,0.741458,...,0.723455,0.694910,0.751496,0.720219,0.715383,1.000000,0.675608,0.679232,0.679404,0.740260
76,0.741317,0.741317,0.741317,0.741317,0.741317,0.741317,0.741317,0.741317,0.741317,0.741317,...,0.696448,0.727287,0.716041,0.741676,0.662384,0.675608,1.000000,0.668796,0.702561,0.711990
77,0.698276,0.698276,0.698276,0.698276,0.698276,0.698276,0.698276,0.698276,0.698276,0.698276,...,0.636623,0.637210,0.651517,0.692098,0.655436,0.679232,0.668796,1.000000,0.672588,0.632863
78,0.721524,0.721524,0.721524,0.721524,0.721524,0.721524,0.721524,0.721524,0.721524,0.721524,...,0.713478,0.783532,0.674453,0.739580,0.691276,0.679404,0.702561,0.672588,1.000000,0.711438
79,0.671070,0.671070,0.671070,0.671070,0.671070,0.671070,0.671070,0.671070,0.671070,0.671070,...,0.711407,0.670262,0.722797,0.679198,0.633385,0.740260,0.711990,0.632863,0.711438,1.000000

===== mat4MS =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,...,0.648058,0.631799,0.645635,0.680674,0.665418,0.683780,0.624413,0.651558,0.643679,0.648075
1,0.823501,1.000000,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,...,0.648058,0.631799,0.645635,0.680674,0.665418,0.683780,0.624413,0.651558,0.643679,0.648075
2,0.823501,0.823501,1.000000,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,...,0.648058,0.631799,0.645635,0.680674,0.665418,0.683780,0.624413,0.651558,0.643679,0.648075
3,0.823501,0.823501,0.823501,1.000000,0.823501,0.823501,0.823501,0.823501,0.823501,0.823501,...,0.648058,0.631799,0.645635,0.680674,0.665418,0.683780,0.624413,0.651558,0.643679,0.648075
4,0.823501,0.823501,0.823501,0.823501,1.000000,0.823501,0.823501,0.823501,0.823501,0.823501,...,0.648058,0.631799,0.645635,0.680674,0.665418,0.683780,0.624413,0.651558,0.643679,0.648075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.683780,0.683780,0.683780,0.683780,0.683780,0.683780,0.683780,0.683780,0.683780,0.683780,...,0.753907,0.757118,0.739311,0.855446,0.747257,1.000000,0.717661,0.727573,0.761776,0.793261
76,0.624413,0.624413,0.624413,0.624413,0.624413,0.624413,0.624413,0.624413,0.624413,0.624413,...,0.756794,0.740178,0.741199,0.796155,0.786653,0.717661,1.000000,0.718879,0.810303,0.769915
77,0.651558,0.651558,0.651558,0.651558,0.651558,0.651558,0.651558,0.651558,0.651558,0.651558,...,0.772347,0.833429,0.725476,0.806837,0.725567,0.727573,0.718879,1.000000,0.717167,0.734290
78,0.643679,0.643679,0.643679,0.643679,0.643679,0.643679,0.643679,0.643679,0.643679,0.643679,...,0.751001,0.751589,0.692967,0.880065,0.707310,0.761776,0.810303,0.717167,1.000000,0.796590
79,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,...,0.831787,0.725561,0.721223,0.867729,0.765811,0.793261,0.769915,0.734290,0.796590,1.000000

===== mat5INV =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,...,0.773337,0.759098,0.786266,0.772159,0.812910,0.798138,0.762878,0.772455,0.730454,0.808174
1,0.889978,1.000000,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,...,0.773337,0.759098,0.786266,0.772159,0.812910,0.798138,0.762878,0.772455,0.730454,0.808174
2,0.889978,0.889978,1.000000,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,...,0.773337,0.759098,0.786266,0.772159,0.812910,0.798138,0.762878,0.772455,0.730454,0.808174
3,0.889978,0.889978,0.889978,1.000000,0.889978,0.889978,0.889978,0.889978,0.889978,0.889978,...,0.773337,0.759098,0.786266,0.772159,0.812910,0.798138,0.762878,0.772455,0.730454,0.808174
4,0.889978,0.889978,0.889978,0.889978,1.000000,0.889978,0.889978,0.889978,0.889978,0.889978,...,0.773337,0.759098,0.786266,0.772159,0.812910,0.798138,0.762878,0.772455,0.730454,0.808174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.798138,0.798138,0.798138,0.798138,0.798138,0.798138,0.798138,0.798138,0.798138,0.798138,...,0.738843,0.714155,0.760786,0.792045,0.699763,1.000000,0.674741,0.728747,0.621030,0.732124
76,0.762878,0.762878,0.762878,0.762878,0.762878,0.762878,0.762878,0.762878,0.762878,0.762878,...,0.697669,0.700947,0.709563,0.733871,0.673743,0.674741,1.000000,0.698196,0.665222,0.674221
77,0.772455,0.772455,0.772455,0.772455,0.772455,0.772455,0.772455,0.772455,0.772455,0.772455,...,0.778350,0.698702,0.708118,0.798617,0.722897,0.728747,0.698196,1.000000,0.702182,0.734066
78,0.730454,0.730454,0.730454,0.730454,0.730454,0.730454,0.730454,0.730454,0.730454,0.730454,...,0.743617,0.674397,0.673219,0.768795,0.683275,0.621030,0.665222,0.702182,1.000000,0.659702
79,0.808174,0.808174,0.808174,0.808174,0.808174,0.808174,0.808174,0.808174,0.808174,0.808174,...,0.728808,0.692799,0.741135,0.789080,0.808955,0.732124,0.674221,0.734066,0.659702,1.000000

===== mat6POUR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,...,0.604303,0.629680,0.618340,0.636298,0.566928,0.604381,0.599516,0.646075,0.615217,0.651313
1,0.745027,1.000000,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,...,0.604303,0.629680,0.618340,0.636298,0.566928,0.604381,0.599516,0.646075,0.615217,0.651313
2,0.745027,0.745027,1.000000,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,...,0.604303,0.629680,0.618340,0.636298,0.566928,0.604381,0.599516,0.646075,0.615217,0.651313
3,0.745027,0.745027,0.745027,1.000000,0.745027,0.745027,0.745027,0.745027,0.745027,0.745027,...,0.604303,0.629680,0.618340,0.636298,0.566928,0.604381,0.599516,0.646075,0.615217,0.651313
4,0.745027,0.745027,0.745027,0.745027,1.000000,0.745027,0.745027,0.745027,0.745027,0.745027,...,0.604303,0.629680,0.618340,0.636298,0.566928,0.604381,0.599516,0.646075,0.615217,0.651313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.604381,0.604381,0.604381,0.604381,0.604381,0.604381,0.604381,0.604381,0.604381,0.604381,...,0.661323,0.645479,0.660570,0.769479,0.606318,1.000000,0.619536,0.680556,0.683608,0.713953
76,0.599516,0.599516,0.599516,0.599516,0.599516,0.599516,0.599516,0.599516,0.599516,0.599516,...,0.603655,0.587192,0.632818,0.666591,0.516377,0.619536,1.000000,0.546166,0.522449,0.586713
77,0.646075,0.646075,0.646075,0.646075,0.646075,0.646075,0.646075,0.646075,0.646075,0.646075,...,0.784710,0.769576,0.778097,0.763748,0.668391,0.680556,0.546166,1.000000,0.755165,0.716090
78,0.615217,0.615217,0.615217,0.615217,0.615217,0.615217,0.615217,0.615217,0.615217,0.615217,...,0.748186,0.709052,0.758476,0.724673,0.616486,0.683608,0.522449,0.755165,1.000000,0.679278
79,0.651313,0.651313,0.651313,0.651313,0.651313,0.651313,0.651313,0.651313,0.651313,0.651313,...,0.694376,0.673278,0.666079,0.728695,0.656756,0.713953,0.586713,0.716090,0.679278,1.000000

===== mat7OR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,...,0.564237,0.700480,0.568753,0.532879,0.696187,0.627158,0.722534,0.565900,0.580373,0.620551
1,0.902510,1.000000,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,...,0.564237,0.700480,0.568753,0.532879,0.696187,0.627158,0.722534,0.565900,0.580373,0.620551
2,0.902510,0.902510,1.000000,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,...,0.564237,0.700480,0.568753,0.532879,0.696187,0.627158,0.722534,0.565900,0.580373,0.620551
3,0.902510,0.902510,0.902510,1.000000,0.902510,0.902510,0.902510,0.902510,0.902510,0.902510,...,0.564237,0.700480,0.568753,0.532879,0.696187,0.627158,0.722534,0.565900,0.580373,0.620551
4,0.902510,0.902510,0.902510,0.902510,1.000000,0.902510,0.902510,0.902510,0.902510,0.902510,...,0.564237,0.700480,0.568753,0.532879,0.696187,0.627158,0.722534,0.565900,0.580373,0.620551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.627158,0.627158,0.627158,0.627158,0.627158,0.627158,0.627158,0.627158,0.627158,0.627158,...,0.672466,0.639135,0.709122,0.681704,0.704805,1.000000,0.784303,0.657171,0.845927,0.759033
76,0.722534,0.722534,0.722534,0.722534,0.722534,0.722534,0.722534,0.722534,0.722534,0.722534,...,0.725410,0.744994,0.702022,0.669924,0.665218,0.784303,1.000000,0.714870,0.666307,0.683450
77,0.565900,0.565900,0.565900,0.565900,0.565900,0.565900,0.565900,0.565900,0.565900,0.565900,...,0.698138,0.643558,0.805899,0.640750,0.637916,0.657171,0.714870,1.000000,0.611053,0.725265
78,0.580373,0.580373,0.580373,0.580373,0.580373,0.580373,0.580373,0.580373,0.580373,0.580373,...,0.683598,0.564412,0.565041,0.626143,0.624384,0.845927,0.666307,0.611053,1.000000,0.634648
79,0.620551,0.620551,0.620551,0.620551,0.620551,0.620551,0.620551,0.620551,0.620551,0.620551,...,0.663063,0.601799,0.659136,0.719125,0.693532,0.759033,0.683450,0.725265,0.634648,1.000000

===== mat8ECCC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,...,0.668183,0.664700,0.633773,0.625081,0.614131,0.647030,0.661257,0.614131,0.626994,0.648075
1,0.748854,1.000000,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,...,0.668183,0.664700,0.633773,0.625081,0.614131,0.647030,0.661257,0.614131,0.626994,0.648075
2,0.748854,0.748854,1.000000,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,...,0.668183,0.664700,0.633773,0.625081,0.614131,0.647030,0.661257,0.614131,0.626994,0.648075
3,0.748854,0.748854,0.748854,1.000000,0.748854,0.748854,0.748854,0.748854,0.748854,0.748854,...,0.668183,0.664700,0.633773,0.625081,0.614131,0.647030,0.661257,0.614131,0.626994,0.648075
4,0.748854,0.748854,0.748854,0.748854,1.000000,0.748854,0.748854,0.748854,0.748854,0.748854,...,0.668183,0.664700,0.633773,0.625081,0.614131,0.647030,0.661257,0.614131,0.626994,0.648075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.647030,0.647030,0.647030,0.647030,0.647030,0.647030,0.647030,0.647030,0.647030,0.647030,...,0.697579,0.722579,0.676121,0.669228,0.527073,1.000000,0.618910,0.525006,0.617587,0.594080
76,0.661257,0.661257,0.661257,0.661257,0.661257,0.661257,0.661257,0.661257,0.661257,0.661257,...,0.651391,0.725170,0.648129,0.624733,0.567472,0.618910,1.000000,0.565291,0.635377,0.668532
77,0.614131,0.614131,0.614131,0.614131,0.614131,0.614131,0.614131,0.614131,0.614131,0.614131,...,0.548214,0.651879,0.588136,0.527109,0.479259,0.525006,0.565291,1.000000,0.611357,0.602783
78,0.626994,0.626994,0.626994,0.626994,0.626994,0.626994,0.626994,0.626994,0.626994,0.626994,...,0.652689,0.707032,0.710844,0.623230,0.611357,0.617587,0.635377,0.611357,1.000000,0.664634
79,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,0.648075,...,0.595324,0.717683,0.667584,0.649788,0.602783,0.594080,0.668532,0.602783,0.664634,1.000000

===== mat9N =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,...,0.859082,0.893220,0.861563,0.869641,0.493531,0.964371,0.126135,0.580927,0.804092,0.814649
1,0.972437,1.000000,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,...,0.859082,0.893220,0.861563,0.869641,0.493531,0.964371,0.126135,0.580927,0.804092,0.814649
2,0.972437,0.972437,1.000000,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,...,0.859082,0.893220,0.861563,0.869641,0.493531,0.964371,0.126135,0.580927,0.804092,0.814649
3,0.972437,0.972437,0.972437,1.000000,0.972437,0.972437,0.972437,0.972437,0.972437,0.972437,...,0.859082,0.893220,0.861563,0.869641,0.493531,0.964371,0.126135,0.580927,0.804092,0.814649
4,0.972437,0.972437,0.972437,0.972437,1.000000,0.972437,0.972437,0.972437,0.972437,0.972437,...,0.859082,0.893220,0.861563,0.869641,0.493531,0.964371,0.126135,0.580927,0.804092,0.814649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.964371,0.964371,0.964371,0.964371,0.964371,0.964371,0.964371,0.964371,0.964371,0.964371,...,0.901000,0.859720,0.862599,0.895136,0.535215,1.000000,0.126377,0.590941,0.796760,0.808198
76,0.126135,0.126135,0.126135,0.126135,0.126135,0.126135,0.126135,0.126135,0.126135,0.126135,...,0.183623,0.288904,0.120554,0.152156,0.550923,0.126377,1.000000,0.603487,0.324918,0.269672
77,0.580927,0.580927,0.580927,0.580927,0.580927,0.580927,0.580927,0.580927,0.580927,0.580927,...,0.553882,0.554483,0.550005,0.541568,0.661224,0.590941,0.603487,1.000000,0.532403,0.548573
78,0.804092,0.804092,0.804092,0.804092,0.804092,0.804092,0.804092,0.804092,0.804092,0.804092,...,0.783880,0.780670,0.772988,0.780424,0.529292,0.796760,0.324918,0.532403,1.000000,0.743061
79,0.814649,0.814649,0.814649,0.814649,0.814649,0.814649,0.814649,0.814649,0.814649,0.814649,...,0.884168,0.814250,0.896739,0.882496,0.532083,0.808198,0.269672,0.548573,0.743061,1.000000

================================================================================
Question index = 3
Question Name = Easy P4306
k = 20
temperature_list = [0.0, 0.2, 0.5, 0.8]
analysis save dir = Questions/Easy P4306/CrossEncoder_Results/analysis
================================================================================

===== Overview Table =====

,matrix,offdiag_mean,offdiag_std,offdiag_min,offdiag_max,overall_within_mean,overall_cross_mean,within_minus_cross,prototype_idx,prototype_score,outlier_idx,outlier_score
0,mat1PI,0.767751,0.052195,0.654101,0.905615,0.796350,0.758694,0.037656,0,0.803771,45,0.701466
1,mat2FD,0.745497,0.066043,0.543874,0.928467,0.780497,0.734413,0.046084,31,0.797394,61,0.641006
2,mat3RC,0.708052,0.074653,0.474362,0.946678,0.755806,0.692929,0.062877,0,0.760086,53,0.642563
3,mat4MS,0.723296,0.069454,0.589612,0.921085,0.774462,0.707093,0.067369,73,0.783461,51,0.652300
4,mat5INV,0.759532,0.056609,0.574087,0.889978,0.773704,0.755044,0.018660,0,0.804040,60,0.677430
5,mat6POUR,0.630536,0.061498,0.484602,0.872573,0.668361,0.618558,0.049803,77,0.685311,51,0.554482
6,mat7OR,0.686134,0.081258,0.437033,0.971542,0.734532,0.670808,0.063724,63,0.726590,78,0.606133
7,mat8ECCC,0.585535,0.071510,0.472945,0.748854,0.594869,0.582579,0.012291,71,0.657742,77,0.539972
8,mat9N,0.615659,0.185914,0.010252,0.974466,0.682857,0.594380,0.088477,75,0.701532,27,0.274262

==============================
Matrix: mat1PI
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.767751     0.052195     0.654101     0.905615

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.905615,0.000000,0.905615,0.905615
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.764320,0.042457,0.681243,0.872971
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.768491,0.041452,0.654101,0.869912
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.746973,0.031109,0.677315,0.838175

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.802131  0.761172  0.751257
0.2  0.802131       NaN  0.746753  0.736251
0.5  0.761172  0.746753       NaN  0.754600
0.8  0.751257  0.736251  0.754600       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.050282  0.025793  0.024731
0.2  0.050282       NaN  0.032556  0.028926
0.5  0.025793  0.032556       NaN  0.036685
0.8  0.024731  0.028926  0.036685       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0              0.79635            0.758694            0.037656

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.803771          0.0                    0
1              1          0.803771          0.0                    1
2              2          0.803771          0.0                    2
3              3          0.803771          0.0                    3
4              4          0.803771          0.0                    4
..           ...               ...          ...                  ...
75            61          0.726312          0.8                    1
76            33          0.723974          0.2                   13
77            50          0.717712          0.5                   10
78            35          0.717664          0.2                   15
79            45          0.701466          0.5                    5

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.803771
outlier_idx = 45, outlier_score = 0.701466


==============================
Matrix: mat2FD
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.745497     0.066043     0.543874     0.928467

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.904130,0.000000,0.904130,0.904130
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.793552,0.059397,0.610631,0.928467
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.702541,0.049147,0.615493,0.839130
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.721765,0.050700,0.597206,0.842158

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.757010  0.731838  0.723871
0.2  0.757010       NaN  0.744806  0.741172
0.5  0.731838  0.744806       NaN  0.707782
0.8  0.723871  0.741172  0.707782       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.020734  0.040302  0.034004
0.2  0.020734       NaN  0.057127  0.060218
0.5  0.040302  0.057127       NaN  0.062373
0.8  0.034004  0.060218  0.062373       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.780497            0.734413            0.046084

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             31          0.797394          0.2                   11
1             30          0.789425          0.2                   10
2             29          0.787709          0.2                    9
3             24          0.782263          0.2                    4
4              0          0.777631          0.0                    0
..           ...               ...          ...                  ...
75            49          0.680547          0.5                    9
76            55          0.676156          0.5                   15
77            40          0.673287          0.5                    0
78            72          0.658413          0.8                   12
79            61          0.641006          0.8                    1

[80 rows x 4 columns]

prototype_idx = 31, prototype_score = 0.797394
outlier_idx = 61, outlier_score = 0.641006


==============================
Matrix: mat3RC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.708052     0.074653     0.474362     0.946678

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.946678,0.000000,0.946678,0.946678
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.727689,0.046886,0.608543,0.880953
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.666860,0.050634,0.558414,0.812780
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.681998,0.047189,0.474362,0.786895

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.708124  0.691880  0.702990
0.2  0.708124       NaN  0.693881  0.689465
0.5  0.691880  0.693881       NaN  0.671235
0.8  0.702990  0.689465  0.671235       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.029341  0.031821  0.028974
0.2  0.029341       NaN  0.052654  0.047475
0.5  0.031821  0.052654       NaN  0.049192
0.8  0.028974  0.047475  0.049192       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.755806            0.692929            0.062877

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.760086          0.0                    0
1              1          0.760086          0.0                    1
2              2          0.760086          0.0                    2
3              3          0.760086          0.0                    3
4              4          0.760086          0.0                    4
..           ...               ...          ...                  ...
75            69          0.656601          0.8                    9
76            68          0.649213          0.8                    8
77            74          0.648444          0.8                   14
78            45          0.648024          0.5                    5
79            53          0.642563          0.5                   13

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.760086
outlier_idx = 53, outlier_score = 0.642563


==============================
Matrix: mat4MS
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.723296     0.069454     0.589612     0.921085

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.823501,0.000000,0.823501,0.823501
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.764018,0.044982,0.631075,0.872564
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.748935,0.051647,0.607195,0.890628
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.761393,0.055966,0.610796,0.900415

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.658502  0.646545  0.654509
0.2  0.658502       NaN  0.759996  0.768718
0.5  0.646545  0.759996       NaN  0.754289
0.8  0.654509  0.768718  0.754289       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.021269  0.021522  0.019452
0.2  0.021269       NaN  0.050692  0.045957
0.5  0.021522  0.050692       NaN  0.051636
0.8  0.019452  0.045957  0.051636       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.774462            0.707093            0.067369

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             73          0.783461          0.8                   13
1             22          0.764062          0.2                    2
2             53          0.761055          0.5                   13
3             23          0.760054          0.2                    3
4             30          0.759275          0.2                   10
..           ...               ...          ...                  ...
75            19          0.694147          0.0                   19
76            49          0.691325          0.5                    9
77            68          0.687295          0.8                    8
78            41          0.687059          0.5                    1
79            51          0.652300          0.5                   11

[80 rows x 4 columns]

prototype_idx = 73, prototype_score = 0.783461
outlier_idx = 51, outlier_score = 0.652300


==============================
Matrix: mat5INV
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.759532     0.056609     0.574087     0.889978

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.889978,0.000000,0.889978,0.889978
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.748195,0.051744,0.600141,0.857655
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.729900,0.052162,0.611292,0.862049
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.726743,0.049839,0.589814,0.851530

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.782090  0.770064  0.778325
0.2  0.782090       NaN  0.735856  0.737806
0.5  0.770064  0.735856       NaN  0.726119
0.8  0.778325  0.737806  0.726119       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.025803  0.022339  0.027308
0.2  0.025803       NaN  0.049925  0.049549
0.5  0.022339  0.049925       NaN  0.050200
0.8  0.027308  0.049549  0.050200       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.773704            0.755044             0.01866

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.804040          0.0                    0
1              1          0.804040          0.0                    1
2              2          0.804040          0.0                    2
3              3          0.804040          0.0                    3
4              4          0.804040          0.0                    4
..           ...               ...          ...                  ...
75            78          0.693793          0.8                   18
76            46          0.692466          0.5                    6
77            51          0.690756          0.5                   11
78            36          0.678690          0.2                   16
79            60          0.677430          0.8                    0

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.804040
outlier_idx = 60, outlier_score = 0.677430


==============================
Matrix: mat6POUR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.630536     0.061498     0.484602     0.872573

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.745027,0.000000,0.745027,0.745027
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.622546,0.059856,0.515370,0.819914
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.651520,0.055614,0.526958,0.779806
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.654350,0.059288,0.484602,0.788942

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.583251  0.603190  0.609400
0.2  0.583251       NaN  0.631749  0.632681
0.5  0.603190  0.631749       NaN  0.651076
0.8  0.609400  0.632681  0.651076       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.024258  0.038847  0.033328
0.2  0.024258       NaN  0.064848  0.061273
0.5  0.038847  0.064848       NaN  0.057234
0.8  0.033328  0.061273  0.057234       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.668361            0.618558            0.049803

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             77          0.685311          0.8                   17
1             43          0.680570          0.5                    3
2             33          0.680038          0.2                   13
3             64          0.672864          0.8                    4
4             35          0.666874          0.2                   15
..           ...               ...          ...                  ...
75            30          0.571730          0.2                   10
76            26          0.571630          0.2                    6
77            65          0.568252          0.8                    5
78            23          0.568209          0.2                    3
79            51          0.554482          0.5                   11

[80 rows x 4 columns]

prototype_idx = 77, prototype_score = 0.685311
outlier_idx = 51, outlier_score = 0.554482


==============================
Matrix: mat7OR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.686134     0.081258     0.437033     0.971542

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.902510,0.000000,0.902510,0.902510
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.688949,0.061209,0.542306,0.828509
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.681240,0.052020,0.482839,0.841286
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.665429,0.067916,0.437033,0.879626

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.701857  0.657430  0.631808
0.2  0.701857       NaN  0.682976  0.672664
0.5  0.657430  0.682976       NaN  0.678113
0.8  0.631808  0.672664  0.678113       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.047563  0.050986  0.061426
0.2  0.047563       NaN  0.059371  0.064097
0.5  0.050986  0.059371       NaN  0.062476
0.8  0.061426  0.064097  0.062476       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.734532            0.670808            0.063724

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             63          0.726590          0.8                    3
1             36          0.724614          0.2                   16
2             76          0.722405          0.8                   16
3              0          0.721134          0.0                    0
4              4          0.721134          0.0                    4
..           ...               ...          ...                  ...
75            72          0.624833          0.8                   12
76            67          0.624773          0.8                    7
77            57          0.617710          0.5                   17
78            73          0.606595          0.8                   13
79            78          0.606133          0.8                   18

[80 rows x 4 columns]

prototype_idx = 63, prototype_score = 0.726590
outlier_idx = 78, outlier_score = 0.606133


==============================
Matrix: mat8ECCC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.585535      0.07151     0.472945     0.748854

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.748854,0.000000,0.748854,0.748854
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.499347,0.037151,0.472945,0.684396
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.538207,0.056950,0.479259,0.704006
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.593071,0.059702,0.479259,0.742457

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.612544  0.616493  0.625005
0.2  0.612544       NaN  0.519244  0.551720
0.5  0.616493  0.519244       NaN  0.570469
0.8  0.625005  0.551720  0.570469       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.007429  0.011842  0.026216
0.2  0.007429       NaN  0.049352  0.054730
0.5  0.011842  0.049352       NaN  0.062410
0.8  0.026216  0.054730  0.062410       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.594869            0.582579            0.012291

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             71          0.657742          0.8                   11
1              0          0.649482          0.0                    0
2              2          0.649482          0.0                    2
3              1          0.649482          0.0                    1
4              4          0.649482          0.0                    4
..           ...               ...          ...                  ...
75            26          0.540027          0.2                    6
76            23          0.540027          0.2                    3
77            74          0.540025          0.8                   14
78            20          0.539994          0.2                    0
79            77          0.539972          0.8                   17

[80 rows x 4 columns]

prototype_idx = 71, prototype_score = 0.657742
outlier_idx = 77, outlier_score = 0.539972


==============================
Matrix: mat9N
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.615659     0.185914     0.010252     0.974466

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.972437,0.000000,0.972437,0.972437
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.589878,0.096036,0.010252,0.972437
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.594525,0.120330,0.151766,0.974466
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.574586,0.193674,0.120554,0.974466

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.566893  0.606057  0.654312
0.2  0.566893       NaN  0.590001  0.563728
0.5  0.606057  0.590001       NaN  0.585288
0.8  0.654312  0.563728  0.585288       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.193777  0.167061  0.228135
0.2  0.193777       NaN  0.109927  0.138322
0.5  0.167061  0.109927       NaN  0.158823
0.8  0.228135  0.138322  0.158823       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.682857             0.59438            0.088477

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             75          0.701532          0.8                   15
1             38          0.699118          0.2                   18
2             32          0.697823          0.2                   12
3              0          0.696475          0.0                    0
4              4          0.696475          0.0                    4
..           ...               ...          ...                  ...
75            68          0.528063          0.8                    8
76            62          0.369451          0.8                    2
77            57          0.361988          0.5                   17
78            76          0.344682          0.8                   16
79            27          0.274262          0.2                    7

[80 rows x 4 columns]

prototype_idx = 75, prototype_score = 0.701532
outlier_idx = 27, outlier_score = 0.274262


####################################################################################################
Processing question 4/17: Easy P7714
####################################################################################################

================================================================================
题目 index = 4
题目名称 = Easy P7714
矩阵保存目录 = Questions/Easy P7714/CrossEncoder_Results/matrices
================================================================================

===== mat1PI =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,...,0.669700,0.644270,0.734215,0.679721,0.735794,0.671815,0.662993,0.658346,0.638866,0.706087
1,0.822687,1.000000,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,...,0.669700,0.644270,0.734215,0.679721,0.735794,0.671815,0.662993,0.658346,0.638866,0.706087
2,0.822687,0.822687,1.000000,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,...,0.669700,0.644270,0.734215,0.679721,0.735794,0.671815,0.662993,0.658346,0.638866,0.706087
3,0.822687,0.822687,0.822687,1.000000,0.822687,0.822687,0.822687,0.822687,0.822687,0.822687,...,0.669700,0.644270,0.734215,0.679721,0.735794,0.671815,0.662993,0.658346,0.638866,0.706087
4,0.822687,0.822687,0.822687,0.822687,1.000000,0.822687,0.822687,0.822687,0.822687,0.822687,...,0.669700,0.644270,0.734215,0.679721,0.735794,0.671815,0.662993,0.658346,0.638866,0.706087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.671815,0.671815,0.671815,0.671815,0.671815,0.671815,0.671815,0.671815,0.671815,0.671815,...,0.730635,0.716537,0.745427,0.800799,0.716008,1.000000,0.747631,0.745112,0.766737,0.763309
76,0.662993,0.662993,0.662993,0.662993,0.662993,0.662993,0.662993,0.662993,0.662993,0.662993,...,0.760053,0.679196,0.801431,0.772085,0.686441,0.747631,1.000000,0.710540,0.699239,0.722514
77,0.658346,0.658346,0.658346,0.658346,0.658346,0.658346,0.658346,0.658346,0.658346,0.658346,...,0.784595,0.723952,0.842498,0.775208,0.696820,0.745112,0.710540,1.000000,0.697675,0.720058
78,0.638866,0.638866,0.638866,0.638866,0.638866,0.638866,0.638866,0.638866,0.638866,0.638866,...,0.751417,0.753911,0.772821,0.800153,0.684106,0.766737,0.699239,0.697675,1.000000,0.710659
79,0.706087,0.706087,0.706087,0.706087,0.706087,0.706087,0.706087,0.706087,0.706087,0.706087,...,0.765991,0.740153,0.811299,0.786892,0.710705,0.763309,0.722514,0.720058,0.710659,1.000000

===== mat2FD =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,...,0.721686,0.779430,0.622361,0.726015,0.700118,0.713539,0.622633,0.598923,0.681612,0.750863
1,0.899641,1.000000,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,...,0.721686,0.779430,0.622361,0.726015,0.700118,0.713539,0.622633,0.598923,0.681612,0.750863
2,0.899641,0.899641,1.000000,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,...,0.721686,0.779430,0.622361,0.726015,0.700118,0.713539,0.622633,0.598923,0.681612,0.750863
3,0.899641,0.899641,0.899641,1.000000,0.899641,0.899641,0.899641,0.899641,0.899641,0.899641,...,0.721686,0.779430,0.622361,0.726015,0.700118,0.713539,0.622633,0.598923,0.681612,0.750863
4,0.899641,0.899641,0.899641,0.899641,1.000000,0.899641,0.899641,0.899641,0.899641,0.899641,...,0.721686,0.779430,0.622361,0.726015,0.700118,0.713539,0.622633,0.598923,0.681612,0.750863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.713539,0.713539,0.713539,0.713539,0.713539,0.713539,0.713539,0.713539,0.713539,0.713539,...,0.773629,0.667647,0.621244,0.663891,0.767876,1.000000,0.643841,0.649926,0.727673,0.821942
76,0.622633,0.622633,0.622633,0.622633,0.622633,0.622633,0.622633,0.622633,0.622633,0.622633,...,0.713022,0.605076,0.694806,0.677254,0.732932,0.643841,1.000000,0.578096,0.769023,0.707095
77,0.598923,0.598923,0.598923,0.598923,0.598923,0.598923,0.598923,0.598923,0.598923,0.598923,...,0.671300,0.647464,0.550110,0.645988,0.642725,0.649926,0.578096,1.000000,0.520591,0.570423
78,0.681612,0.681612,0.681612,0.681612,0.681612,0.681612,0.681612,0.681612,0.681612,0.681612,...,0.714157,0.611713,0.654026,0.702430,0.763771,0.727673,0.769023,0.520591,1.000000,0.671841
79,0.750863,0.750863,0.750863,0.750863,0.750863,0.750863,0.750863,0.750863,0.750863,0.750863,...,0.712405,0.631403,0.678375,0.691892,0.736609,0.821942,0.707095,0.570423,0.671841,1.000000

===== mat3RC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,...,0.654870,0.629362,0.612949,0.652227,0.771540,0.620841,0.648832,0.588181,0.594409,0.594863
1,0.966953,1.000000,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,...,0.654870,0.629362,0.612949,0.652227,0.771540,0.620841,0.648833,0.588180,0.594408,0.594863
2,0.966953,0.966953,1.000000,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,...,0.654870,0.629362,0.612949,0.652227,0.771540,0.620841,0.648833,0.588180,0.594408,0.594863
3,0.966953,0.966953,0.966953,1.000000,0.966953,0.966953,0.966953,0.966953,0.966953,0.966953,...,0.654870,0.629362,0.612949,0.652227,0.771540,0.620841,0.648833,0.588180,0.594408,0.594863
4,0.966953,0.966953,0.966953,0.966953,1.000000,0.966953,0.966953,0.966953,0.966953,0.966953,...,0.654870,0.629362,0.612949,0.652227,0.771540,0.620841,0.648833,0.588180,0.594408,0.594863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.620841,0.620841,0.620841,0.620841,0.620841,0.620841,0.620841,0.620841,0.620841,0.620841,...,0.677864,0.714153,0.605063,0.671978,0.685054,1.000000,0.690561,0.625533,0.630938,0.661384
76,0.648832,0.648833,0.648833,0.648833,0.648833,0.648833,0.648833,0.648833,0.648833,0.648833,...,0.661004,0.722195,0.629280,0.661661,0.669733,0.690561,1.000000,0.600141,0.628504,0.605939
77,0.588181,0.588180,0.588180,0.588180,0.588180,0.588180,0.588180,0.588180,0.588180,0.588180,...,0.684087,0.591620,0.609373,0.643267,0.656007,0.625533,0.600141,1.000000,0.539691,0.575726
78,0.594409,0.594408,0.594408,0.594408,0.594408,0.594408,0.594408,0.594408,0.594408,0.594408,...,0.647942,0.657153,0.625140,0.669728,0.599971,0.630938,0.628504,0.539691,1.000000,0.593591
79,0.594863,0.594863,0.594863,0.594863,0.594863,0.594863,0.594863,0.594863,0.594863,0.594863,...,0.641841,0.694629,0.677193,0.725061,0.598568,0.661384,0.605939,0.575726,0.593591,1.000000

===== mat4MS =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,...,0.588825,0.710340,0.602219,0.689098,0.518430,0.543255,0.625498,0.404798,0.540682,0.672048
1,0.944074,1.000000,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,...,0.588825,0.710340,0.602219,0.689098,0.518430,0.543255,0.625498,0.404798,0.540682,0.672048
2,0.944074,0.944074,1.000000,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,...,0.588825,0.710340,0.602219,0.689098,0.518430,0.543255,0.625498,0.404798,0.540682,0.672048
3,0.944074,0.944074,0.944074,1.000000,0.944074,0.944074,0.944074,0.944074,0.944074,0.944074,...,0.588825,0.710340,0.602219,0.689098,0.518430,0.543255,0.625498,0.404798,0.540682,0.672048
4,0.944074,0.944074,0.944074,0.944074,1.000000,0.944074,0.944074,0.944074,0.944074,0.944074,...,0.588825,0.710340,0.602219,0.689098,0.518430,0.543255,0.625498,0.404798,0.540682,0.672048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.543255,0.543255,0.543255,0.543255,0.543255,0.543255,0.543255,0.543255,0.543255,0.543255,...,0.654216,0.559820,0.623889,0.520082,0.593042,1.000000,0.659235,0.574849,0.599063,0.657740
76,0.625498,0.625498,0.625498,0.625498,0.625498,0.625498,0.625498,0.625498,0.625498,0.625498,...,0.648655,0.619391,0.668270,0.635292,0.673483,0.659235,1.000000,0.526729,0.640725,0.610887
77,0.404798,0.404798,0.404798,0.404798,0.404798,0.404798,0.404798,0.404798,0.404798,0.404798,...,0.548003,0.522744,0.601962,0.383741,0.585423,0.574849,0.526729,1.000000,0.514583,0.505449
78,0.540682,0.540682,0.540682,0.540682,0.540682,0.540682,0.540682,0.540682,0.540682,0.540682,...,0.633795,0.563306,0.640687,0.524265,0.598399,0.599063,0.640725,0.514583,1.000000,0.569762
79,0.672048,0.672048,0.672048,0.672048,0.672048,0.672048,0.672048,0.672048,0.672048,0.672048,...,0.618924,0.637958,0.659147,0.583933,0.606201,0.657740,0.610887,0.505449,0.569762,1.000000

===== mat5INV =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,...,0.712053,0.793090,0.667246,0.739729,0.687181,0.667458,0.710662,0.583786,0.645085,0.696919
1,0.959888,1.000000,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,...,0.712053,0.793090,0.667246,0.739729,0.687181,0.667458,0.710662,0.583786,0.645085,0.696919
2,0.959888,0.959888,1.000000,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,...,0.712053,0.793090,0.667246,0.739729,0.687181,0.667458,0.710662,0.583786,0.645085,0.696919
3,0.959888,0.959888,0.959888,1.000000,0.959888,0.959888,0.959888,0.959888,0.959888,0.959888,...,0.712053,0.793090,0.667246,0.739729,0.687181,0.667458,0.710662,0.583786,0.645085,0.696919
4,0.959888,0.959888,0.959888,0.959888,1.000000,0.959888,0.959888,0.959888,0.959888,0.959888,...,0.712053,0.793090,0.667246,0.739729,0.687181,0.667458,0.710662,0.583786,0.645085,0.696919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.667458,0.667458,0.667458,0.667458,0.667458,0.667458,0.667458,0.667458,0.667458,0.667458,...,0.631912,0.711874,0.602063,0.575125,0.581088,1.000000,0.619937,0.598352,0.659433,0.606967
76,0.710662,0.710662,0.710662,0.710662,0.710662,0.710662,0.710662,0.710662,0.710662,0.710662,...,0.647920,0.746466,0.568294,0.683003,0.662892,0.619937,1.000000,0.699926,0.680866,0.711553
77,0.583786,0.583786,0.583786,0.583786,0.583786,0.583786,0.583786,0.583786,0.583786,0.583786,...,0.602224,0.669972,0.580761,0.618469,0.577493,0.598352,0.699926,1.000000,0.651881,0.568506
78,0.645085,0.645085,0.645085,0.645085,0.645085,0.645085,0.645085,0.645085,0.645085,0.645085,...,0.674202,0.642539,0.597794,0.637682,0.639413,0.659433,0.680866,0.651881,1.000000,0.630759
79,0.696919,0.696919,0.696919,0.696919,0.696919,0.696919,0.696919,0.696919,0.696919,0.696919,...,0.715352,0.717894,0.590070,0.628048,0.603469,0.606967,0.711553,0.568506,0.630759,1.000000

===== mat6POUR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,...,0.725506,0.660509,0.643422,0.672716,0.611149,0.634930,0.685547,0.639079,0.687892,0.682900
1,0.938132,1.000000,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,...,0.725506,0.660509,0.643422,0.672716,0.611149,0.634930,0.685547,0.639079,0.687892,0.682900
2,0.938132,0.938132,1.000000,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,...,0.725506,0.660509,0.643422,0.672716,0.611149,0.634930,0.685547,0.639079,0.687892,0.682900
3,0.938132,0.938132,0.938132,1.000000,0.938132,0.938132,0.938132,0.938132,0.938132,0.938132,...,0.725506,0.660509,0.643422,0.672716,0.611149,0.634930,0.685547,0.639079,0.687892,0.682900
4,0.938132,0.938132,0.938132,0.938132,1.000000,0.938132,0.938132,0.938132,0.938132,0.938132,...,0.725506,0.660509,0.643422,0.672716,0.611149,0.634930,0.685547,0.639079,0.687892,0.682900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.634930,0.634930,0.634930,0.634930,0.634930,0.634930,0.634930,0.634930,0.634930,0.634930,...,0.551879,0.579632,0.631382,0.598500,0.561416,1.000000,0.532625,0.560101,0.536130,0.588771
76,0.685547,0.685547,0.685547,0.685547,0.685547,0.685547,0.685547,0.685547,0.685547,0.685547,...,0.591090,0.844595,0.638280,0.623560,0.568270,0.532625,1.000000,0.661723,0.681973,0.664131
77,0.639079,0.639079,0.639079,0.639079,0.639079,0.639079,0.639079,0.639079,0.639079,0.639079,...,0.602990,0.621037,0.645386,0.620571,0.569273,0.560101,0.661723,1.000000,0.631012,0.614735
78,0.687892,0.687892,0.687892,0.687892,0.687892,0.687892,0.687892,0.687892,0.687892,0.687892,...,0.630811,0.691796,0.631215,0.665504,0.579515,0.536130,0.681973,0.631012,1.000000,0.693872
79,0.682900,0.682900,0.682900,0.682900,0.682900,0.682900,0.682900,0.682900,0.682900,0.682900,...,0.656066,0.595671,0.675577,0.714667,0.572904,0.588771,0.664131,0.614735,0.693872,1.000000

===== mat7OR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,...,0.444466,0.604908,0.518627,0.628649,0.621160,0.489059,0.571868,0.492826,0.615518,0.547641
1,0.967339,1.000000,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,...,0.444466,0.604908,0.518627,0.628648,0.621160,0.489059,0.571868,0.492826,0.615518,0.547641
2,0.967339,0.967339,1.000000,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,...,0.444466,0.604908,0.518627,0.628648,0.621160,0.489059,0.571868,0.492826,0.615518,0.547641
3,0.967339,0.967339,0.967339,1.000000,0.967339,0.967339,0.967339,0.967339,0.967339,0.967339,...,0.444466,0.604908,0.518627,0.628648,0.621160,0.489059,0.571868,0.492826,0.615518,0.547641
4,0.967339,0.967339,0.967339,0.967339,1.000000,0.967339,0.967339,0.967339,0.967339,0.967339,...,0.444466,0.604908,0.518627,0.628648,0.621160,0.489059,0.571868,0.492826,0.615518,0.547641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.489059,0.489059,0.489059,0.489059,0.489059,0.489059,0.489059,0.489059,0.489059,0.489059,...,0.548346,0.565439,0.705771,0.613795,0.673212,1.000000,0.651769,0.619631,0.556996,0.640291
76,0.571868,0.571868,0.571868,0.571868,0.571868,0.571868,0.571868,0.571868,0.571868,0.571868,...,0.555073,0.656810,0.639978,0.696452,0.715797,0.651769,1.000000,0.489667,0.571882,0.570040
77,0.492826,0.492826,0.492826,0.492826,0.492826,0.492826,0.492826,0.492826,0.492826,0.492826,...,0.421944,0.377262,0.658011,0.508742,0.586594,0.619631,0.489667,1.000000,0.511650,0.615202
78,0.615518,0.615518,0.615518,0.615518,0.615518,0.615518,0.615518,0.615518,0.615518,0.615518,...,0.525604,0.589829,0.534660,0.588745,0.597674,0.556996,0.571882,0.511650,1.000000,0.479473
79,0.547641,0.547641,0.547641,0.547641,0.547641,0.547641,0.547641,0.547641,0.547641,0.547641,...,0.539113,0.617135,0.679250,0.644199,0.713254,0.640291,0.570040,0.615202,0.479473,1.000000

===== mat8ECCC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,...,0.609460,0.649663,0.645600,0.618991,0.528963,0.627396,0.528963,0.541743,0.620981,0.601810
1,0.782888,1.000000,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,...,0.609460,0.649663,0.645600,0.618991,0.528963,0.627396,0.528963,0.541743,0.620981,0.601810
2,0.782888,0.782888,1.000000,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,...,0.609460,0.649663,0.645600,0.618991,0.528963,0.627396,0.528963,0.541743,0.620981,0.601810
3,0.782888,0.782888,0.782888,1.000000,0.782888,0.782888,0.782888,0.782888,0.782888,0.782888,...,0.609460,0.649663,0.645600,0.618991,0.528963,0.627396,0.528963,0.541743,0.620981,0.601810
4,0.782888,0.782888,0.782888,0.782888,1.000000,0.782888,0.782888,0.782888,0.782888,0.782888,...,0.609460,0.649663,0.645600,0.618991,0.528963,0.627396,0.528963,0.541743,0.620981,0.601810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.627396,0.627396,0.627396,0.627396,0.627396,0.627396,0.627396,0.627396,0.627396,0.627396,...,0.626313,0.532264,0.640311,0.666519,0.607172,1.000000,0.600503,0.590640,0.564165,0.562360
76,0.528963,0.528963,0.528963,0.528963,0.528963,0.528963,0.528963,0.528963,0.528963,0.528963,...,0.567848,0.473739,0.614774,0.585471,0.479259,0.600503,1.000000,0.569899,0.562093,0.501673
77,0.541743,0.541743,0.541743,0.541743,0.541743,0.541743,0.541743,0.541743,0.541743,0.541743,...,0.567398,0.520239,0.622036,0.620483,0.569899,0.590640,0.569899,1.000000,0.589323,0.530476
78,0.620981,0.620981,0.620981,0.620981,0.620981,0.620981,0.620981,0.620981,0.620981,0.620981,...,0.623613,0.609641,0.623621,0.663991,0.562093,0.564165,0.562093,0.589323,1.000000,0.585027
79,0.601810,0.601810,0.601810,0.601810,0.601810,0.601810,0.601810,0.601810,0.601810,0.601810,...,0.558637,0.526401,0.596193,0.620239,0.501673,0.562360,0.501673,0.530476,0.585027,1.000000

===== mat9N =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,...,0.848078,0.676470,0.012527,0.781160,0.524703,0.805449,0.584161,0.010181,0.761141,0.130448
1,0.972014,1.000000,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,...,0.848078,0.676470,0.012527,0.781160,0.524703,0.805449,0.584161,0.010181,0.761141,0.130448
2,0.972014,0.972014,1.000000,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,...,0.848078,0.676470,0.012527,0.781160,0.524703,0.805449,0.584161,0.010181,0.761141,0.130448
3,0.972014,0.972014,0.972014,1.000000,0.972014,0.972014,0.972014,0.972014,0.972014,0.972014,...,0.848078,0.676470,0.012527,0.781160,0.524703,0.805449,0.584161,0.010181,0.761141,0.130448
4,0.972014,0.972014,0.972014,0.972014,1.000000,0.972014,0.972014,0.972014,0.972014,0.972014,...,0.848078,0.676470,0.012527,0.781160,0.524703,0.805449,0.584161,0.010181,0.761141,0.130448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.805449,0.805449,0.805449,0.805449,0.805449,0.805449,0.805449,0.805449,0.805449,0.805449,...,0.876021,0.723461,0.050655,0.879646,0.507632,1.000000,0.553117,0.026715,0.864307,0.184980
76,0.584161,0.584161,0.584161,0.584161,0.584161,0.584161,0.584161,0.584161,0.584161,0.584161,...,0.524143,0.524166,0.598421,0.528545,0.554472,0.553117,1.000000,0.633874,0.606273,0.624447
77,0.010181,0.010181,0.010181,0.010181,0.010181,0.010181,0.010181,0.010181,0.010181,0.010181,...,0.136450,0.161676,0.441898,0.056728,0.511349,0.026715,0.633874,1.000000,0.127142,0.208042
78,0.761141,0.761141,0.761141,0.761141,0.761141,0.761141,0.761141,0.761141,0.761141,0.761141,...,0.853798,0.677617,0.164788,0.807205,0.508054,0.864307,0.606273,0.127142,1.000000,0.179536
79,0.130448,0.130448,0.130448,0.130448,0.130448,0.130448,0.130448,0.130448,0.130448,0.130448,...,0.145038,0.161395,0.282358,0.191568,0.531533,0.184980,0.624447,0.208042,0.179536,1.000000

================================================================================
Question index = 4
Question Name = Easy P7714
k = 20
temperature_list = [0.0, 0.2, 0.5, 0.8]
analysis save dir = Questions/Easy P7714/CrossEncoder_Results/analysis
================================================================================

===== Overview Table =====

,matrix,offdiag_mean,offdiag_std,offdiag_min,offdiag_max,overall_within_mean,overall_cross_mean,within_minus_cross,prototype_idx,prototype_score,outlier_idx,outlier_score
0,mat1PI,0.724338,0.047305,0.620283,0.871801,0.756652,0.714105,0.042547,72,0.764633,65,0.679363
1,mat2FD,0.716978,0.069790,0.478469,0.899641,0.755699,0.704716,0.050983,52,0.762603,77,0.611800
2,mat3RC,0.692643,0.092686,0.402741,0.966953,0.745467,0.675916,0.069551,1,0.750606,43,0.593910
3,mat4MS,0.636430,0.097708,0.379752,0.944074,0.701177,0.615926,0.085251,0,0.690116,77,0.497766
4,mat5INV,0.683257,0.098597,0.450673,0.959888,0.719521,0.671774,0.047747,0,0.769293,24,0.562712
5,mat6POUR,0.687713,0.086357,0.483302,0.938132,0.725622,0.675709,0.049913,0,0.758076,40,0.585389
6,mat7OR,0.626050,0.121458,0.275895,0.967339,0.707638,0.600214,0.107424,22,0.680570,34,0.505732
7,mat8ECCC,0.605078,0.070587,0.408802,0.782888,0.636490,0.595131,0.041359,23,0.672222,27,0.541486
8,mat9N,0.545116,0.271945,0.009061,0.974627,0.616469,0.522521,0.093948,23,0.657807,58,0.188003

==============================
Matrix: mat1PI
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.724338     0.047305     0.620283     0.871801

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.822687,0.000000,0.822687,0.822687
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.727408,0.031599,0.658528,0.825525
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.747925,0.036961,0.657583,0.843122
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.728588,0.047749,0.620283,0.844118

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.687036  0.697884  0.684164
0.2  0.687036       NaN  0.740622  0.733384
0.5  0.697884  0.740622       NaN  0.741539
0.8  0.684164  0.733384  0.741539       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.030047  0.023359  0.030238
0.2  0.030047       NaN  0.033801  0.036095
0.5  0.023359  0.033801       NaN  0.038003
0.8  0.030238  0.036095  0.038003       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.756652            0.714105            0.042547

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             72          0.764633          0.8                   12
1             41          0.754733          0.5                    1
2             51          0.750975          0.5                   11
3             62          0.750219          0.8                    2
4             32          0.746390          0.2                   12
..           ...               ...          ...                  ...
75            29          0.697058          0.2                    9
76            31          0.690964          0.2                   11
77            61          0.685859          0.8                    1
78            55          0.683514          0.5                   15
79            65          0.679363          0.8                    5

[80 rows x 4 columns]

prototype_idx = 72, prototype_score = 0.764633
outlier_idx = 65, outlier_score = 0.679363


==============================
Matrix: mat2FD
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.716978      0.06979     0.478469     0.899641

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.899641,0.000000,0.899641,0.899641
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.705403,0.056754,0.549735,0.859476
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.727735,0.056487,0.588873,0.870697
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.690017,0.063562,0.478469,0.847998

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.717437  0.712938  0.685989
0.2  0.717437       NaN  0.713821  0.689358
0.5  0.712938  0.713821       NaN  0.708752
0.8  0.685989  0.689358  0.708752       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.056838  0.039175  0.048301
0.2  0.056838       NaN  0.044294  0.052605
0.5  0.039175  0.044294       NaN  0.059635
0.8  0.048301  0.052605  0.059635       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.755699            0.704716            0.050983

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             52          0.762603          0.5                   12
1             40          0.753940          0.5                    0
2              0          0.752158          0.0                    0
3              1          0.752158          0.0                    1
4              4          0.752158          0.0                    4
..           ...               ...          ...                  ...
75            45          0.661272          0.5                    5
76            63          0.651875          0.8                    3
77            76          0.643532          0.8                   16
78            31          0.619636          0.2                   11
79            77          0.611800          0.8                   17

[80 rows x 4 columns]

prototype_idx = 52, prototype_score = 0.762603
outlier_idx = 77, outlier_score = 0.611800


==============================
Matrix: mat3RC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.692643     0.092686     0.402741     0.966953

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.966953,0.000000,0.966953,0.966953
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.651356,0.077595,0.497494,0.965641
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.681535,0.066413,0.480212,0.851129
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.682025,0.067705,0.531542,0.884914

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.682147  0.688604  0.675538
0.2  0.682147       NaN  0.664140  0.657777
0.5  0.688604  0.664140       NaN  0.687290
0.8  0.675538  0.657777  0.687290       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.043215  0.044085  0.060682
0.2  0.043215       NaN  0.065695  0.065012
0.5  0.044085  0.065695       NaN  0.074558
0.8  0.060682  0.065012  0.074558       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.745467            0.675916            0.069551

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              1          0.750606          0.0                    1
1              2          0.750606          0.0                    2
2              3          0.750606          0.0                    3
3              4          0.750606          0.0                    4
4              6          0.750606          0.0                    6
..           ...               ...          ...                  ...
75            39          0.629950          0.2                   19
76            29          0.615064          0.2                    9
77            78          0.611797          0.8                   18
78            77          0.609029          0.8                   17
79            43          0.593910          0.5                    3

[80 rows x 4 columns]

prototype_idx = 1, prototype_score = 0.750606
outlier_idx = 43, outlier_score = 0.593910


==============================
Matrix: mat4MS
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0       0.63643     0.097708     0.379752     0.944074

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.944074,0.000000,0.944074,0.944074
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.643131,0.069481,0.497397,0.824007
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.601875,0.054420,0.486581,0.741374
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.615629,0.066180,0.383741,0.755660

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.614873  0.602832  0.611384
0.2  0.614873       NaN  0.626993  0.629261
0.5  0.602832  0.626993       NaN  0.610214
0.8  0.611384  0.629261  0.610214       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.056709  0.049519  0.070455
0.2  0.056709       NaN  0.055072  0.061459
0.5  0.049519  0.055072       NaN  0.058298
0.8  0.070455  0.061459  0.058298       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.701177            0.615926            0.085251

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.690116          0.0                    0
1              1          0.690116          0.0                    1
2              2          0.690116          0.0                    2
3              3          0.690116          0.0                    3
4              4          0.690116          0.0                    4
..           ...               ...          ...                  ...
75            78          0.571298          0.8                   18
76            20          0.566836          0.2                    0
77            40          0.556350          0.5                    0
78            23          0.553592          0.2                    3
79            77          0.497766          0.8                   17

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.690116
outlier_idx = 77, outlier_score = 0.497766


==============================
Matrix: mat5INV
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.683257     0.098597     0.450673     0.959888

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.959888,0.000000,0.959888,0.959888
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.646884,0.074700,0.455340,0.856100
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.638645,0.057773,0.508627,0.822001
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.632667,0.053287,0.493058,0.836742

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.725421  0.702757  0.698637
0.2  0.725421       NaN  0.634850  0.633445
0.5  0.702757  0.634850       NaN  0.635531
0.8  0.698637  0.633445  0.635531       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.066093  0.055844  0.054043
0.2  0.066093       NaN  0.067903  0.065991
0.5  0.055844  0.067903       NaN  0.056617
0.8  0.054043  0.065991  0.056617       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.719521            0.671774            0.047747

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.769293          0.0                    0
1              1          0.769293          0.0                    1
2              2          0.769293          0.0                    2
3              3          0.769293          0.0                    3
4              4          0.769293          0.0                    4
..           ...               ...          ...                  ...
75            48          0.603247          0.5                    8
76            57          0.587943          0.5                   17
77            77          0.575524          0.8                   17
78            34          0.568437          0.2                   14
79            24          0.562712          0.2                    4

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.769293
outlier_idx = 24, outlier_score = 0.562712


==============================
Matrix: mat6POUR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.687713     0.086357     0.483302     0.938132

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.938132,0.000000,0.938132,0.938132
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.680310,0.064865,0.573064,0.861353
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.655313,0.058609,0.523970,0.834708
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.628732,0.060385,0.490291,0.857051

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.722442  0.702503  0.678231
0.2  0.722442       NaN  0.663542  0.646900
0.5  0.702503  0.663542       NaN  0.640637
0.8  0.678231  0.646900  0.640637       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.042544  0.045794  0.034820
0.2  0.042544       NaN  0.064440  0.055543
0.5  0.045794  0.064440       NaN  0.057006
0.8  0.034820  0.055543  0.057006       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.725622            0.675709            0.049913

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.758076          0.0                    0
1              1          0.758076          0.0                    1
2              2          0.758076          0.0                    2
3              3          0.758076          0.0                    3
4              4          0.758076          0.0                    4
..           ...               ...          ...                  ...
75            22          0.610496          0.2                    2
76            74          0.603624          0.8                   14
77            56          0.602012          0.5                   16
78            75          0.599816          0.8                   15
79            40          0.585389          0.5                    0

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.758076
outlier_idx = 40, outlier_score = 0.585389


==============================
Matrix: mat7OR
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0       0.62605     0.121458     0.275895     0.967339

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.967339,0.000000,0.967339,0.967339
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.615742,0.088094,0.275895,0.812858
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.616087,0.076943,0.379285,0.815080
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.631385,0.072542,0.377262,0.857148

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.578721  0.568198  0.578603
0.2  0.578721       NaN  0.614793  0.633357
0.5  0.568198  0.614793       NaN  0.627614
0.8  0.578603  0.633357  0.627614       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.094325  0.115645  0.062076
0.2  0.094325       NaN  0.082105  0.079544
0.5  0.115645  0.082105       NaN  0.069937
0.8  0.062076  0.079544  0.069937       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.707638            0.600214            0.107424

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             22          0.680570          0.2                    2
1             65          0.679443          0.8                    5
2             52          0.677971          0.5                   12
3             42          0.676187          0.5                    2
4             53          0.669536          0.5                   13
..           ...               ...          ...                  ...
75            49          0.547333          0.5                    9
76            54          0.541101          0.5                   14
77            55          0.538702          0.5                   15
78            70          0.527964          0.8                   10
79            34          0.505732          0.2                   14

[80 rows x 4 columns]

prototype_idx = 22, prototype_score = 0.680570
outlier_idx = 34, outlier_score = 0.505732


==============================
Matrix: mat8ECCC
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.605078     0.070587     0.408802     0.782888

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.782888,0.000000,0.782888,0.782888
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.601751,0.070189,0.408802,0.712757
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.580099,0.062333,0.413637,0.738215
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.581222,0.044911,0.455068,0.682125

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.597990  0.600786  0.605440
0.2  0.597990       NaN  0.592077  0.594169
0.5  0.600786  0.592077       NaN  0.580323
0.8  0.605440  0.594169  0.580323       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.042658  0.035671  0.048032
0.2  0.042658       NaN  0.067048  0.064821
0.5  0.035671  0.067048       NaN  0.059682
0.8  0.048032  0.064821  0.059682       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0              0.63649            0.595131            0.041359

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             23          0.672222          0.2                    3
1             24          0.664228          0.2                    4
2             41          0.663210          0.5                    1
3              0          0.645053          0.0                    0
4              4          0.645053          0.0                    4
..           ...               ...          ...                  ...
75            69          0.546296          0.8                    9
76            74          0.546203          0.8                   14
77            76          0.546118          0.8                   16
78            43          0.543540          0.5                    3
79            27          0.541486          0.2                    7

[80 rows x 4 columns]

prototype_idx = 23, prototype_score = 0.672222
outlier_idx = 27, outlier_score = 0.541486


==============================
Matrix: mat9N
==============================

[Method 1] Overall Stability (Off-Diagonal Statistics)

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.545116     0.271945     0.009061     0.974627

[Method 2-A] Within-Temperature Stability

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.972014,0.000000,0.972014,0.972014
1,0.2,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.511326,0.152085,0.019378,0.972014
2,0.5,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.494309,0.253633,0.010076,0.969395
3,0.8,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.488227,0.251700,0.009605,0.974039

[Method 2-B] Between-Temperature Mean Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.505488  0.598501  0.516748
0.2  0.505488       NaN  0.506167  0.514853
0.5  0.598501  0.506167       NaN  0.493370
0.8  0.516748  0.514853  0.493370       NaN

[Method 2-C] Between-Temperature Standard Deviation Matrix

          0.0       0.2       0.5       0.8
0.0       NaN  0.274730  0.317436  0.308771
0.2  0.274730       NaN  0.202542  0.193894
0.5  0.317436  0.202542       NaN  0.249388
0.8  0.308771  0.193894  0.249388       NaN

[Method 2-D] Summary of Temperature Decomposition

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.616469            0.522521            0.093948

[Method 3] Prototype / Outlier Analysis (sorted by row mean offdiag)

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             23          0.657807          0.2                    3
1             42          0.656113          0.5                    2
2             54          0.654971          0.5                   14
3             36          0.653197          0.2                   16
4             40          0.651629          0.5                    0
..           ...               ...          ...                  ...
75            34          0.272689          0.2                   14
76            72          0.269909          0.8                   12
77            77          0.245590          0.8                   17
78            65          0.213099          0.8                    5
79            58          0.188003          0.5                   18

[80 rows x 4 columns]

prototype_idx = 23, prototype_score = 0.657807
outlier_idx = 58, outlier_score = 0.188003


####################################################################################################
Processing question 5/17: Hard P11658
####################################################################################################

================================================================================
题目 index = 5
题目名称 = Hard P11658
矩阵保存目录 = Questions/Hard P11658/CrossEncoder_Results/matrices
================================================================================

===== mat1PI =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat2FD =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat3RC =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat4MS =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat5INV =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat6POUR =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat7OR =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat8ECCC =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

===== mat9N =====
shape = (0, 0)

Empty DataFrame
Columns: []
Index: []

================================================================================
Question index = 5
Question Name = Hard P11658
k = 20
temperature_list = [0.0, 0.2, 0.5, 0.8]
analysis save dir = Questions/Hard P11658/CrossEncoder_Results/analysis
================================================================================

/opt/conda/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/conda/lib/python3.12/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/opt/conda/lib/python3.12/site-packages/numpy/_core/_methods.py:219: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/opt/conda/lib/python3.12/site-packages/numpy/_core/_methods.py:178: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/opt/conda/lib/python3.12/site-packages/numpy/_core/_methods.py:211: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

ValueError: zero-size array to reduction operation minimum which has no identity