In [1]:
from pathlib import Path
import re
from pprint import pprint
from sentence_transformers import CrossEncoder
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

In [2]:
# Questions 目录
QUESTIONS_DIR = Path("./Questions")

# ———————————————————— 参数：拆分用 ————————————————————
# 8 个固定 section
SECTION_TITLES = [
    "Problem Interface",
    "Formal Definitions",
    "Required Complexity",
    "Maintained State",
    "Invariants",
    "Per-Operation Update Rules",
    "Output Rule",
    "Edge Cases and Consistency Checks",
]

SECTION_VARS = {
    "Problem Interface": "ProblemInterface",
    "Formal Definitions": "FormalDefinitions",
    "Required Complexity": "RequiredComplexity",
    "Maintained State": "MaintainedState",
    "Invariants": "Invariants",
    "Per-Operation Update Rules": "PerOperationUpdateRules",
    "Output Rule": "OutputRule",
    "Edge Cases and Consistency Checks": "EdgeCasesAndConsistencyChecks",
}

FIRST_SECTION_MARK = "### [1] Problem Interface"

SECTION_PATTERN = re.compile(
    r"^###\s*\[(\d+)\]\s*(.+?)\s*$",
    re.MULTILINE
)

NUMBERED_STEP_RE = re.compile(r"^\s*\d+\.\s+")



# ———————————————————— 参数：CrossEncoder计算用 ————————————————————
model = CrossEncoder("cross-encoder/stsb-roberta-large")

# 块名顺序
KEY_ORDER = [
    "ProblemInterface",                  # 1
    "FormalDefinitions",                 # 2
    "RequiredComplexity",                # 3
    "MaintainedState",                   # 4
    "Invariants",                        # 5
    "PerOperationUpdateRules",           # 6
    "OutputRule",                        # 7
    "EdgeCasesAndConsistencyChecks",     # 8
    "Note",                              # 9
]

# 对应矩阵变量名
MAT_NAMES = [
    "mat1PI",
    "mat2FD",
    "mat3RC",
    "mat4MS",
    "mat5INV",
    "mat6POUR",
    "mat7OR",
    "mat8ECCC",
    "mat9N",
]

# ———————————————————— 参数：数据分析 ————————————————————

TARGET_Q_INDEX = 0   # 指定打印 / 分析第几个题目（从 0 开始）

# k和temp必须严格与QtoE中的一致
k = 20
temperature_list = [0.2, 0.5, 0.8, 1.0]

ROUND_DIGITS = 6    # 保留几位

# 若只想看部分矩阵，可改成例如 ["mat8ECCC", "mat9N"]
SELECTED_MATS = None

DEFAULT_MAT_NAMES = [
    "mat1PI",    # Problem Interface
    "mat2FD",    # Formal Definitions
    "mat3RC",    # Required Complexity
    "mat4MS",    # Maintained State
    "mat5INV",   # Invariants
    "mat6POUR",  # Per-Operation Update Rules
    "mat7OR",    # Output Rule
    "mat8ECCC",  # Edge Cases and Consistency Checks
    "mat9N",
]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/stsb-roberta-large
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
# 拆分用 函数部分
def list_question_dirs(questions_dir: Path):
    return sorted(
        [p for p in questions_dir.iterdir() if p.is_dir() and not p.name.startswith(".")],
        key=lambda x: x.name
    )


def list_explain_txts(explain_dir: Path):
    txts = []

    for p in explain_dir.iterdir():
        if not (p.is_file() and p.suffix.lower() == ".txt"):
            continue

        parts = p.stem.split()

        if len(parts) >= 1 and parts[0].isdigit():
            txts.append((int(parts[0]), p))

    txts_sorted = sorted(txts, key=lambda x: x[0])
    display(txts_sorted)

    return [p for _, p in txts_sorted]


def remove_blank_lines(text: str) -> str:
    """
    对块内容做空行剔除：删除所有空行，仅保留非空行并按原顺序拼接。
    """
    if not text:
        return ""
    lines = [line for line in text.splitlines() if line.strip() != ""]
    return "\n".join(lines).strip()


def split_into_8_sections(text: str):
    """
    先切出 8 个块。
    舍弃 ### [1] Problem Interface 之前的任何内容。
    返回 dict:
    {
        'ProblemInterface': ...,
        ...
        'EdgeCasesAndConsistencyChecks': ...
    }
    """
    first_idx = text.find(FIRST_SECTION_MARK)
    if first_idx == -1:
        raise ValueError(f"未找到 '{FIRST_SECTION_MARK}'")

    text = text[first_idx:]
    matches = list(SECTION_PATTERN.finditer(text))
    if not matches:
        raise ValueError("未识别到 section 标题")

    parsed = {v: "" for v in SECTION_VARS.values()}

    for i, m in enumerate(matches):
        title = m.group(2).strip()
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        content = text[start:end]

        if title in SECTION_VARS:
            parsed[SECTION_VARS[title]] = content

    return parsed


def extract_note_from_section8(detailed_text: str):
    """
    从第八块中剥离第九块 Note。

    规则：
    1. 先对第八块原始内容处理，不提前删空行。
    2. 只考虑“最后一个由空行分隔出的连续非空块”是否应作为 Note。
    3. 若该最后块内部存在某行匹配 '数字. 空格'（如 5. xxx），
       则说明它属于第八块，不剥离。
    4. 若最后块内部没有编号行，且它前面由空行分隔，则将其剥离为 Note。
    5. 因为是按空行分块，若前面有编号步骤但中间已有空行断开，则最后块不再属于该步骤。
    """
    if not detailed_text.strip():
        return "", ""

    lines = detailed_text.splitlines()

    # 去掉末尾空行，便于找最后非空块
    end = len(lines) - 1
    while end >= 0 and lines[end].strip() == "":
        end -= 1

    if end < 0:
        return "", ""

    # 找最后一个连续非空块 [block_start, end]
    block_start = end
    while block_start >= 0 and lines[block_start].strip() != "":
        block_start -= 1
    block_start += 1

    # 如果整个 detailed 都是一个连续非空块，则不剥离 Note
    if block_start == 0:
        main_text = "\n".join(lines[:end + 1])
        return main_text, ""

    last_block_lines = lines[block_start:end + 1]

    # 若最后块内部含有编号步骤起始行，则它属于第八块
    if any(NUMBERED_STEP_RE.match(line) for line in last_block_lines):
        main_text = "\n".join(lines[:end + 1])
        return main_text, ""

    # 否则，最后块剥离为 Note
    note_text = "\n".join(last_block_lines)
    main_text = "\n".join(lines[:block_start - 1])  # block_start-1 是分隔空行

    return main_text, note_text


def parse_one_explain_file(txt_path: Path):
    """
    处理单个 explain 文件：
    1. 先切分出 8 个块
    2. 对第 8 块做第 9 块 Note 的剥离
    3. 对这 9 块内容统一做空行剔除
    返回：
    {
        'ProblemInterface': ...,
        ...
        'EdgeCasesAndConsistencyChecks': ...,
        'Note': ...
    }
    """
    raw = txt_path.read_text(encoding="utf-8")

    parsed8 = split_into_8_sections(raw)

    detailed_main, note_text = extract_note_from_section8(parsed8["EdgeCasesAndConsistencyChecks"])
    parsed8["EdgeCasesAndConsistencyChecks"] = detailed_main

    parsed9 = dict(parsed8)
    parsed9["Note"] = note_text

    # 最后统一对 9 块做空行剔除
    for key in parsed9:
        parsed9[key] = remove_blank_lines(parsed9[key])

    return parsed9


def parse_question_dir(question_dir: Path):
    """
    对单个题目目录处理。
    返回：
    {
        'ProblemSummary': [file1内容, file2内容, ...],
        ...
        'DetailedAlgorithmSteps': [...],
        'Note': [...]
    }
    """
    explain_dir = question_dir / "LLM Explains"
    if not explain_dir.exists() or not explain_dir.is_dir():
        raise FileNotFoundError(f"{question_dir} 下不存在 'LLM Explains' 文件夹")

    txt_files = list_explain_txts(explain_dir)

    result = {v: [] for v in SECTION_VARS.values()}
    result["Note"] = []

    for txt_path in txt_files:
        parsed = parse_one_explain_file(txt_path)
        for key in result:
            result[key].append(parsed[key])

    return result

In [ ]:
# 遍历
dirs = list_question_dirs(QUESTIONS_DIR)
all_results = {}

for d in dirs:
    try:
        all_results[d.name] = parse_question_dir(d)
        print(f"done: {d.name}")
    except Exception as e:
        print(f"error: {d.name} -> {e}")

if all_results:
    first_name = next(iter(all_results))
    print(f"\n示例题目: {first_name}")
    pprint(all_results[first_name])

In [4]:
# 单独测试
dirs = list_question_dirs(QUESTIONS_DIR)
all_results = {}

d = dirs[0]
try:
    all_results[d.name] = parse_question_dir(d)
    print(f"done: {d.name}")
except Exception as e:
    print(f"error: {d.name} -> {e}")

if all_results:
    first_name = next(iter(all_results))
    print(f"\n示例题目: {first_name}")
    pprint(all_results[first_name])

[(1, PosixPath('Questions/Easy B3666/LLM Explains/1 0.0.txt')),
 (2, PosixPath('Questions/Easy B3666/LLM Explains/2 0.0.txt')),
 (3, PosixPath('Questions/Easy B3666/LLM Explains/3 0.0.txt')),
 (4, PosixPath('Questions/Easy B3666/LLM Explains/4 0.0.txt')),
 (5, PosixPath('Questions/Easy B3666/LLM Explains/5 0.0.txt')),
 (6, PosixPath('Questions/Easy B3666/LLM Explains/6 0.0.txt')),
 (7, PosixPath('Questions/Easy B3666/LLM Explains/7 0.0.txt')),
 (8, PosixPath('Questions/Easy B3666/LLM Explains/8 0.0.txt')),
 (9, PosixPath('Questions/Easy B3666/LLM Explains/9 0.0.txt')),
 (10, PosixPath('Questions/Easy B3666/LLM Explains/10 0.0.txt')),
 (11, PosixPath('Questions/Easy B3666/LLM Explains/11 0.0.txt')),
 (12, PosixPath('Questions/Easy B3666/LLM Explains/12 0.0.txt')),
 (13, PosixPath('Questions/Easy B3666/LLM Explains/13 0.0.txt')),
 (14, PosixPath('Questions/Easy B3666/LLM Explains/14 0.0.txt')),
 (15, PosixPath('Questions/Easy B3666/LLM Explains/15 0.0.txt')),
 (16, PosixPath('Questions/Easy B3666/LLM Explains/16 0.0.txt')),
 (17, PosixPath('Questions/Easy B3666/LLM Explains/17 0.0.txt')),
 (18, PosixPath('Questions/Easy B3666/LLM Explains/18 0.0.txt')),
 (19, PosixPath('Questions/Easy B3666/LLM Explains/19 0.0.txt')),
 (20, PosixPath('Questions/Easy B3666/LLM Explains/20 0.0.txt')),
 (21, PosixPath('Questions/Easy B3666/LLM Explains/21 0.2.txt')),
 (22, PosixPath('Questions/Easy B3666/LLM Explains/22 0.2.txt')),
 (23, PosixPath('Questions/Easy B3666/LLM Explains/23 0.2.txt')),
 (24, PosixPath('Questions/Easy B3666/LLM Explains/24 0.2.txt')),
 (25, PosixPath('Questions/Easy B3666/LLM Explains/25 0.2.txt')),
 (26, PosixPath('Questions/Easy B3666/LLM Explains/26 0.2.txt')),
 (27, PosixPath('Questions/Easy B3666/LLM Explains/27 0.2.txt')),
 (28, PosixPath('Questions/Easy B3666/LLM Explains/28 0.2.txt')),
 (29, PosixPath('Questions/Easy B3666/LLM Explains/29 0.2.txt')),
 (30, PosixPath('Questions/Easy B3666/LLM Explains/30 0.2.txt')),
 (31, PosixPath('Questions/Easy B3666/LLM Explains/31 0.2.txt')),
 (32, PosixPath('Questions/Easy B3666/LLM Explains/32 0.2.txt')),
 (33, PosixPath('Questions/Easy B3666/LLM Explains/33 0.2.txt')),
 (34, PosixPath('Questions/Easy B3666/LLM Explains/34 0.2.txt')),
 (35, PosixPath('Questions/Easy B3666/LLM Explains/35 0.2.txt')),
 (36, PosixPath('Questions/Easy B3666/LLM Explains/36 0.2.txt')),
 (37, PosixPath('Questions/Easy B3666/LLM Explains/37 0.2.txt')),
 (38, PosixPath('Questions/Easy B3666/LLM Explains/38 0.2.txt')),
 (39, PosixPath('Questions/Easy B3666/LLM Explains/39 0.2.txt')),
 (40, PosixPath('Questions/Easy B3666/LLM Explains/40 0.2.txt')),
 (41, PosixPath('Questions/Easy B3666/LLM Explains/41 0.5.txt')),
 (42, PosixPath('Questions/Easy B3666/LLM Explains/42 0.5.txt')),
 (43, PosixPath('Questions/Easy B3666/LLM Explains/43 0.5.txt')),
 (44, PosixPath('Questions/Easy B3666/LLM Explains/44 0.5.txt')),
 (45, PosixPath('Questions/Easy B3666/LLM Explains/45 0.5.txt')),
 (46, PosixPath('Questions/Easy B3666/LLM Explains/46 0.5.txt')),
 (47, PosixPath('Questions/Easy B3666/LLM Explains/47 0.5.txt')),
 (48, PosixPath('Questions/Easy B3666/LLM Explains/48 0.5.txt')),
 (49, PosixPath('Questions/Easy B3666/LLM Explains/49 0.5.txt')),
 (50, PosixPath('Questions/Easy B3666/LLM Explains/50 0.5.txt')),
 (51, PosixPath('Questions/Easy B3666/LLM Explains/51 0.5.txt')),
 (52, PosixPath('Questions/Easy B3666/LLM Explains/52 0.5.txt')),
 (53, PosixPath('Questions/Easy B3666/LLM Explains/53 0.5.txt')),
 (54, PosixPath('Questions/Easy B3666/LLM Explains/54 0.5.txt')),
 (55, PosixPath('Questions/Easy B3666/LLM Explains/55 0.5.txt')),
 (56, PosixPath('Questions/Easy B3666/LLM Explains/56 0.5.txt')),
 (57, PosixPath('Questions/Easy B3666/LLM Explains/57 0.5.txt')),
 (58, PosixPath('Questions/Easy B3666/LLM Explains/58 0.5.txt')),
 (59, PosixPath('Questions/Easy B3666/LLM Explains/59 0.5.txt')),
 (60, PosixPath('Questions/Easy B3666/LLM Explains/60 0.5.txt')),
 (61, PosixPath('Questions/Easy B3666/LLM Explains/61 0.8.txt')),
 (62, PosixPath('Questions/Easy B3666/LLM Explains/62 0.8.txt')),
 (63, PosixPath('Questions/Easy B3666/LLM Explains/63 0.8.txt')),
 (64, PosixPath('Questions/Easy B3666/LLM Explains/64 0.8.txt')),
 (65, PosixPath('Questions/Easy B3666/LLM Explains/65 0.8.txt')),
 (66, PosixPath('Questions/Easy B3666/LLM Explains/66 0.8.txt')),
 (67, PosixPath('Questions/Easy B3666/LLM Explains/67 0.8.txt')),
 (68, PosixPath('Questions/Easy B3666/LLM Explains/68 0.8.txt')),
 (69, PosixPath('Questions/Easy B3666/LLM Explains/69 0.8.txt')),
 (70, PosixPath('Questions/Easy B3666/LLM Explains/70 0.8.txt')),
 (71, PosixPath('Questions/Easy B3666/LLM Explains/71 0.8.txt')),
 (72, PosixPath('Questions/Easy B3666/LLM Explains/72 0.8.txt')),
 (73, PosixPath('Questions/Easy B3666/LLM Explains/73 0.8.txt')),
 (74, PosixPath('Questions/Easy B3666/LLM Explains/74 0.8.txt')),
 (75, PosixPath('Questions/Easy B3666/LLM Explains/75 0.8.txt')),
 (76, PosixPath('Questions/Easy B3666/LLM Explains/76 0.8.txt')),
 (77, PosixPath('Questions/Easy B3666/LLM Explains/77 0.8.txt')),
 (78, PosixPath('Questions/Easy B3666/LLM Explains/78 0.8.txt')),
 (79, PosixPath('Questions/Easy B3666/LLM Explains/79 0.8.txt')),
 (80, PosixPath('Questions/Easy B3666/LLM Explains/80 0.8.txt'))]

done: Easy B3666

示例题目: Easy B3666
{'EdgeCasesAndConsistencyChecks': ['- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '
                                   'stored in `stack` and used in `ans` are '
                                   '1-based, matching the problem statement. '
                                   'No conversion to 0-based indexing is '
                                   'performed at any stage.\n'
                                   '- **Wrong interpretations to avoid**:\n'
                                   '  - Using `≥` instead of `>` in the suffix '
                                   'maximum condition would incorrectly '
                                   'include equal values.\n'
                                   '  - Using `a[stack.top()] < x[k]` (strict) '
                                   'in the while condition would fail to pop '
                                   'equal values, violating the `>` '
                                   'requirement.\n'
                                   '  - Storing values instead of indices in '
                                   'the stack would lose position information '
                                   'needed for XOR.\n'
                                   '  - Outputting the XOR of values instead '
                                   'of indices would be incorrect.\n'
                                   '  - Using 0-based indexing internally and '
                                   'converting at output would introduce '
                                   'off-by-one errors.',
                                   '- **Empty stack handling**: When `stack` '
                                   'is empty before step 2 (only at `k=1`), '
                                   'the while loop is skipped, `k=1` is '
                                   'pushed, and `ans = 0 XOR 1 = 1`, matching '
                                   'sample output first line.\n'
                                   '- **Equality case**: The condition '
                                   '`a[stack.top()] ≤ x[k]` uses non-strict '
                                   'inequality (`≤`), so equal values cause '
                                   'the old index to be popped. This is '
                                   'correct because the definition requires '
                                   '`a_i > a_j` for all `j > i`; if `a_i = '
                                   'a_j`, then `i` is not a suffix maximum.\n'
                                   '- **Single element**: For `k=1`, `S_1 = '
                                   '{1}`, so `ans = 1`.\n'
                                   '- **Strictly decreasing input**: If `x[1] '
                                   '> x[2] > ... > x[n]`, then `stack = [1, 2, '
                                   '..., k]` after `k` operations, and `ans = '
                                   '1 XOR 2 XOR ... XOR k`.\n'
                                   '- **Strictly increasing input**: If `x[1] '
                                   '< x[2] < ... < x[n]`, then after `k` '
                                   'operations, `stack = [k]`, so `ans = k`.\n'
                                   '- **Parsing-unit consistency**: The input '
                                   'must be parsed as one fixed-length block '
                                   'of `n` integers on the second line; '
                                   'interpreting it as `n` separate scalar '
                                   'reads per line (e.g., one integer per '
                                   'line) would be incorrect.\n'
                                   '- **Indexing convention**: All indices '

In [5]:
display(len(all_results))
display(len(all_results["Easy B3666"]))
display(len(all_results["Easy B3666"]["EdgeCasesAndConsistencyChecks"]))
display(all_results["Easy B3666"]["EdgeCasesAndConsistencyChecks"][0])
display(type(all_results))

1

9

80

'- **Empty stack handling**: When `stack` is empty before step 2 (only at `k=1`), the while loop is skipped, `k=1` is pushed, and `ans = 0 XOR 1 = 1`, matching sample output first line.\n- **Equality case**: The condition `a[stack.top()] ≤ x[k]` uses non-strict inequality (`≤`), so equal values cause the old index to be popped. This is correct because the definition requires `a_i > a_j` for all `j > i`; if `a_i = a_j`, then `i` is not a suffix maximum.\n- **Single element**: For `k=1`, `S_1 = {1}`, so `ans = 1`.\n- **Strictly decreasing input**: If `x[1] > x[2] > ... > x[n]`, then `stack = [1, 2, ..., k]` after `k` operations, and `ans = 1 XOR 2 XOR ... XOR k`.\n- **Strictly increasing input**: If `x[1] < x[2] < ... < x[n]`, then after `k` operations, `stack = [k]`, so `ans = k`.\n- **Parsing-unit consistency**: The input must be parsed as one fixed-length block of `n` integers on the second line; interpreting it as `n` separate scalar reads per line (e.g., one integer per line) would be incorrect.\n- **Indexing convention**: All indices stored in `stack` and used in `ans` are 1-based, matching the problem statement. No conversion to 0-based indexing is performed at any stage.\n- **Wrong interpretations to avoid**:\n  - Using `≥` instead of `>` in the suffix maximum condition would incorrectly include equal values.\n  - Using `a[stack.top()] < x[k]` (strict) in the while condition would fail to pop equal values, violating the `>` requirement.\n  - Storing values instead of indices in the stack would lose position information needed for XOR.\n  - Outputting the XOR of values instead of indices would be incorrect.\n  - Using 0-based indexing internally and converting at output would introduce off-by-one errors.'

dict

In [6]:
def build_similarity_matrix(
    text_list,
    batch_size=64,
    show_pair_progress=False,
    matrix_label="",
    matrix_pos=None,
    matrix_total=None
):
    n = len(text_list)
    mat = np.zeros((n, n), dtype=float)

    # 对角线 = 1
    np.fill_diagonal(mat, 1.0)

    # 上三角 pair
    pairs = []
    index_pairs = []
    for i in range(n):
        for j in range(i + 1, n):
            pairs.append((text_list[i], text_list[j]))
            index_pairs.append((i, j))

    total_pairs = len(pairs)

    if pairs:
        all_scores = []

        pair_pbar = None
        if show_pair_progress:
            desc = matrix_label if matrix_label else "pair progress"
            if matrix_pos is not None and matrix_total is not None:
                desc = f"[matrix {matrix_pos}/{matrix_total}] {desc}"
            pair_pbar = tqdm(total=total_pairs, desc=desc, leave=False)

        for start in range(0, total_pairs, batch_size):
            end = min(start + batch_size, total_pairs)
            batch_pairs = pairs[start:end]
            batch_scores = model.predict(batch_pairs)
            all_scores.extend(batch_scores)

            if pair_pbar is not None:
                pair_pbar.update(end - start)

        if pair_pbar is not None:
            pair_pbar.close()

        for (i, j), score in zip(index_pairs, all_scores):
            mat[i, j] = score
            mat[j, i] = score

    return mat

In [7]:
# ===== 主处理 =====

all_matrices = {}  # 每个题目对应9个矩阵

question_names = list(all_results.keys())
num_questions = len(question_names)
num_matrices = len(MAT_NAMES)
total_matrix_jobs = num_questions * num_matrices

overall_pbar = tqdm(total=total_matrix_jobs, desc="All matrices", position=0)

for q_idx, qname in enumerate(tqdm(question_names, desc="Questions", position=1), start=1):
    qdata = all_results[qname]
    mats = {}

    per_question_pbar = tqdm(
        total=num_matrices,
        desc=f"Question {q_idx}/{num_questions}: {qname}",
        position=2,
        leave=False
    )

    for mat_idx, (key, mat_name) in enumerate(zip(KEY_ORDER, MAT_NAMES), start=1):
        texts = qdata[key]

        per_question_pbar.set_postfix_str(f"{mat_idx}/{num_matrices} -> {mat_name}")
        overall_pbar.set_postfix_str(f"{qname} | {mat_name}")

        mat = build_similarity_matrix(
            texts,
            batch_size=64,
            show_pair_progress=True,
            matrix_label=f"{qname} | {mat_name}",
            matrix_pos=mat_idx,
            matrix_total=num_matrices
        )
        mats[mat_name] = mat

        per_question_pbar.update(1)
        overall_pbar.update(1)

    per_question_pbar.close()
    all_matrices[qname] = mats

overall_pbar.close()

All matrices:   0%|          | 0/9 [00:00<?, ?it/s]

Questions:   0%|          | 0/1 [00:00<?, ?it/s]

Question 1/1: Easy B3666:   0%|          | 0/9 [00:00<?, ?it/s]

[matrix 1/9] Easy B3666 | mat1PI:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 2/9] Easy B3666 | mat2FD:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 3/9] Easy B3666 | mat3RC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 4/9] Easy B3666 | mat4MS:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 5/9] Easy B3666 | mat5INV:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 6/9] Easy B3666 | mat6POUR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 7/9] Easy B3666 | mat7OR:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 8/9] Easy B3666 | mat8ECCC:   0%|          | 0/3160 [00:00<?, ?it/s]

[matrix 9/9] Easy B3666 | mat9N:   0%|          | 0/3160 [00:00<?, ?it/s]

In [8]:
# all_matrices打印辅助函数
def get_question_names_from_all_matrices(all_matrices):
    return list(all_matrices.keys())

def get_question_name_by_index(all_matrices, q_index):
    qnames = get_question_names_from_all_matrices(all_matrices)
    if not (0 <= q_index < len(qnames)):
        raise IndexError(f"q_index={q_index} 越界，当前题目总数为 {len(qnames)}")
    return qnames[q_index]

def print_question_matrices(all_matrices, q_index, selected_mats=None, round_digits=6):
    qname = get_question_name_by_index(all_matrices, q_index)
    mats = all_matrices[qname]

    mat_names = selected_mats if selected_mats is not None else list(mats.keys())

    print(f"题目 index = {q_index}")
    print(f"题目名称 = {qname}")

    for mat_name in mat_names:
        print(f"\n===== {mat_name} =====")
        mat = mats[mat_name]
        print(f"shape = {mat.shape}")
        display(pd.DataFrame(mat).round(round_digits))

In [9]:
# 直接打印指定题目的矩阵
print_question_matrices(
    all_matrices,
    q_index=TARGET_Q_INDEX,
    selected_mats=SELECTED_MATS,
    round_digits=ROUND_DIGITS
)

题目 index = 0
题目名称 = Easy B3666

===== mat1PI =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.695320,0.716941,0.716832,0.669096,0.696973,0.759664,0.764109,0.689242,0.758000,0.771218
1,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.695320,0.716941,0.716832,0.669096,0.696973,0.759664,0.764109,0.689242,0.758000,0.771218
2,0.932416,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.695320,0.716941,0.716832,0.669096,0.696973,0.759664,0.764109,0.689242,0.758000,0.771218
3,0.932416,0.932416,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.695320,0.716941,0.716832,0.669096,0.696973,0.759664,0.764109,0.689242,0.758000,0.771218
4,0.932416,0.932416,0.932416,0.932416,1.000000,0.932416,0.932416,0.932416,0.932416,0.932416,...,0.695320,0.716941,0.716832,0.669096,0.696973,0.759664,0.764109,0.689242,0.758000,0.771218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.759664,0.759664,0.759664,0.759664,0.759664,0.759664,0.759664,0.759664,0.759664,0.759664,...,0.772107,0.791569,0.796816,0.654264,0.726233,1.000000,0.751090,0.759514,0.791987,0.748616
76,0.764109,0.764109,0.764109,0.764109,0.764109,0.764109,0.764109,0.764109,0.764109,0.764109,...,0.791621,0.726358,0.724059,0.745811,0.719573,0.751090,1.000000,0.698055,0.757050,0.739174
77,0.689242,0.689242,0.689242,0.689242,0.689242,0.689242,0.689242,0.689242,0.689242,0.689242,...,0.758095,0.719353,0.729890,0.630015,0.699534,0.759514,0.698055,1.000000,0.732666,0.710782
78,0.758000,0.758000,0.758000,0.758000,0.758000,0.758000,0.758000,0.758000,0.758000,0.758000,...,0.778764,0.803108,0.792835,0.688470,0.742332,0.791987,0.757050,0.732666,1.000000,0.732805
79,0.771218,0.771218,0.771218,0.771218,0.771218,0.771218,0.771218,0.771218,0.771218,0.771218,...,0.746021,0.740623,0.729409,0.626976,0.698233,0.748616,0.739174,0.710782,0.732805,1.000000

===== mat2FD =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.773778,0.748867,0.843570,0.690744,0.773260,0.758459,0.799477,0.741896,0.714469,0.755040
1,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.773778,0.748867,0.843570,0.690744,0.773260,0.758459,0.799477,0.741896,0.714469,0.755040
2,0.937798,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.773778,0.748867,0.843570,0.690744,0.773260,0.758459,0.799477,0.741896,0.714469,0.755040
3,0.937798,0.937798,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.773778,0.748867,0.843570,0.690744,0.773260,0.758459,0.799477,0.741896,0.714469,0.755040
4,0.937798,0.937798,0.937798,0.937798,1.000000,0.937798,0.937798,0.937798,0.937798,0.937798,...,0.773778,0.748867,0.843570,0.690744,0.773260,0.758459,0.799477,0.741896,0.714469,0.755040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.758459,0.758459,0.758459,0.758459,0.758459,0.758459,0.758459,0.758459,0.758459,0.758459,...,0.713197,0.764530,0.724217,0.667634,0.671102,1.000000,0.709998,0.700970,0.614311,0.737985
76,0.799477,0.799477,0.799477,0.799477,0.799477,0.799477,0.799477,0.799477,0.799477,0.799477,...,0.720155,0.734196,0.821989,0.696146,0.768715,0.709998,1.000000,0.760787,0.692780,0.724551
77,0.741896,0.741896,0.741896,0.741896,0.741896,0.741896,0.741896,0.741896,0.741896,0.741896,...,0.746210,0.713376,0.734469,0.708020,0.732192,0.700970,0.760787,1.000000,0.621755,0.661563
78,0.714469,0.714469,0.714469,0.714469,0.714469,0.714469,0.714469,0.714469,0.714469,0.714469,...,0.630301,0.639165,0.733173,0.614616,0.739012,0.614311,0.692780,0.621755,1.000000,0.551664
79,0.755040,0.755040,0.755040,0.755040,0.755040,0.755040,0.755040,0.755040,0.755040,0.755040,...,0.735451,0.744765,0.743611,0.641827,0.659004,0.737985,0.724551,0.661563,0.551664,1.000000

===== mat3RC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.524692,0.635462,0.617514,0.603964,0.434137,0.666278,0.542059,0.682732,0.633976,0.553687
1,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.524692,0.635462,0.617514,0.603964,0.434137,0.666278,0.542059,0.682732,0.633976,0.553687
2,0.940892,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.524692,0.635462,0.617514,0.603964,0.434137,0.666278,0.542059,0.682732,0.633976,0.553687
3,0.940892,0.940892,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.524692,0.635462,0.617514,0.603964,0.434137,0.666278,0.542059,0.682732,0.633976,0.553687
4,0.940892,0.940892,0.940892,0.940892,1.000000,0.940892,0.940892,0.940892,0.940892,0.940892,...,0.524692,0.635462,0.617514,0.603964,0.434137,0.666278,0.542059,0.682732,0.633976,0.553687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.666278,0.666278,0.666278,0.666278,0.666278,0.666278,0.666278,0.666278,0.666278,0.666278,...,0.648555,0.580427,0.534291,0.654864,0.486638,1.000000,0.620825,0.750871,0.606504,0.587700
76,0.542059,0.542059,0.542059,0.542059,0.542059,0.542059,0.542059,0.542059,0.542059,0.542059,...,0.503113,0.563967,0.499227,0.621263,0.636016,0.620825,1.000000,0.651287,0.520704,0.566006
77,0.682732,0.682732,0.682732,0.682732,0.682732,0.682732,0.682732,0.682732,0.682732,0.682732,...,0.640414,0.707775,0.663972,0.719151,0.623508,0.750871,0.651287,1.000000,0.630452,0.652412
78,0.633976,0.633976,0.633976,0.633976,0.633976,0.633976,0.633976,0.633976,0.633976,0.633976,...,0.639262,0.631877,0.585813,0.561608,0.415741,0.606504,0.520704,0.630452,1.000000,0.591497
79,0.553687,0.553687,0.553687,0.553687,0.553687,0.553687,0.553687,0.553687,0.553687,0.553687,...,0.592823,0.555762,0.564151,0.650259,0.514811,0.587700,0.566006,0.652412,0.591497,1.000000

===== mat4MS =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.759665,0.731134,0.678202,0.698510,0.610279,0.738768,0.680271,0.740797,0.792343,0.700738
1,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.759665,0.731134,0.678202,0.698510,0.610279,0.738768,0.680271,0.740797,0.792343,0.700738
2,0.909813,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.759665,0.731134,0.678202,0.698510,0.610279,0.738768,0.680271,0.740797,0.792343,0.700738
3,0.909813,0.909813,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.759665,0.731134,0.678202,0.698510,0.610279,0.738768,0.680271,0.740797,0.792343,0.700738
4,0.909813,0.909813,0.909813,0.909813,1.000000,0.909813,0.909813,0.909813,0.909813,0.909813,...,0.759665,0.731134,0.678202,0.698510,0.610279,0.738768,0.680271,0.740797,0.792343,0.700738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.738768,0.738768,0.738768,0.738768,0.738768,0.738768,0.738768,0.738768,0.738768,0.738768,...,0.658718,0.628059,0.644223,0.653624,0.738440,1.000000,0.698661,0.696796,0.747644,0.678784
76,0.680271,0.680271,0.680271,0.680271,0.680271,0.680271,0.680271,0.680271,0.680271,0.680271,...,0.695213,0.670927,0.629448,0.638540,0.667340,0.698661,1.000000,0.652746,0.663941,0.675415
77,0.740797,0.740797,0.740797,0.740797,0.740797,0.740797,0.740797,0.740797,0.740797,0.740797,...,0.696575,0.656212,0.673483,0.677490,0.685615,0.696796,0.652746,1.000000,0.637785,0.668990
78,0.792343,0.792343,0.792343,0.792343,0.792343,0.792343,0.792343,0.792343,0.792343,0.792343,...,0.695536,0.689675,0.656149,0.644735,0.656707,0.747644,0.663941,0.637785,1.000000,0.714440
79,0.700738,0.700738,0.700738,0.700738,0.700738,0.700738,0.700738,0.700738,0.700738,0.700738,...,0.694835,0.688719,0.634606,0.680964,0.720147,0.678784,0.675415,0.668990,0.714440,1.000000

===== mat5INV =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.686350,0.736246,0.724860,0.728307,0.683278,0.784171,0.741842,0.655787,0.796638,0.684180
1,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.686350,0.736246,0.724860,0.728307,0.683278,0.784171,0.741842,0.655787,0.796638,0.684180
2,0.955818,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.686350,0.736246,0.724860,0.728307,0.683278,0.784171,0.741842,0.655787,0.796638,0.684180
3,0.955818,0.955818,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.686350,0.736246,0.724860,0.728307,0.683278,0.784171,0.741842,0.655787,0.796638,0.684180
4,0.955818,0.955818,0.955818,0.955818,1.000000,0.955818,0.955818,0.955818,0.955818,0.955818,...,0.686350,0.736246,0.724860,0.728307,0.683278,0.784171,0.741842,0.655787,0.796638,0.684180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.784171,0.784171,0.784171,0.784171,0.784171,0.784171,0.784171,0.784171,0.784171,0.784171,...,0.645415,0.709944,0.637340,0.624637,0.614003,1.000000,0.664469,0.672799,0.767496,0.711708
76,0.741842,0.741842,0.741842,0.741842,0.741842,0.741842,0.741842,0.741842,0.741842,0.741842,...,0.611277,0.619424,0.596900,0.572748,0.555317,0.664469,1.000000,0.566633,0.654116,0.560184
77,0.655787,0.655787,0.655787,0.655787,0.655787,0.655787,0.655787,0.655787,0.655787,0.655787,...,0.586304,0.641775,0.573042,0.616743,0.620517,0.672799,0.566633,1.000000,0.688981,0.604788
78,0.796638,0.796638,0.796638,0.796638,0.796638,0.796638,0.796638,0.796638,0.796638,0.796638,...,0.605679,0.698221,0.516340,0.706082,0.690544,0.767496,0.654116,0.688981,1.000000,0.667297
79,0.684180,0.684180,0.684180,0.684180,0.684180,0.684180,0.684180,0.684180,0.684180,0.684180,...,0.696133,0.674635,0.639662,0.589596,0.577617,0.711708,0.560184,0.604788,0.667297,1.000000

===== mat6POUR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.658911,0.655186,0.649891,0.604305,0.639488,0.624334,0.626642,0.666404,0.665145,0.647151
1,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.658911,0.655186,0.649891,0.604305,0.639488,0.624334,0.626642,0.666404,0.665145,0.647151
2,0.895031,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.658911,0.655186,0.649891,0.604305,0.639488,0.624334,0.626642,0.666404,0.665145,0.647151
3,0.895031,0.895031,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.658911,0.655186,0.649891,0.604305,0.639488,0.624334,0.626642,0.666404,0.665145,0.647151
4,0.895031,0.895031,0.895031,0.895031,1.000000,0.895031,0.895031,0.895031,0.895031,0.895031,...,0.658911,0.655186,0.649891,0.604305,0.639488,0.624334,0.626642,0.666404,0.665145,0.647151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.624334,0.624334,0.624334,0.624334,0.624334,0.624334,0.624334,0.624334,0.624334,0.624334,...,0.730721,0.707267,0.663044,0.549431,0.621252,1.000000,0.629133,0.688059,0.641418,0.662579
76,0.626642,0.626642,0.626642,0.626642,0.626642,0.626642,0.626642,0.626642,0.626642,0.626642,...,0.642289,0.641913,0.629856,0.587236,0.651833,0.629133,1.000000,0.642648,0.651287,0.613309
77,0.666404,0.666404,0.666404,0.666404,0.666404,0.666404,0.666404,0.666404,0.666404,0.666404,...,0.683984,0.615333,0.650741,0.581719,0.628509,0.688059,0.642648,1.000000,0.634283,0.623425
78,0.665145,0.665145,0.665145,0.665145,0.665145,0.665145,0.665145,0.665145,0.665145,0.665145,...,0.664628,0.688205,0.648801,0.623145,0.636811,0.641418,0.651287,0.634283,1.000000,0.737021
79,0.647151,0.647151,0.647151,0.647151,0.647151,0.647151,0.647151,0.647151,0.647151,0.647151,...,0.641361,0.654155,0.654343,0.553902,0.660228,0.662579,0.613309,0.623425,0.737021,1.000000

===== mat7OR =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.718238,0.626850,0.694747,0.722070,0.759434,0.726258,0.760949,0.719407,0.656245,0.711006
1,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.718238,0.626850,0.694747,0.722070,0.759434,0.726258,0.760949,0.719407,0.656245,0.711006
2,0.969586,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.718238,0.626850,0.694747,0.722070,0.759434,0.726258,0.760949,0.719407,0.656245,0.711006
3,0.969586,0.969586,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.718238,0.626850,0.694747,0.722070,0.759434,0.726258,0.760949,0.719407,0.656245,0.711006
4,0.969586,0.969586,0.969586,0.969586,1.000000,0.969586,0.969586,0.969586,0.969586,0.969586,...,0.718238,0.626850,0.694747,0.722070,0.759434,0.726258,0.760949,0.719407,0.656245,0.711006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.726258,0.726258,0.726258,0.726258,0.726258,0.726258,0.726258,0.726258,0.726258,0.726258,...,0.723537,0.680386,0.756966,0.768534,0.731399,1.000000,0.670968,0.713507,0.692825,0.749900
76,0.760949,0.760949,0.760949,0.760949,0.760949,0.760949,0.760949,0.760949,0.760949,0.760949,...,0.736625,0.588706,0.703802,0.712539,0.756294,0.670968,1.000000,0.672919,0.681523,0.750151
77,0.719407,0.719407,0.719407,0.719407,0.719407,0.719407,0.719407,0.719407,0.719407,0.719407,...,0.738360,0.601929,0.656761,0.741130,0.694270,0.713507,0.672919,1.000000,0.705374,0.740792
78,0.656245,0.656245,0.656245,0.656245,0.656245,0.656245,0.656245,0.656245,0.656245,0.656245,...,0.683410,0.777033,0.646464,0.705929,0.688202,0.692825,0.681523,0.705374,1.000000,0.660659
79,0.711006,0.711006,0.711006,0.711006,0.711006,0.711006,0.711006,0.711006,0.711006,0.711006,...,0.718929,0.690267,0.769071,0.744769,0.738559,0.749900,0.750151,0.740792,0.660659,1.000000

===== mat8ECCC =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.615638,0.551050,0.588522,0.551050,0.565589,0.551050,0.503895,0.551050,0.531726,0.532147
1,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.615638,0.551050,0.588522,0.551050,0.565589,0.551050,0.503895,0.551050,0.531726,0.532147
2,0.750305,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.615638,0.551050,0.588522,0.551050,0.565589,0.551050,0.503895,0.551050,0.531726,0.532147
3,0.750305,0.750305,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.615638,0.551050,0.588522,0.551050,0.565589,0.551050,0.503895,0.551050,0.531726,0.532147
4,0.750305,0.750305,0.750305,0.750305,1.000000,0.750305,0.750305,0.750305,0.750305,0.750305,...,0.615638,0.551050,0.588522,0.551050,0.565589,0.551050,0.503895,0.551050,0.531726,0.532147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,...,0.598907,0.479259,0.551693,0.479259,0.602015,1.000000,0.474422,0.479259,0.553993,0.544148
76,0.503895,0.503895,0.503895,0.503895,0.503895,0.503895,0.503895,0.503895,0.503895,0.503895,...,0.564079,0.474422,0.538667,0.474422,0.593081,0.474422,1.000000,0.470744,0.471246,0.483160
77,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,0.551050,...,0.598907,0.479259,0.551693,0.479259,0.602015,0.479259,0.470744,1.000000,0.553993,0.544148
78,0.531726,0.531726,0.531726,0.531726,0.531726,0.531726,0.531726,0.531726,0.531726,0.531726,...,0.644030,0.553993,0.599586,0.553993,0.661027,0.553993,0.471246,0.553993,1.000000,0.544167
79,0.532147,0.532147,0.532147,0.532147,0.532147,0.532147,0.532147,0.532147,0.532147,0.532147,...,0.584048,0.544148,0.593957,0.544148,0.606550,0.544148,0.483160,0.544148,0.544167,1.000000

===== mat9N =====
shape = (80, 80)

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.167298,0.537582,0.852922,0.514697,0.188095,0.503325,0.914486,0.500383,0.557442,0.161998
1,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.167298,0.537582,0.852922,0.514697,0.188095,0.503325,0.914486,0.500383,0.557442,0.161998
2,0.972504,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.167298,0.537582,0.852922,0.514697,0.188095,0.503325,0.914486,0.500383,0.557442,0.161998
3,0.972504,0.972504,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.167298,0.537582,0.852922,0.514697,0.188095,0.503325,0.914486,0.500383,0.557442,0.161998
4,0.972504,0.972504,0.972504,0.972504,1.000000,0.972504,0.972504,0.972504,0.972504,0.972504,...,0.167298,0.537582,0.852922,0.514697,0.188095,0.503325,0.914486,0.500383,0.557442,0.161998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.503325,0.503325,0.503325,0.503325,0.503325,0.503325,0.503325,0.503325,0.503325,0.503325,...,0.531074,0.631128,0.494148,0.596874,0.569007,1.000000,0.568340,0.565726,0.553305,0.594106
76,0.914486,0.914486,0.914486,0.914486,0.914486,0.914486,0.914486,0.914486,0.914486,0.914486,...,0.262547,0.527567,0.860348,0.512851,0.016841,0.568340,1.000000,0.504921,0.554996,0.117315
77,0.500383,0.500383,0.500383,0.500383,0.500383,0.500383,0.500383,0.500383,0.500383,0.500383,...,0.524476,0.611775,0.500420,0.589442,0.543453,0.565726,0.504921,1.000000,0.526461,0.541894
78,0.557442,0.557442,0.557442,0.557442,0.557442,0.557442,0.557442,0.557442,0.557442,0.557442,...,0.614317,0.590539,0.549248,0.534273,0.603387,0.553305,0.554996,0.526461,1.000000,0.616634
79,0.161998,0.161998,0.161998,0.161998,0.161998,0.161998,0.161998,0.161998,0.161998,0.161998,...,0.275409,0.558393,0.151134,0.505439,0.190682,0.594106,0.117315,0.541894,0.616634,1.000000

In [10]:
# =============================
# 三种分析方法：辅助函数
# =============================

import numpy as np
import pandas as pd

def check_matrix_and_build_groups(mat, k, temperature_list):
    n = mat.shape[0]
    expected_n = k * len(temperature_list)

    if mat.shape[0] != mat.shape[1]:
        raise ValueError(f"矩阵不是方阵，shape={mat.shape}")

    if n != expected_n:
        raise ValueError(
            f"矩阵大小与参数不匹配：matrix_n={n}, "
            f"但 k * len(temperature_list) = {k} * {len(temperature_list)} = {expected_n}"
        )

    # 顺序约定：
    # [0:k) -> temperature_list[0]
    # [k:2k) -> temperature_list[1]
    # ...
    temp_to_indices = {}
    for ti, temp in enumerate(temperature_list):
        start = ti * k
        end = start + k
        temp_to_indices[temp] = list(range(start, end))

    return temp_to_indices


def get_offdiag_values(mat):
    n = mat.shape[0]
    mask = ~np.eye(n, dtype=bool)
    return mat[mask]


def get_upper_triangle_values(submat):
    n = submat.shape[0]
    vals = []
    for i in range(n):
        for j in range(i + 1, n):
            vals.append(submat[i, j])
    return np.array(vals, dtype=float)


# -----------------------------
# 方法1：整体稳定性
# -----------------------------
def method1_global_stats(mat):
    vals = get_offdiag_values(mat)

    return {
        "offdiag_mean": float(np.mean(vals)),
        "offdiag_std": float(np.std(vals)),
        "offdiag_min": float(np.min(vals)),
        "offdiag_max": float(np.max(vals)),
    }


# -----------------------------
# 方法2：温度内 / 温度间分解
# -----------------------------
def method2_temperature_decomposition(mat, k, temperature_list):
    temp_to_indices = check_matrix_and_build_groups(mat, k, temperature_list)

    # 1) 每个温度内部（within-temp）
    within_rows = []
    within_all_vals = []

    for temp in temperature_list:
        idxs = temp_to_indices[temp]
        submat = mat[np.ix_(idxs, idxs)]
        vals = get_upper_triangle_values(submat)

        within_rows.append({
            "temperature": temp,
            "sample_indices": idxs,
            "within_mean": float(np.mean(vals)) if len(vals) > 0 else np.nan,
            "within_std": float(np.std(vals)) if len(vals) > 0 else np.nan,
            "within_min": float(np.min(vals)) if len(vals) > 0 else np.nan,
            "within_max": float(np.max(vals)) if len(vals) > 0 else np.nan,
        })

        within_all_vals.extend(vals.tolist())

    within_df = pd.DataFrame(within_rows)

    # 2) 不同温度之间（cross-temp）
    cross_mean = pd.DataFrame(index=temperature_list, columns=temperature_list, dtype=float)
    cross_std = pd.DataFrame(index=temperature_list, columns=temperature_list, dtype=float)

    cross_all_vals = []

    for i, temp_i in enumerate(temperature_list):
        idx_i = temp_to_indices[temp_i]

        for j, temp_j in enumerate(temperature_list):
            idx_j = temp_to_indices[temp_j]

            if i == j:
                cross_mean.loc[temp_i, temp_j] = np.nan
                cross_std.loc[temp_i, temp_j] = np.nan
                continue

            vals = []
            for a in idx_i:
                for b in idx_j:
                    vals.append(mat[a, b])

            vals = np.array(vals, dtype=float)
            cross_mean.loc[temp_i, temp_j] = float(np.mean(vals))
            cross_std.loc[temp_i, temp_j] = float(np.std(vals))

            # 只累计上三角温度对，避免重复
            if i < j:
                cross_all_vals.extend(vals.tolist())

    overall_within_mean = float(np.mean(within_all_vals)) if len(within_all_vals) > 0 else np.nan
    overall_cross_mean = float(np.mean(cross_all_vals)) if len(cross_all_vals) > 0 else np.nan

    summary = {
        "overall_within_mean": overall_within_mean,
        "overall_cross_mean": overall_cross_mean,
        "within_minus_cross": (
            overall_within_mean - overall_cross_mean
            if (not np.isnan(overall_within_mean) and not np.isnan(overall_cross_mean))
            else np.nan
        )
    }

    return {
        "within_df": within_df,
        "cross_mean_df": cross_mean,
        "cross_std_df": cross_std,
        "summary": summary,
    }


# -----------------------------
# 方法3：原型 / 离群分析
# -----------------------------
def method3_prototype_outlier(mat, k=None, temperature_list=None):
    n = mat.shape[0]

    row_mean_offdiag = (np.sum(mat, axis=1) - np.diag(mat)) / (n - 1)

    df = pd.DataFrame({
        "sample_index": np.arange(n),
        "row_mean_offdiag": row_mean_offdiag,
    })

    if k is not None and temperature_list is not None:
        expected_n = k * len(temperature_list)
        if expected_n == n:
            df["temperature"] = [temperature_list[i // k] for i in range(n)]
            df["local_index_in_temp"] = [i % k for i in range(n)]

    prototype_idx = int(np.argmax(row_mean_offdiag))
    outlier_idx = int(np.argmin(row_mean_offdiag))

    df = df.sort_values("row_mean_offdiag", ascending=False).reset_index(drop=True)

    return {
        "row_mean_df": df,
        "prototype_idx": prototype_idx,
        "prototype_score": float(row_mean_offdiag[prototype_idx]),
        "outlier_idx": outlier_idx,
        "outlier_score": float(row_mean_offdiag[outlier_idx]),
    }


# -----------------------------
# 汇总：单个矩阵三种分析
# -----------------------------
def analyze_one_matrix(mat, k, temperature_list):
    m1 = method1_global_stats(mat)
    m2 = method2_temperature_decomposition(mat, k, temperature_list)
    m3 = method3_prototype_outlier(mat, k=k, temperature_list=temperature_list)

    overview = {
        **m1,
        **m2["summary"],
        "prototype_idx": m3["prototype_idx"],
        "prototype_score": m3["prototype_score"],
        "outlier_idx": m3["outlier_idx"],
        "outlier_score": m3["outlier_score"],
    }

    return {
        "overview": overview,
        "method1": m1,
        "method2": m2,
        "method3": m3,
    }

In [11]:
# =============================
# 对指定题目的所有矩阵做分析
# =============================

def analyze_question_matrices(all_matrices, q_index, k, temperature_list, selected_mats=None, round_digits=6):
    qname = get_question_name_by_index(all_matrices, q_index)
    mats = all_matrices[qname]

    mat_names = selected_mats if selected_mats is not None else list(mats.keys())

    print(f"题目 index = {q_index}")
    print(f"题目名称 = {qname}")
    print(f"k = {k}")
    print(f"temperature_list = {temperature_list}")

    overview_rows = []
    stat_results = {}

    for mat_name in mat_names:
        mat = mats[mat_name]
        result = analyze_one_matrix(mat, k, temperature_list)
        stat_results[mat_name] = result

        overview_row = {"matrix": mat_name}
        overview_row.update(result["overview"])
        overview_rows.append(overview_row)

    overview_df = pd.DataFrame(overview_rows)
    print("\n===== 总览表 =====")
    display(overview_df.round(round_digits))

    for mat_name in mat_names:
        result = stat_results[mat_name]

        print(f"\n\n==============================")
        print(f"矩阵: {mat_name}")
        print(f"==============================")

        print("\n[方法1] 整体稳定性（非对角元素统计）")
        display(pd.DataFrame([result["method1"]]).round(round_digits))

        print("\n[方法2-A] 温度内稳定性")
        display(result["method2"]["within_df"].round(round_digits))

        print("\n[方法2-B] 温度间均值矩阵")
        display(result["method2"]["cross_mean_df"].round(round_digits))

        print("\n[方法2-C] 温度间标准差矩阵")
        display(result["method2"]["cross_std_df"].round(round_digits))

        print("\n[方法2-D] 温度分解汇总")
        display(pd.DataFrame([result["method2"]["summary"]]).round(round_digits))

        print("\n[方法3] 原型 / 离群分析（按 row mean offdiag 排序）")
        display(result["method3"]["row_mean_df"].round(round_digits))

        print(
            f"prototype_idx = {result['method3']['prototype_idx']}, "
            f"prototype_score = {result['method3']['prototype_score']:.{round_digits}f}"
        )
        print(
            f"outlier_idx = {result['method3']['outlier_idx']}, "
            f"outlier_score = {result['method3']['outlier_score']:.{round_digits}f}"
        )

    return overview_df, stat_results


overview_df, stat_results = analyze_question_matrices(
    all_matrices=all_matrices,
    q_index=TARGET_Q_INDEX,
    k=k,
    temperature_list=temperature_list,
    selected_mats=SELECTED_MATS,
    round_digits=ROUND_DIGITS
)

题目 index = 0
题目名称 = Easy B3666
k = 20
temperature_list = [0.2, 0.5, 0.8, 1.0]

===== 总览表 =====

,matrix,offdiag_mean,offdiag_std,offdiag_min,offdiag_max,overall_within_mean,overall_cross_mean,within_minus_cross,prototype_idx,prototype_score,outlier_idx,outlier_score
0,mat1PI,0.757690,0.058490,0.600664,0.932416,0.793663,0.746298,0.047366,0,0.790566,73,0.678953
1,mat2FD,0.737014,0.080047,0.513030,0.937798,0.759622,0.729855,0.029767,0,0.803925,39,0.625806
2,mat3RC,0.635470,0.105595,0.399533,0.962741,0.701351,0.614607,0.086744,1,0.701264,74,0.493384
3,mat4MS,0.708719,0.068221,0.537351,0.909813,0.735524,0.700230,0.035294,0,0.765795,64,0.623357
4,mat5INV,0.692119,0.088029,0.496809,0.955818,0.729639,0.680237,0.049402,0,0.770258,65,0.587802
5,mat6POUR,0.661442,0.068497,0.527780,0.895031,0.714744,0.644563,0.070181,0,0.699297,55,0.602677
6,mat7OR,0.708271,0.083142,0.524267,0.969586,0.766809,0.689734,0.077075,63,0.762219,48,0.631991
7,mat8ECCC,0.575143,0.064746,0.436574,0.800816,0.613537,0.562986,0.050551,51,0.663793,76,0.514582
8,mat9N,0.543311,0.245823,0.009193,0.972853,0.618194,0.519598,0.098595,50,0.648622,63,0.254095

==============================
矩阵: mat1PI
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0       0.75769      0.05849     0.600664     0.932416

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.932416,0.000000,0.932416,0.932416
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.744845,0.041015,0.626614,0.836562
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.765159,0.034365,0.677684,0.861726
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.732234,0.041479,0.626976,0.838072

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.741639  0.753305  0.741997
0.5  0.741639       NaN  0.754462  0.739328
0.8  0.753305  0.754462       NaN  0.747056
1.0  0.741997  0.739328  0.747056       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.036951  0.025817  0.037703
0.5  0.036951       NaN  0.042067  0.043878
0.8  0.025817  0.042067       NaN  0.042467
1.0  0.037703  0.043878  0.042467       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.793663            0.746298            0.047366

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.790566          0.2                    0
1              1          0.790566          0.2                    1
2              2          0.790566          0.2                    2
3              3          0.790566          0.2                    3
4              4          0.790566          0.2                    4
..           ...               ...          ...                  ...
75            34          0.712861          0.5                   14
76            77          0.705279          1.0                   17
77            31          0.698380          0.5                   11
78            35          0.685445          0.5                   15
79            73          0.678953          1.0                   13

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.790566
outlier_idx = 73, outlier_score = 0.678953


==============================
矩阵: mat2FD
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.737014     0.080047      0.51303     0.937798

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.937798,0.000000,0.937798,0.937798
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.721624,0.071207,0.538051,0.908299
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.688590,0.060843,0.556992,0.836194
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.690475,0.066724,0.538755,0.884157

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.769530  0.755675  0.759390
0.5  0.769530       NaN  0.704156  0.697738
0.8  0.755675  0.704156       NaN  0.692640
1.0  0.759390  0.697738  0.692640       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.042255  0.040341  0.038636
0.5  0.042255       NaN  0.063517  0.063977
0.8  0.040341  0.063517       NaN  0.058337
1.0  0.038636  0.063977  0.058337       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.759622            0.729855            0.029767

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.803925          0.2                    0
1              1          0.803925          0.2                    1
2              2          0.803925          0.2                    2
3              3          0.803925          0.2                    3
4              4          0.803925          0.2                    4
..           ...               ...          ...                  ...
75            63          0.673135          1.0                    3
76            73          0.671813          1.0                   13
77            47          0.651580          0.8                    7
78            64          0.640024          1.0                    4
79            39          0.625806          0.5                   19

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.803925
outlier_idx = 39, outlier_score = 0.625806


==============================
矩阵: mat3RC
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0       0.63547     0.105595     0.399533     0.962741

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.940892,0.000000,0.940892,0.940892
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.650253,0.097021,0.457841,0.962741
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.639859,0.065992,0.460453,0.791716
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.574401,0.071719,0.415741,0.793735

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.651661  0.628881  0.595603
0.5  0.651661       NaN  0.628103  0.582080
0.8  0.628881  0.628103       NaN  0.601314
1.0  0.595603  0.582080  0.601314       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.068780  0.054788  0.060422
0.5  0.068780       NaN  0.078941  0.071208
0.8  0.054788  0.078941       NaN  0.065258
1.0  0.060422  0.071208  0.065258       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.701351            0.614607            0.086744

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              1          0.701264          0.2                    1
1              3          0.701264          0.2                    3
2              5          0.701264          0.2                    5
3              4          0.701264          0.2                    4
4              6          0.701264          0.2                    6
..           ...               ...          ...                  ...
75            39          0.552427          0.5                   19
76            52          0.537984          0.8                   12
77            63          0.532758          1.0                    3
78            70          0.526344          1.0                   10
79            74          0.493384          1.0                   14

[80 rows x 4 columns]

prototype_idx = 1, prototype_score = 0.701264
outlier_idx = 74, outlier_score = 0.493384


==============================
矩阵: mat4MS
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.708719     0.068221     0.537351     0.909813

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.909813,0.00000,0.909813,0.909813
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.702951,0.04384,0.583266,0.861091
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.670813,0.03309,0.580387,0.766525
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.658521,0.04100,0.537351,0.795274

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.737537  0.708217  0.714813
0.5  0.737537       NaN  0.685663  0.685125
0.8  0.708217  0.685663       NaN  0.670028
1.0  0.714813  0.685125  0.670028       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.034432  0.037040  0.046372
0.5  0.034432       NaN  0.043226  0.044411
0.8  0.037040  0.043226       NaN  0.037820
1.0  0.046372  0.044411  0.037820       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.735524             0.70023            0.035294

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.765795          0.2                    0
1              1          0.765795          0.2                    1
2              2          0.765795          0.2                    2
3              3          0.765795          0.2                    3
4              4          0.765795          0.2                    4
..           ...               ...          ...                  ...
75            45          0.654052          0.8                    5
76            42          0.652232          0.8                    2
77            36          0.649760          0.5                   16
78            62          0.638707          1.0                    2
79            64          0.623357          1.0                    4

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.765795
outlier_idx = 64, outlier_score = 0.623357


==============================
矩阵: mat5INV
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.692119     0.088029     0.496809     0.955818

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.955818,0.000000,0.955818,0.955818
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.665990,0.045522,0.551696,0.772613
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.657599,0.051860,0.547843,0.826292
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.639149,0.054044,0.516340,0.767496

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.718904  0.697623  0.717965
0.5  0.718904       NaN  0.652944  0.647029
0.8  0.697623  0.652944       NaN  0.646958
1.0  0.717965  0.647029  0.646958       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.048668  0.046459  0.049345
0.5  0.048668       NaN  0.047963  0.052849
0.8  0.046459  0.047963       NaN  0.056896
1.0  0.049345  0.052849  0.056896       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.729639            0.680237            0.049402

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.770258          0.2                    0
1              1          0.770258          0.2                    1
2              2          0.770258          0.2                    2
3              3          0.770258          0.2                    3
4              4          0.770258          0.2                    4
..           ...               ...          ...                  ...
75            47          0.621634          0.8                    7
76            74          0.619295          1.0                   14
77            53          0.619031          0.8                   13
78            44          0.602445          0.8                    4
79            65          0.587802          1.0                    5

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.770258
outlier_idx = 65, outlier_score = 0.587802


==============================
矩阵: mat6POUR
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.661442     0.068497      0.52778     0.895031

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.895031,0.000000,0.895031,0.895031
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.649531,0.036864,0.528347,0.789864
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.671667,0.048588,0.535501,0.777457
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.642749,0.038784,0.548006,0.796783

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.640356  0.634168  0.637420
0.5  0.640356       NaN  0.651115  0.643529
0.8  0.634168  0.651115       NaN  0.660792
1.0  0.637420  0.643529  0.660792       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.023040  0.020714  0.021192
0.5  0.023040       NaN  0.040915  0.036316
0.8  0.020714  0.040915       NaN  0.042280
1.0  0.021192  0.036316  0.042280       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.714744            0.644563            0.070181

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0              0          0.699297          0.2                    0
1              1          0.699297          0.2                    1
2              2          0.699297          0.2                    2
3              3          0.699297          0.2                    3
4              4          0.699297          0.2                    4
..           ...               ...          ...                  ...
75            36          0.615018          0.5                   16
76            73          0.612629          1.0                   13
77            34          0.612398          0.5                   14
78            52          0.610927          0.8                   12
79            55          0.602677          0.8                   15

[80 rows x 4 columns]

prototype_idx = 0, prototype_score = 0.699297
outlier_idx = 55, outlier_score = 0.602677


==============================
矩阵: mat7OR
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.708271     0.083142     0.524267     0.969586

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.969586,0.000000,0.969586,0.969586
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.706651,0.050354,0.586890,0.845730
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.686086,0.053115,0.524267,0.845879
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.704915,0.043732,0.588706,0.802643

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.687992  0.665827  0.692657
0.5  0.687992       NaN  0.695153  0.705622
0.8  0.665827  0.695153       NaN  0.691152
1.0  0.692657  0.705622  0.691152       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.043245  0.048917  0.051423
0.5  0.043245       NaN  0.054242  0.053124
0.8  0.048917  0.054242       NaN  0.053664
1.0  0.051423  0.053124  0.053664       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.766809            0.689734            0.077075

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             63          0.762219          1.0                    3
1              0          0.751287          0.2                    0
2              2          0.751287          0.2                    2
3              1          0.751287          0.2                    1
4              4          0.751287          0.2                    4
..           ...               ...          ...                  ...
75            37          0.657465          0.5                   17
76            39          0.647168          0.5                   19
77            42          0.633729          0.8                    2
78            53          0.632715          0.8                   13
79            48          0.631991          0.8                    8

[80 rows x 4 columns]

prototype_idx = 63, prototype_score = 0.762219
outlier_idx = 48, outlier_score = 0.631991


==============================
矩阵: mat8ECCC
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.575143     0.064746     0.436574     0.800816

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.750305,0.000000,0.750305,0.750305
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.576466,0.053445,0.479259,0.738287
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.569159,0.064358,0.460441,0.730253
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.558216,0.049330,0.460952,0.680968

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.563275  0.561626  0.552542
0.5  0.563275       NaN  0.570968  0.565509
0.8  0.561626  0.570968       NaN  0.563994
1.0  0.552542  0.565509  0.563994       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.037397  0.029191  0.036368
0.5  0.037397       NaN  0.056308  0.050690
0.8  0.029191  0.056308       NaN  0.059389
1.0  0.036368  0.050690  0.059389       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.613537            0.562986            0.050551

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             51          0.663793          0.8                   11
1             67          0.632366          1.0                    7
2             26          0.629776          0.5                    6
3             44          0.618505          0.8                    4
4             29          0.615729          0.5                    9
..           ...               ...          ...                  ...
75            73          0.535974          1.0                   13
76            77          0.535952          1.0                   17
77            58          0.534450          0.8                   18
78            22          0.525588          0.5                    2
79            76          0.514582          1.0                   16

[80 rows x 4 columns]

prototype_idx = 51, prototype_score = 0.663793
outlier_idx = 76, outlier_score = 0.514582


==============================
矩阵: mat9N
==============================

[方法1] 整体稳定性（非对角元素统计）

   offdiag_mean  offdiag_std  offdiag_min  offdiag_max
0      0.543311     0.245823     0.009193     0.972853

[方法2-A] 温度内稳定性

,temperature,sample_indices,within_mean,within_std,within_min,within_max
0,0.2,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",0.972504,0.000000,0.972504,0.972504
1,0.5,"[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 3...",0.496382,0.165997,0.010790,0.970563
2,0.8,"[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 5...",0.545982,0.182868,0.056459,0.960495
3,1.0,"[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 7...",0.457906,0.217075,0.009193,0.933275

[方法2-B] 温度间均值矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.479001  0.614979  0.513941
0.5  0.479001       NaN  0.506944  0.481869
0.8  0.614979  0.506944       NaN  0.520855
1.0  0.513941  0.481869  0.520855       NaN

[方法2-C] 温度间标准差矩阵

          0.2       0.5       0.8       1.0
0.2       NaN  0.258379  0.258042  0.291102
0.5  0.258379       NaN  0.170306  0.177973
0.8  0.258042  0.170306       NaN  0.198798
1.0  0.291102  0.177973  0.198798       NaN

[方法2-D] 温度分解汇总

   overall_within_mean  overall_cross_mean  within_minus_cross
0             0.618194            0.519598            0.098595

[方法3] 原型 / 离群分析（按 row mean offdiag 排序）

    sample_index  row_mean_offdiag  temperature  local_index_in_temp
0             50          0.648622          0.8                   10
1              0          0.640962          0.2                    0
2              2          0.640962          0.2                    2
3              1          0.640962          0.2                    1
4              4          0.640962          0.2                    4
..           ...               ...          ...                  ...
75            69          0.335772          1.0                    9
76            74          0.311847          1.0                   14
77            31          0.291657          0.5                   11
78            70          0.285909          1.0                   10
79            63          0.254095          1.0                    3

[80 rows x 4 columns]

prototype_idx = 50, prototype_score = 0.648622
outlier_idx = 63, outlier_score = 0.254095